<?php

return [
    'leaderboard' => 'Leaderboard',
    'tournament' => 'Tournament',
    'maps' => 'Maps',
    'mapsBrowse' => 'Browse',
    'myMaps' => 'My maps',
    'mapsDesigner' => 'Map Designer',
    'randomMap' => 'Random map',
    'mapsLatestGames' => 'Latest games',
    'guide' => 'Guide',
    'login' => 'Login',
    'register' => 'Register',
    'myProfile' => 'My profile',
    'myImprovement' => 'My improvement',
    'favReplays' => 'Favorite replays',
    'settings' => 'Settings',
    'logout' => 'Logout',
    
    /* Leaderboard */
    'name' => 'Name',
    'time' => 'Time',
    'blocks' => 'Blocks',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Date',
    'replay' => 'Replay',
    'place' => 'Place',
    'nli' => 'Not logged in!',
    'today' => 'Today',
    'lastWeek' => 'Last week',
    'lastMonth' => 'Last month',
    'lastYear' => 'Last year',
    'allTime' => 'All time',
    'bestPlayers' => 'Best players',
    'bestGames' => 'Best games',
    'bestSubs' => 'Best subs',
    'latestGames' => 'Latest games',
    'leastBlocks' => 'The least blocks',
    'myTimes' => 'My times',
    'perfectFinesse' => '0 finesse',
    
    /* Replay */
    'load' => 'Load',
    'play' => 'Play',
    'pause' => 'Pause',
    'showSeg' => 'Show segments',
    'fastestSeg' => 'Fastest segments',
    'slowestSeg' => 'Slowest segments',
    'speedChart' => 'Speed chart',
    'moreStats' => 'More stats',
    'lines' => 'Lines',
    'scoringPlaylist' => 'Scoring playlist',
    'filterSP' => 'Filter scoring playlist',
    'applyFilter' => 'Apply filter',
    'timestamp' => 'Timestamp',
    'action' => 'Action', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Score equivalent',
    'position' => 'Position', //position in a replay
    'lAVG' => 'Local average',
    'gAVG' => 'Global average',
    'repHelp' => 'Help', //link that shows information how to use the tool
    'repExport' => 'GIF or video',
    
    /* PW change */
    'pwChange' => 'Change password',
    'newPw' => 'New Password',
    'againPw' => 'Again',
    'applyChange' => 'Apply change',
    'emailChange' => 'שינוי דוא"ל',
    'currentEmail' => 'נוכחי',
    'newEmail' => 'דוא"ל חדש',
    
    /* Localization settings */
    'localSettings' => 'Localization settings',
    'lang' => 'Language',
    'langNone' => 'None (selectable in the top menu)',
    'langDesc' => 'Select the preferred language.',
    'timezone' => 'Timezone',
    'timezoneDesc' => 'Used to convert time into your local time.',
    'country' => 'Country',
    'continent' => 'Continent',
    'countryDesc' => 'Used to display per-country leader boards.',
    
    /* Profile */
    'ownProfile' => 'This is your public profile accessible at',
    'bestTimes' => 'Best times',
    'allTimes' => 'View all sprint times',
    'userImpr' => 'View improvement stats',
    'gameStats' => 'Game stats',
    'latestGames' => 'Latest games',
    'noGames' => 'This user has not played any games yet.',
    'gamesPlayed' => 'Games',
    'totalTime' => 'Total time',
    'linesSent' => 'Lines sent',
    'linesRec' => 'Lines received',
    'placedBlocks' => 'Placed blocks',
    'blockCnt' => ':cnt blocks',
    'APM10Games' => '10-games APM',
    'PPS10Games' => '10-games PPS',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Combo',
    'longestGame' => 'Longest game',
    'totalB2B' => 'Total B2Bs',
    'mostSent' => 'Most sent',
    'hours' => 'hours',
    'minutes' => 'minutes',
    'createdMaps' => 'Created maps',
    'viewMapsBy' => 'View all maps created by',
    'playersCount' => 'Players',
    'gameResultPosition' => 'Position',
    'gameResultRoundTime' => 'Gametime',
    'viewAllGamesOf' => 'View all games of :mode',
    'noGamesOf' => ':name hasn\'t played any games of :mode yet.',
    
    /* Maps */
    'map' => 'Map',
    'mapCreate' => 'Create new',
    'mapName' => 'Name',
    'mapNameLong' => 'Map name',
    'mapDesc' => 'Description',
    'mapRules' => 'Rules',
    'mapOptions' => 'Options',
    'mapPlay' => 'Play',
    'mapPlayLink' => 'Play Map',
    'mapAuthor' => 'Author',
    'mapCreatedBy' => 'Created by',
    'backToMaps' => 'Back to maps',
    'playThisMap' => 'Play this map',
    'search' => 'Search',
    'myMaps' => 'My maps',
    'mapsByUser' => ':name\'s maps',
    'displayUnpublished' => 'Display :cnt unpublished maps',
    'displayPublished' => 'Display :cnt published maps',
    'usersMapMedals' => ':name\'s map medals',
    'usersCompletedMaps' => ':name\'s completed maps',
    'showRecords' => 'Show records',
    'details' => 'Details',
    'playedBy' => 'Played by',
    'latestMapGames' => 'The latest map games',

    /* Stats */
    'improvementStats' => 'Improvement stats',
    //keep ':name'
    'improvementInfo' => 'The following graph shows line race time (Y axis) vs game date (X axis). Highlighted line shows improvements in :name\'s personal records. You can place your cursor over any point to show the game details.',
    'date' => 'Date',
    'result' => 'Result',
    'submit' => 'Submit',
    'qSettings' => 'Query settings',
    'dispAll' => 'Display all games',
    
    /* About */
    'aboutInfo' => 'Jstris is a simple online multiplayer block game built in Javascript, HTML5 and Python (server).',
    'version' => 'Version',
    'changelog' => 'Changelog',
    'discussion' => 'Discussion',
    'learnMore' => 'Learn more',
    'contact' => 'Contact',
    'serverCoverage' => 'Server cost coverage',
    'supporters' => 'Project supporters',
    'translators' => 'Translators',
    'moderators' => 'Moderators',
    
    /* Other */
    'notFound' => 'Not found.',
    'invalidLink' => 'Requested link is invalid.',
    'brb' => 'Be right back.',
    'tryAgain' => 'Site is being updated, please try again in a few moments.',

    /* Settings - Other options */
    'setOther' => 'Other options',
    'hideAcc' => 'Hidden account',
    'accVisibility' => 'Visibility',
    'hideAccInfo' => 'If enabled, the account will be excluded from public leaderboards.',

    /* Chat reports */
    'reportU' => 'Report user',
    'reportDesc' => 'Here you can create a report if you think someone has abused the game chat.',
    'user' => 'User',
    'reason' => 'Reason',
    'rr0' => 'Spam or unwanted advertising',
    'rr1' => 'Sexually explicit content',
    'rr2' => 'Hate speech',
    'rr3' => 'Harassment or bullying',
    'rr4' => 'Other (specify)',
    'sendReport' => 'Send report',
    
    /* Settings - Navigation */
    'setProfileNav' => 'פרופיל',
    'setLocalizationNav' => 'לוקליזציה',
    'setPasswordNav' => 'סיסמה',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => 'אחר',

    /* Settings - Discord */
    'setDiscordTitle' => 'חיבור ל-Discord',
    'disconnect' => 'נתק',
    'connectDiscord' => 'חבר Discord',

    /* Settings - Other */
    'setExperiments' => 'ניסויים',
    'setExperimentsDesc' => 'אפשר גישת בדיקה לפיצ׳רים ניסיוניים/לא גמורים',
    'setExperimentsNote' => 'שתף רעיונות על פיצ׳רים שנבדקו ב-Discord של Jstris',
    'deleteAccount' => 'מחק חשבון',

    /* Settings - Supporter History */
    'returnBack' => 'חזור',
    'giftBalanceHistory' => 'היסטוריית יתרת מתנות',
    'message' => 'הודעה',
    'change' => 'שינוי',
    'before' => 'לפני',
    'after' => 'אחרי',
    'relative' => 'יחסי',
    'none' => 'ללא',

    /* Settings - Supporter Status */
    'subscription' => 'מנוי',
    'active' => 'פעיל',
    'manage' => 'ניהול',
    'renewsOn' => 'מתחדש ב:',
    'oneTime' => 'חד-פעמי',
    'expires' => 'פג תוקף',
    'extend' => 'הרחב',
    'giftingBalance' => 'יתרת מתנות',
    'days' => 'ימים',
    'add' => 'הוסף',
    'useCode' => 'השתמש בקוד',
    'balanceHistory' => 'היסטוריית יתרה',
    'noExpiration' => 'ללא תוקף',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'העלה תמונה מותאמת',
    'uploadCustomImageDesc' => 'בחר תמונה לשימוש כתמונת פרופיל ציבורית ב-Jstris. ניתן להסיר אם דווחה כפוגענית.',
    'supporterOption' => 'אפשרות Supporter',
    'seeDetails' => 'צפה בפרטים',
    'uploadPreviewCrop' => 'העלה לתצוגה מקדימה וחיתוך',

    /* Settings - Profile */
    'remove' => 'הסר',
    'noImageSelected' => 'לא נבחרה עדיין תמונה',
    'bioPlaceholder' => 'הקלד הודעה שתופיע בפרופיל שלך',
    'bioFormatInfo' => 'ניתן לעצב קישורים כך: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'חשבונות Supporter יכולים להשתמש בעיצוב, להוסיף קישורים ואמוג׳ים',
    'selectProfileImage' => 'בחר תמונת פרופיל',
    'jstrisBlocks' => 'בלוקים של Jstris',
    'animalArt' => 'אמנות חיות',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris חינמי וללא פרסומות. בתמיכה תוכל לפתוח את היתרונות הבאים:',
    'benefitProfileCustomizations' => 'התאמות פרופיל',
    'benefitProfileCustomizationsDesc' => 'באפשרותך להעלות תמונת פרופיל מותאמת ולהשתמש בעיצוב מורחב בהודעת "עליי" (עד 2000 תווים, קישורים ואמוג׳ים).',
    'benefitSaveMatchesBots' => 'שמירת משחקים מול בוטים',
    'benefitSaveMatchesBotsDesc' => 'משחקי 1v1 מול בוטים יישמרו בתוצאות כולל ריפליים וסטטיסטיקות מתקדמות.',
    'benefitUnlimitedReplays' => 'ריפליים ללא הגבלה',
    'benefitUnlimitedReplaysDesc' => 'אף ריפליי ממצבי שחקן יחיד לא יימחק כל עוד ה-Supporter פעיל.',
    'getSupporterCta' => 'קבל Jstris Supporter!',
    'configureBenefits' => 'הגדר יתרונות',
    'nameChange' => 'שינוי שם',
    'nameChangeInfo' => 'כ-Supporter ניתן לשנות שם פעם בחודש. שנה כאן:',
    'newNameLabel' => 'שם חדש',
    'newNamePlaceholder' => 'הכנס שם משתמש חדש',
    'manageSubscriptionTitle' => 'ניהול מנוי Jstris',
    'manageSubscriptionInfo1' => 'להשהיה/ביטול, התחבר ל-PayPal ובחר בלוח הניהול.',
    'manageSubscriptionInfo2' => 'בבעיות: jstris@jezevec10.com.',
    'close' => 'סגור',
];
