<?php

return [
    'leaderboard' => 'Žebříček',
    'tournament' => 'Turnaj',
    'maps' => 'Mapy',
    'mapsBrowse' => 'Procházet',
    'myMaps' => 'Moje mapy',
    'mapsDesigner' => 'Tvorba map',
    'randomMap' => 'Náhodná mapa',
    'mapsLatestGames' => 'Nedávné hry',
    'guide' => 'Průvodce',
    'login' => 'Přihlásit',
    'register' => 'Zaregistrovat',
    'myProfile' => 'Můj profil',
    'myImprovement' => 'Moje zlepšení',
    'favReplays' => 'Oblíbené nahrávky',
    'friends' => 'Přátelé',    
    'settings' => 'Nastavení',
    'logout' => 'Odhlásit',
    
    /* Leaderboard */
    'name' => 'Jméno',
    'time' => 'Čas',
    'blocks' => 'Bloků',
    'PPS' => 'PPS',
    'finesse' => 'Obratnost',
    'date' => 'Datum',
    'replay' => 'Záznam',
    'place' => 'Místo',
    'nli' => 'Nejste přihlášeni!',
    'today' => 'Dnes',
    'lastWeek' => 'Minulý týden',
    'lastMonth' => 'Minulý měsíc',
    'lastYear' => 'Minulý rok',
    'allTime' => 'Celkově',
    'bestPlayers' => 'Nejlepší hráči',
    'bestGames' => 'Nejlepší hry',
    'bestSubs' => 'Nejlepší pod...',
    'latestGames' => 'Nedávné hry',
    'leastBlocks' => 'Nejméně bloků',
    'myTimes' => 'Moje časy',
    'perfectFinesse' => 'Bezchybná finesse',
    
    /* Replay */
    'load' => 'Načíst',
    'play' => 'Hrát',
    'pause' => 'Pauza',
    'showSeg' => 'Zobrazit úseky',
    'fastestSeg' => 'Nejrychlejší úseky',
    'slowestSeg' => 'Nejpomalejší úseky',
    'speedChart' => 'Tabulka rychlostí',
    'moreStats' => 'Další statistiky',
    'lines' => 'Řádků',
    'scoringPlaylist' => 'Seznam skóre',
    'filterSP' => 'Filtr seznamu skóre',
    'applyFilter' => 'Použít filtr',
    'timestamp' => 'Časová značka',
    'action' => 'Trik', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Bodová hodnota',
    'position' => 'Pozice', //position in a replay
    'lAVG' => 'Lokální průměr',
    'gAVG' => 'Celkový průměr',
    'repHelp' => 'Nápověda', //link that shows information how to use the tool
    'repExport' => 'GIF nebo video',
    
    /* PW change */
    'pwChange' => 'Změna hesla',
    'newPw' => 'Nové heslo',
    'againPw' => 'Znovu',
    'applyChange' => 'Použít změny',
    
    /* Localization settings */
    'localSettings' => 'Jazyk a region',
    'lang' => 'Jazyk',
    'langNone' => 'Žádné (vyberte nahoře)',
    'langDesc' => 'Vyberte preferovaný jazyk.',
    'timezone' => 'Časová zóna',
    'timezoneDesc' => 'Vaše časová zóna',
    'country' => 'Země',
    'continent' => 'Kontinent',
    'countryDesc' => 'Použito k zobrazení skóre podle země.',
    
    /* Profile */
    'ownProfile' => 'Tohle je váš veřejný profil, dostupný na',
    'bestTimes' => 'Nejlepší časy',
    'allTimes' => 'Zobrazit všechny časy sprintu',
    'userImpr' => 'Zobrazit statistiky zlepšení',
    'userRanking' => 'Statistiky žebříčku',
    'gameStats' => 'Statistiky her',
    'latestGames' => 'Nedávné hry',
    'noGames' => 'Hráč ještě nikdy nehrál.',
    'gamesPlayed' => 'Her',
    'totalTime' => 'Celkový čas',
    'linesSent' => 'Odeslaných řádků',
    'linesRec' => 'Obdržených řádků',
    'placedBlocks' => 'Umístěných bloků',
    'blockCnt' => ':cnt bloků',
    'APM10Games' => 'APM za 10 her',
    'PPS10Games' => 'PPS za 10 her',
    'maxAPM' => 'Nejvíc APM',
    'maxREN' => 'Největší kombo',
    'longestGame' => 'Nejdelší hra',
    'totalB2B' => 'Celkem Back-To-Back',
    'mostSent' => 'Nejvíce odeslaných',
    'hours' => 'hodin',
    'minutes' => 'minut',
    'createdMaps' => 'Vytvořené mapy',
    'viewMapsBy' => 'Všechny mapy od',
    'playersCount' => 'Hráčů',
    'gameResultPosition' => 'Pozice',
    'gameResultRoundTime' => 'Doba hry',
    'viewAllGamesOf' => 'Všechny hry v režimu :mode',
    'noGamesOf' => ':name ještě nehrál :mode.',
    
    /* Maps */
    'map' => 'Mapa',
    'mapCreate' => 'Vytvořit novou',
    'mapName' => 'Název',
    'mapNameLong' => 'Název mapy',
    'mapDesc' => 'Popis',
    'mapRules' => 'Pravidla',
    'mapOptions' => 'Možnosti',
    'mapPlay' => 'Hrát',
    'mapPlayLink' => 'Hrát mapu',
    'mapAuthor' => 'Autor',
    'mapCreatedBy' => 'Vytvořil/a',
    'backToMaps' => 'Zpátky k mapám',
    'playThisMap' => 'Hrát tuto mapu',
    'search' => 'Hledat',
    'myMaps' => 'Moje mapy',
    'mapsByUser' => 'Mapy od :name',
    'displayUnpublished' => 'Zobrazit :cnt nezveřejněných map',
    'displayPublished' => 'Zobrazit :cnt veřejných map',
    'usersMapMedals' => 'Medaile za mapy hráče :name',
    'usersCompletedMaps' => ':Dokončené mapy hráče :name',
    'showRecords' => 'Zobrazit rekordy',
    'details' => 'Podrobnosti',
    'playedBy' => 'Hráčů',
    'latestMapGames' => 'Nedávno hrané mapy',

    /* Stats */
    'improvementStats' => 'Statistiky zlepšení',
    //keep ':name'
    'improvementInfo' => 'Tento graf ukazuje čas závodu (svislá osa) v závislosti na datumu (vodorovná osa) v osobních statistikách hráče :name. Přejetím kurzorem nad kterýkoliv bod si zobrazíte detaily.',
    'date' => 'Datum',
    'result' => 'Výsledek',
    'submit' => 'Odeslat',
    'qSettings' => 'Nastavení dotazu',
    'dispAll' => 'Zobrazit všechny hry',
    
    /* About */
    'aboutInfo' => 'Jstris je jednoduchá online hra s bloky vytvořená v Javascriptu, HTML5 a Pythonu (server).',
    'version' => 'Verze',
    'changelog' => 'Seznam změn',
    'discussion' => 'Diskuze',
    'learnMore' => 'Zjistit víc',
    'contact' => 'Kontakt',
    'serverCoverage' => 'Náklady na provoz',
    'supporters' => 'Sponzoři projektu',
    'translators' => 'Překladatelé',
    'moderators' => 'Moderátoři',

    /* Other */
    'notFound' => 'Nenalezeno.',
    'invalidLink' => 'Odkaz je neplatný.',
    'brb' => 'Vydržte chvilku.',
    'tryAgain' => 'Aktualizujeme stránku, zkuste to za chvíli znovu.',

    /* Settings - Other options */
    'setOther' => 'Další možnosti',
    'hideAcc' => 'Skrytý účet',
    'accVisibility' => 'Viditelnost',
    'hideAccInfo' => 'Po aktivaci nebude tento účet zobrazován ve veřejném žebříčku.',

    /* Chat reports */
    'reportU' => 'Nahlásit uživatele',
    'reportDesc' => 'Pokud si myslíte, že došlo ke zneužití chatu, můžete uživatele nahlásit.',
    'user' => 'Uživatel',
    'reason' => 'Důvod',
    'rr0' => 'Spam nebo reklama',
    'rr1' => 'Sexuální obsah',
    'rr2' => 'Nenávist',
    'rr3' => 'Obtěžování nebo šikana',
    'rr4' => 'Jiné (uveďte)',
    'sendReport' => 'Odeslat',

    /* Friends */
    'accept' => 'Přijmout',
    'ignore' => 'Ignorovat',
    'pending' => 'Příchozí žádosti',
    'frFilter' => 'Filtrovat jména',
    'noPending' => 'V tuto chvíli nemáte žádné žádosti.',
    'onlineNow' => 'Nyní online',
    'recentlyAc' => 'Nedávno aktivní',
    'lastActive' => 'Aktivní :when',
    'noFriends' => 'Váš seznam přátel je v tuto chvíli prázdný.',
    'ruSure' => 'Jste si jistí?',
    'rmFriend' => 'Chcete tohoto uživatele odstranit ze seznamu přátel?',
    'rmConfirm' => 'Ano, odstranit',
];
