<?php

return [
    'leaderboard' => 'Žebříček',
    'tournament' => 'Turnaj',
    'maps' => 'Mapy',
    'mapsBrowse' => 'Procházet',
    'myMaps' => 'Moje mapy',
    'mapsDesigner' => 'Tvorba map',
    'randomMap' => 'Náhodná mapa',
    'mapsLatestGames' => 'Nedávné hry',
    'guide' => 'Průvodce',
    'login' => 'Přihlásit',
    'register' => 'Zaregistrovat',
    'myProfile' => 'Můj profil',
    'myImprovement' => 'Moje zlepšení',
    'favReplays' => 'Oblíbené nahrávky',
    'friends' => 'Přátelé',    
    'settings' => 'Nastavení',
    'logout' => 'Odhlásit',
    
    /* Leaderboard */
    'name' => 'Jméno',
    'time' => 'Čas',
    'blocks' => 'Bloků',
    'PPS' => 'PPS',
    'finesse' => 'Obratnost',
    'date' => 'Datum',
    'replay' => 'Záznam',
    'place' => 'Místo',
    'nli' => 'Nejste přihlášeni!',
    'today' => 'Dnes',
    'lastWeek' => 'Minulý týden',
    'lastMonth' => 'Minulý měsíc',
    'lastYear' => 'Minulý rok',
    'allTime' => 'Celkově',
    'bestPlayers' => 'Nejlepší hráči',
    'bestGames' => 'Nejlepší hry',
    'bestSubs' => 'Nejlepší pod...',
    'latestGames' => 'Nedávné hry',
    'leastBlocks' => 'Nejméně bloků',
    'myTimes' => 'Moje časy',
    'perfectFinesse' => 'Bezchybná finesse',
    'mostGames' => 'Nejvíce her',
    
    /* Replay */
    'load' => 'Načíst',
    'play' => 'Hrát',
    'pause' => 'Pauza',
    'showSeg' => 'Zobrazit úseky',
    'fastestSeg' => 'Nejrychlejší úseky',
    'slowestSeg' => 'Nejpomalejší úseky',
    'speedChart' => 'Tabulka rychlostí',
    'moreStats' => 'Další statistiky',
    'lines' => 'Řádků',
    'scoringPlaylist' => 'Seznam skóre',
    'filterSP' => 'Filtr seznamu skóre',
    'applyFilter' => 'Použít filtr',
    'timestamp' => 'Časová značka',
    'action' => 'Trik', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Bodová hodnota',
    'position' => 'Pozice', //position in a replay
    'lAVG' => 'Lokální průměr',
    'gAVG' => 'Celkový průměr',
    'repHelp' => 'Nápověda', //link that shows information how to use the tool
    'repExport' => 'GIF nebo video',
    
    /* PW change */
    'pwChange' => 'Změna hesla',
    'newPw' => 'Nové heslo',
    'againPw' => 'Znovu',
    'applyChange' => 'Použít změny',
    'emailChange' => 'Změnit e-mail',
    'currentEmail' => 'Aktuální',
    'newEmail' => 'Nový e-mail',
    
    /* Localization settings */
    'localSettings' => 'Jazyk a region',
    'lang' => 'Jazyk',
    'langNone' => 'Žádné (vyberte nahoře)',
    'langDesc' => 'Vyberte preferovaný jazyk.',
    'timezone' => 'Časová zóna',
    'timezoneDesc' => 'Vaše časová zóna',
    'country' => 'Země',
    'continent' => 'Kontinent',
    'countryDesc' => 'Použito k zobrazení skóre podle země.',
    
    /* Profile */
    'ownProfile' => 'Tohle je váš veřejný profil, dostupný na',
    'bestTimes' => 'Nejlepší časy',
    'allTimes' => 'Zobrazit všechny časy sprintu',
    'userImpr' => 'Zobrazit statistiky zlepšení',
    'userRanking' => 'Statistiky žebříčku',
    'gameStats' => 'Statistiky her',
    'latestGames' => 'Nedávné hry',
    'noGames' => 'Hráč ještě nikdy nehrál.',
    'gamesPlayed' => 'Her',
    'totalTime' => 'Celkový čas',
    'linesSent' => 'Odeslaných řádků',
    'linesRec' => 'Obdržených řádků',
    'placedBlocks' => 'Umístěných bloků',
    'blockCnt' => ':cnt bloků',
    'APM10Games' => 'APM za 10 her',
    'PPS10Games' => 'PPS za 10 her',
    'maxAPM' => 'Nejvíc APM',
    'maxREN' => 'Největší kombo',
    'longestGame' => 'Nejdelší hra',
    'totalB2B' => 'Celkem Back-To-Back',
    'mostSent' => 'Nejvíce odeslaných',
    'hours' => 'hodin',
    'minutes' => 'minut',
    'createdMaps' => 'Vytvořené mapy',
    'viewMapsBy' => 'Všechny mapy od',
    'playersCount' => 'Hráčů',
    'gameResultPosition' => 'Pozice',
    'gameResultRoundTime' => 'Doba hry',
    'viewAllGamesOf' => 'Všechny hry v režimu :mode',
    'noGamesOf' => ':name ještě nehrál :mode.',
    
    /* Maps */
    'map' => 'Mapa',
    'mapCreate' => 'Vytvořit novou',
    'mapName' => 'Název',
    'mapNameLong' => 'Název mapy',
    'mapDesc' => 'Popis',
    'mapRules' => 'Pravidla',
    'mapOptions' => 'Možnosti',
    'mapPlay' => 'Hrát',
    'mapPlayLink' => 'Hrát mapu',
    'mapAuthor' => 'Autor',
    'mapCreatedBy' => 'Vytvořil/a',
    'backToMaps' => 'Zpátky k mapám',
    'playThisMap' => 'Hrát tuto mapu',
    'search' => 'Hledat',
    'myMaps' => 'Moje mapy',
    'mapsByUser' => 'Mapy od :name',
    'displayUnpublished' => 'Zobrazit :cnt nezveřejněných map',
    'displayPublished' => 'Zobrazit :cnt veřejných map',
    'usersMapMedals' => 'Medaile za mapy hráče :name',
    'usersCompletedMaps' => 'Dokončené mapy hráče :name',
    'showRecords' => 'Zobrazit rekordy',
    'details' => 'Podrobnosti',
    'playedBy' => 'Hráčů',
    'latestMapGames' => 'Nedávno hrané mapy',

    /* Stats */
    'improvementStats' => 'Statistiky zlepšení',
    //keep ':name'
    'improvementInfo' => 'Tento graf ukazuje čas závodu (svislá osa) v závislosti na datumu (vodorovná osa) v osobních statistikách hráče :name. Přejetím kurzorem nad kterýkoliv bod si zobrazíte detaily.',
    'date' => 'Datum',
    'result' => 'Výsledek',
    'submit' => 'Odeslat',
    'qSettings' => 'Nastavení dotazu',
    'dispAll' => 'Zobrazit všechny hry',
    
    /* About */
    'aboutInfo' => 'Jstris je jednoduchá online hra s bloky vytvořená v Javascriptu, HTML5 a Pythonu (server).',
    'version' => 'Verze',
    'changelog' => 'Seznam změn',
    'discussion' => 'Diskuze',
    'learnMore' => 'Zjistit víc',
    'contact' => 'Kontakt',
    'serverCoverage' => 'Náklady na provoz',
    'supporters' => 'Sponzoři projektu',
    'translators' => 'Překladatelé',
    'moderators' => 'Moderátoři',

    /* Other */
    'notFound' => 'Nenalezeno.',
    'invalidLink' => 'Odkaz je neplatný.',
    'brb' => 'Vydržte chvilku.',
    'tryAgain' => 'Aktualizujeme stránku, zkuste to za chvíli znovu.',
    'wasteDesc' => 'Podíl T bloků nevyužitých pro T-Spin (k celkovému počtu T bloků)',

    /* Settings - Other options */
    'setOther' => 'Další možnosti',
    'hideAcc' => 'Skrytý účet',
    'accVisibility' => 'Viditelnost',
    'hideAccInfo' => 'Po aktivaci nebude tento účet zobrazován ve veřejném žebříčku.',

    /* Chat reports */
    'reportU' => 'Nahlásit uživatele',
    'reportDesc' => 'Pokud si myslíte, že došlo ke zneužití chatu, můžete uživatele nahlásit.',
    'user' => 'Uživatel',
    'reason' => 'Důvod',
    'rr0' => 'Spam nebo reklama',
    'rr1' => 'Sexuální obsah',
    'rr2' => 'Nenávist',
    'rr3' => 'Obtěžování nebo šikana',
    'rr4' => 'Jiné (uveďte)',
    'sendReport' => 'Odeslat',

    /* Friends */
    'accept' => 'Přijmout',
    'ignore' => 'Ignorovat',
    'pending' => 'Příchozí žádosti',
    'frFilter' => 'Filtrovat jména',
    'noPending' => 'V tuto chvíli nemáte žádné žádosti.',
    'onlineNow' => 'Nyní online',
    'recentlyAc' => 'Nedávno aktivní',
    'lastActive' => 'Aktivní :when',
    'noFriends' => 'Váš seznam přátel je v tuto chvíli prázdný.',
    'ruSure' => 'Jste si jistí?',
    'rmFriend' => 'Chcete tohoto uživatele odstranit ze seznamu přátel?',
    'rmConfirm' => 'Ano, odstranit',
    
    /* Settings - Navigation */
    'setProfileNav' => 'Profil',
    'setLocalizationNav' => 'Jazyk a region',
    'setPasswordNav' => 'Heslo',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => 'Další',

    /* Settings - Discord */
    'setDiscordTitle' => 'Připojit Discord',
    'disconnect' => 'Odpojit',
    'connectDiscord' => 'Připojit Discord',

    /* Settings - Other */
    'setExperiments' => 'Experimenty',
    'setExperimentsDesc' => 'Povolit testovací přístup k experimentálním/nedokončeným funkcím',
    'setExperimentsNote' => 'Sdílejte své nápady k testovaným funkcím na Jstris Discordu',
    'deleteAccount' => 'Smazat účet',

    /* Settings - Supporter History */
    'returnBack' => 'Zpět',
    'giftBalanceHistory' => 'Historie dárkového zůstatku',
    'message' => 'Zpráva',
    'change' => 'Změna',
    'before' => 'Před',
    'after' => 'Po',
    'relative' => 'Relativní',
    'none' => 'Žádné',

    /* Settings - Supporter Status */
    'subscription' => 'Předplatné',
    'active' => 'aktivní',
    'manage' => 'Spravovat',
    'renewsOn' => 'Obnovuje se:',
    'oneTime' => 'Jednorázové',
    'expires' => 'Vyprší',
    'extend' => 'Prodloužit',
    'giftingBalance' => 'Dárkový zůstatek',
    'days' => 'dní',
    'add' => 'Přidat',
    'useCode' => 'Použít kód',
    'balanceHistory' => 'Historie zůstatku',
    'noExpiration' => 'Bez expirace',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'Nahrát vlastní obrázek',
    'uploadCustomImageDesc' => 'Vyberte obrázek, který bude použit jako veřejná profilová fotka na Jstrisu. Obrázek může být odstraněn, pokud bude nahlášen jako nevhodný.',
    'supporterOption' => 'Možnost pro Supportery',
    'seeDetails' => 'Zobrazit detaily',
    'uploadPreviewCrop' => 'Nahrát pro náhled a oříznutí',

    /* Settings - Profile */
    'remove' => 'Odebrat',
    'noImageSelected' => 'Zatím nebyl vybrán žádný obrázek',
    'bioPlaceholder' => 'Zadejte text, který se zobrazí na vašem profilu',
    'bioFormatInfo' => 'Odkazy můžete formátovat takto: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Účty Supporter mohou používat formátování, vkládat odkazy a emoty',
    'selectProfileImage' => 'Vybrat profilový obrázek',
    'jstrisBlocks' => 'Jstris bloky',
    'animalArt' => 'Zvířecí motivy',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris je bez reklam a zdarma pro všechny. Podporou odemknete následující výhody:',
    'benefitProfileCustomizations' => 'Úpravy profilu',
    'benefitProfileCustomizationsDesc' => 'Můžete nahrát vlastní profilový obrázek a použít rozšířené formátování v zprávě „O mně“ (až 2000 znaků, odkazy a emoty).',
    'benefitSaveMatchesBots' => 'Ukládání zápasů proti botům',
    'benefitSaveMatchesBotsDesc' => 'Vaše 1v1 proti botům se uloží do výsledků včetně záznamů a rozšířených statistik.',
    'benefitUnlimitedReplays' => 'Neomezené záznamy',
    'benefitUnlimitedReplaysDesc' => 'Žádné vaše záznamy z jednohráčských režimů nebudou při aktivním Supporterovi mazány.',
    'getSupporterCta' => 'Získat Jstris Supporter!',
    'configureBenefits' => 'Nastavit výhody',
    'nameChange' => 'Změna jména',
    'nameChangeInfo' => 'Jako Supporter můžete jednou měsíčně změnit své jméno. Změňte jej zde:',
    'newNameLabel' => 'Nové jméno',
    'newNamePlaceholder' => 'Zadejte nové uživatelské jméno',
    'manageSubscriptionTitle' => 'Správa předplatného Jstris',
    'manageSubscriptionInfo1' => 'Pro pozastavení nebo zrušení předplatného se přihlaste do svého účtu PayPal a vyberte příslušnou možnost na panelu předplatného.',
    'manageSubscriptionInfo2' => 'V případě problémů nás kontaktujte na jstris@jezevec10.com.',
    'close' => 'Zavřít',
];
