<?php

return [
    'leaderboard' => 'Bestenliste',
    'tournament' => 'Turnier',
    'maps' => 'Maps',
    'mapsBrowse' => 'Durchsuchen',
    'myMaps' => 'Meine Maps',
    'mapsDesigner' => 'Map Designer',
    'randomMap' => 'Zufällige Map',
    'mapsLatestGames' => 'Letzten Spiele',
    'guide' => 'Guide',
    'login' => 'Anmelden',
    'register' => 'Registrieren',
    'myProfile' => 'Mein Profil',
    'myImprovement' => 'Meine Fortschritt',
    'favReplays' => 'Lieblingswiederholungen',
    'settings' => 'Einstellungen',
    'logout' => 'Ausloggen',
    
    /* Leaderboard */
    'name' => 'Name',
    'time' => 'Zeit',
    'blocks' => 'Blöcke',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Datum',
    'replay' => 'Wiederholung',
    'place' => 'Platz',
    'nli' => 'Nicht eingeloggt!',
    'today' => 'Heute',
    'lastWeek' => 'Letzte Woche',
    'lastMonth' => 'Letzten Monat',
    'lastYear' => 'Letztes Jahr',
    'allTime' => 'Jederzeit',
    'bestPlayers' => 'Beste Spieler',
    'bestGames' => 'Beste Spiele',
    'bestSubs' => 'Beste unter',
    'latestGames' => 'Neusten Spiele',
    'leastBlocks' => 'Die wenigsten Blöcke',
    'myTimes' => 'Meine Zeit',
    'perfectFinesse' => '0 Finesse',

    /* Replay */
    'load' => 'Laden',
    'play' => 'Starten',
    'pause' => 'Pause',
    'showSeg' => 'Zeige Segmente',
    'fastestSeg' => 'Schnellstes Segment',
    'slowestSeg' => 'Langsamstes Segment',
    'speedChart' => 'Geschwindigkeitsdiagramm',
    'moreStats' => 'Mehr Statistiken',
    'lines' => 'Reihen',
    'scoringPlaylist' => 'Wertungsliste',
    'filterSP' => 'Wertungslistenfilter',
    'applyFilter' => 'Filter anwenden',
    'timestamp' => 'Zeitstempel',
    'action' => 'Aktion', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Entsprechende Punkte',
    'position' => 'Position', //position in a replay
    'lAVG' => 'Lokaler Durchschnitt',
    'gAVG' => 'Globaler Durchschnitt',
    'repHelp' => 'Hilfe', //link that shows information how to use the tool
    'repExport' => 'GIF oder Video',

    /* PW change */
    'pwChange' => 'Passwort ändern',
    'newPw' => 'Neues Passwort',
    'againPw' => 'Passwort wiederholen',
    'applyChange' => 'Anwenden',
    'emailChange' => 'E-Mail ändern',
    'currentEmail' => 'Aktuell',
    'newEmail' => 'Neue E-Mail',

    /* Localization settings */
    'localSettings' => 'Standorteinstellungen',
    'lang' => 'Sprache',
    'langNone' => 'Keine (selectable in the top menu)',
    'langDesc' => 'Wähle die gewünschte Sprache.',
    'timezone' => 'Zeitzone',
    'timezoneDesc' => 'Wird zur Konvertierung der Zeit verwendet',
    'country' => 'Land',
    'continent' => 'Kontinent',
    'countryDesc' => 'Wird zur Anzeige auf der Länderrangliste verwendet.',

    /* Profile */
    'ownProfile' => 'Das is dein Öffentliches Profil, erreichbar unter',
    'bestTimes' => 'Beste Zeiten',
    'allTimes' => 'Zeige alle Sprintzeiten',
    'userImpr' => 'Zeige Fortschritts-Statistik',
    'gameStats' => 'Spiel-Statistik',
    'latestGames' => 'Neuesten Spiele',
    'noGames' => 'Dieser Nutzer hat noch kein Spiel gespielt!',
    'gamesPlayed' => 'Spiele',
    'totalTime' => 'Totale Spielzeit',
    'linesSent' => 'Reihen gesendet',
    'linesRec' => 'Reihen erhalten',
    'placedBlocks' => 'Plazierte Blöcke',
    'blockCnt' => ':cnt Blöcke',
    'APM10Games' => '10-Spiele APM',
    'PPS10Games' => '10-Spiele PPS',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Kombo',
    'longestGame' => 'Längstes Spiel',
    'totalB2B' => 'Total B2Bs',
    'mostSent' => 'Meist Gesendete Reihen',
    'hours' => 'Stunden',
    'minutes' => 'Minuten',
    'createdMaps' => 'Erstellte Maps',
    'viewMapsBy' => 'Zeige alle erstellten Maps',
    'playersCount' => 'Spieler',
    'gameResultPosition' => 'Position',
    'gameResultRoundTime' => 'Spielzeit',
    'viewAllGamesOf' => 'Zeige alle Spiele von :mode',
    'noGamesOf' => ':name hat bislang noch keine :mode Spiele gespielt.',
    
    /* Maps */
    'map' => 'Map',
    'mapCreate' => 'Erstelle neue',
    'mapName' => 'Name',
    'mapNameLong' => 'Map Name',
    'mapDesc' => 'Beschreibung',
    'mapRules' => 'Regeln',
    'mapOptions' => 'Optionen',
    'mapPlay' => 'Spielen',
    'mapPlayLink' => 'Map spielen',
    'mapAuthor' => 'Autor',
    'mapCreatedBy' => 'Erstellt von',
    'backToMaps' => 'Zurück zu den Maps',
    'playThisMap' => 'Spiele die Map',
    'search' => 'Suchen',
    'myMaps' => 'Meine Maps',
    'mapsByUser' => ':names Maps',
    'displayUnpublished' => 'Zeige :cnt unveröffentlichte Maps',
    'displayPublished' => 'Zeige :cnt veröffentlichte Maps',
    'usersMapMedals' => ':names Map Medaillen',
    'usersCompletedMaps' => ':names fertige Maps',
    'showRecords' => 'Zeige Rekorde',
    'details' => 'Details',
    'playedBy' => 'Gespielt von',
    'latestMapGames' => 'Die letzten Spiele dieser Map',
    
    /* Stats */
    'improvementStats' => 'Fortschritts-Statistik',
    //keep ':name'
    'improvementInfo' => 'Der folgende Graph zeigt Sprint-Rundenzeit (Y Achse) vs Spieldatum (X Achse). Hervorgehobene Linienen zeigen den Fortschritt von :name\'s persönliche Rekorde. Mit der Maus können auf jedem Punkt Details über die Spiele eingesehen werden.',
    'date' => 'Datum',
    'result' => 'Ergebnis',
    'submit' => 'Einreichen',
    'qSettings' => 'Spiel-Modus',
    'dispAll' => 'Zeige alle Spiele',
    
    /* About */
    'aboutInfo' => 'Jstris ist ein einfaches Mehrspieler Blockbau Spiel, welches mit Hilfe von Javascript, HTML5 und Python (server) realisiert wurde.',
    'version' => 'Version',
    'changelog'=> 'Änderungsprotokoll',
    'discussion' => 'Diskussion',
    'learnMore' => 'Über',
    'contact' => 'Kontakt',
    'serverCoverage' => 'Server Kostendeckung',
    'supporters' => 'Projekt Unterstützer',
    'translators' => 'Übersetzer',
    'moderators' => 'Moderatoren',
    
    /* Other */
    'notFound' => 'Nicht gefunden.',
    'invalidLink' => 'Angeforderter Link ungültig.',
    'brb' => 'Wir sind bald zurück.',
    'tryAgain' => 'Die Webseite wird aktuell geupdated, versuche es bitte später nochmal.',

    /* Settings - Other options */
    'setOther' => 'Andere Optionen',
    'hideAcc' => 'Verstecktes Konto',
    'accVisibility' => 'Sichtbarkeit',
    'hideAccInfo' => 'Wenn aktiviert, wird das Konto von öffentlichen Bestenlisten ausgeschlossen.',

    /* Chat reports */
    'reportU' => 'Benutzer melden',
    'reportDesc' => 'Hier können Sie einen Bericht erstellen, wenn Sie denken, jemand hat das Spiel chat missbraucht.',
    'user' => 'Benutzer',
    'reason' => 'Grund',
    'rr0' => 'Spam oder unerwünschte Werbung',
    'rr1' => 'Sexuell explizite Inhalte',
    'rr2' => 'Hassreden',
    'rr3' => 'Belästigung oder Mobbing',
    'rr4' => 'Andere (angeben)',
    'sendReport' => 'Bericht senden',

    /* Friends */
    'accept' => 'Akzeptiere',
    'ignore' => 'Ablehnen',
    'pending' => 'Ausstehende Anträge',
    'frFilter' => 'Suche',
    'noPending' => 'Im Moment haben Sie keine ausstehenden Freundschaftsanfragen.',
    'onlineNow' => 'Jetzt online',
    'recentlyAc' => 'Kürzlich aktiv',
    'lastActive' => 'Aktiv :when',
    'noFriends' => 'Im Moment ist Ihre Freundesliste leer.',
    'ruSure' => 'Sind Sie sicher?',
    'rmFriend' => 'Möchten Sie diese Person von Ihrer Freundesliste entfernen?',
    'rmConfirm' => 'entfernen',
    
    /* Settings - Navigation */
    'setProfileNav' => 'Profil',
    'setLocalizationNav' => 'Lokalisierung',
    'setPasswordNav' => 'Passwort',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => 'Sonstiges',

    /* Settings - Discord */
    'setDiscordTitle' => 'Discord verbinden',
    'disconnect' => 'Trennen',
    'connectDiscord' => 'Discord verbinden',

    /* Settings - Other */
    'setExperiments' => 'Experimente',
    'setExperimentsDesc' => 'Testzugang zu experimentellen/unfertigen Funktionen aktivieren',
    'setExperimentsNote' => 'Teile deine Ideen zu getesteten Funktionen im Jstris Discord',
    'deleteAccount' => 'Konto löschen',

    /* Settings - Supporter History */
    'returnBack' => 'Zurück',
    'giftBalanceHistory' => 'Verlauf Guthaben zum Verschenken',
    'message' => 'Nachricht',
    'change' => 'Änderung',
    'before' => 'Vorher',
    'after' => 'Nachher',
    'relative' => 'Relativ',
    'none' => 'Keine',

    /* Settings - Supporter Status */
    'subscription' => 'Abo',
    'active' => 'aktiv',
    'manage' => 'Verwalten',
    'renewsOn' => 'Erneuert am:',
    'oneTime' => 'Einmalig',
    'expires' => 'Läuft ab',
    'extend' => 'Verlängern',
    'giftingBalance' => 'Guthaben zum Verschenken',
    'days' => 'Tage',
    'add' => 'Hinzufügen',
    'useCode' => 'Code verwenden',
    'balanceHistory' => 'Verlauf',
    'noExpiration' => 'Kein Ablauf',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'Eigenes Bild hochladen',
    'uploadCustomImageDesc' => 'Wähle ein Bild als öffentliches Profilbild in Jstris. Das Bild kann entfernt werden, wenn es als anstößig gemeldet wird.',
    'supporterOption' => 'Supporter-Option',
    'seeDetails' => 'Details ansehen',
    'uploadPreviewCrop' => 'Hochladen zum Vorschau & Zuschneiden',

    /* Settings - Profile */
    'remove' => 'Entfernen',
    'noImageSelected' => 'Noch kein Bild ausgewählt',
    'bioPlaceholder' => 'Text eingeben, der in deinem Profil erscheint',
    'bioFormatInfo' => 'Hyperlinks so formatieren: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Supporter-Konten können formatieren, Links und Emotes einfügen',
    'selectProfileImage' => 'Profilbild auswählen',
    'jstrisBlocks' => 'Jstris Blöcke',
    'animalArt' => 'Tierkunst',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris ist werbefrei und kostenlos. Mit deiner Unterstützung schaltest du folgende Vorteile frei:',
    'benefitProfileCustomizations' => 'Profilanpassungen',
    'benefitProfileCustomizationsDesc' => 'Eigenes Profilbild hochladen und erweitertes Formatieren in der "Über mich"-Nachricht (bis 2000 Zeichen, Hyperlinks und Emotes).',
    'benefitSaveMatchesBots' => 'Spiele gegen Bots speichern',
    'benefitSaveMatchesBotsDesc' => 'Deine 1v1 gegen Bots werden bei den Ergebnissen gespeichert, inkl. Replays und erweiterter Statistiken.',
    'benefitUnlimitedReplays' => 'Unbegrenzte Replays',
    'benefitUnlimitedReplaysDesc' => 'Solange du Supporter bist, werden keine Singleplayer-Replays gelöscht.',
    'getSupporterCta' => 'Jstris Supporter holen!',
    'configureBenefits' => 'Vorteile konfigurieren',
    'nameChange' => 'Namensänderung',
    'nameChangeInfo' => 'Als Supporter kannst du deinen Namen einmal im Monat ändern. Hier ändern:',
    'newNameLabel' => 'Neuer Name',
    'newNamePlaceholder' => 'Neuen Benutzernamen eingeben',
    'manageSubscriptionTitle' => 'Jstris-Abo verwalten',
    'manageSubscriptionInfo1' => 'Zum Pausieren/Kündigen, bei PayPal anmelden und Option im Abo-Dashboard wählen.',
    'manageSubscriptionInfo2' => 'Bei Problemen: jstris@jezevec10.com.',
    'close' => 'Schließen',

];
