<?php

return [
    'leaderboard' => 'lyderių lentelė',
    'tournament' => 'Turnyras',
    'mapsBrowse' => 'Naršyti',
    'mapsLatestGames' => 'Paskutiniai žaidimai',
    'guide' => 'Gidas',
    'login' => 'Prisijungti',
    'register' => 'Registruotis',
    'myProfile' => 'Profilis',
    'myImprovement' => 'Mano pažanga',
    'friends' => 'Draugai',
    'settings' => 'Nustatymai',
    'logout' => 'Atsijungti',
    
    /* Leaderboard */
    'name' => 'Vardas',
    'time' => 'Laikas',
    'blocks' => 'Blokai',
    'date' => 'Data',
    'place' => 'Vieta',
    'nli' => 'Jūs esate neprisijungę!',
    'today' => 'Šiandien',
    'lastWeek' => 'Praeitą savaitę',
    'lastMonth' => 'Prieš mėnesį',
    'lastYear' => 'Prieš metus',
    'allTime' => 'Visų laikų',
    'bestPlayers' => 'Geriausi žaidėjai',
    'bestGames' => 'Geriausi žaidimai',
    'latestGames' => 'Paskutiniai žaidimai',
    'leastBlocks' => 'Mažiausiai blokų',
    'myTimes' => 'Mano laikai',
    'mostGames' => 'Daugiausiai žaidimų',
    
    /* Replay */
    'load' => 'Krauti',
    'play' => 'Rodyti',
    'pause' => 'Pauzė',
    'showSeg' => 'Rodyti segmentus',
    'fastestSeg' => 'Greičiausi segmentai',
    'slowestSeg' => 'Lėčiausi segmentai',
    'speedChart' => 'Greičio diagrama',
    'moreStats' => 'Daugiau statistikos',
    'lines' => 'Eilučių',
    'applyFilter' => 'Išsaugoti filtrą',
    'timestamp' => 'Laiko žyma',
    'position' => 'Pozicija', //position in a replay
    'repHelp' => 'Pagalba', //link that shows information how to use the tool
    'repExport' => 'GIF arba video',
    
    /* PW change */
    'pwChange' => 'Keisti slaptažodį',
    'newPw' => 'Naujas slaptažodis',
    'applyChange' => 'Išsaugoti pakeitimus',
    'emailChange' => 'Keisti el. paštą',
    'currentEmail' => 'Dabartinis',
    'newEmail' => 'Naujas el. paštas',
    
    /* Localization settings */
    'localSettings' => 'Lokalizacijos nustatymai',
    'lang' => 'Kalba',
    'langNone' => 'Jokie',
    'langDesc' => 'Pasirinkite norima kalba.',
    'timezone' => 'Laiko zona',
    'timezoneDesc' => 'Naudojama konvertuoti laiką į jūsų lokalų laiką.',
    'country' => 'Šalis',
    'continent' => 'Kontinentas',
    'countryDesc' => 'Naudojama atskirų šalių lyderių lentelėje.',
    
    /* Profile */
    'ownProfile' => 'Jūsų viešas profilis prieinamas',
    'bestTimes' => 'Geriausi laikai',
    'allTimes' => 'Žiūrėti visus sprinto žaidimus',
    'userImpr' => 'Tobulėjimo statistika',
    'userRanking' => 'Rango statistika',
    'gameStats' => 'Žaidimo statistika',
    'latestGames' => 'Paskutiniai žaidimai',
    'noGames' => 'Šis žaidėjas dar nežaidė jokių žaidimų.',
    'gamesPlayed' => 'Žaidimai',
    'totalTime' => 'Bendras laikas',
    'placedBlocks' => 'Blokų padėta',
    'blockCnt' => ':cnt blokai',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Combo',
    'longestGame' => 'Ilgiausias žaidimas',
    'hours' => 'valandos',
    'minutes' => 'minutės',
    'playersCount' => 'Žaidėjai',
    'gameResultPosition' => 'Pozicija',
    'gameResultRoundTime' => 'Žaidimo laikas',
    'viewAllGamesOf' => 'Visi :mode žaidimai',
    'noGamesOf' => 'Žaidėjas :name nežaidė :mode žaidimų.',
    
    /* Maps */
    'mapCreate' => 'Sukurti naują',
    'mapName' => 'Pavadinimas',
    'mapNameLong' => 'Map Pavadinimas',
    'mapDesc' => 'Aprašymas',
    'mapRules' => 'Taisyklės',
    'mapOptions' => 'Nustatymai',
    'mapPlay' => 'Žaisti',
    'mapAuthor' => 'Autorius',
    'mapCreatedBy' => 'Sukurta',
    'search' => 'Ieškoti',
    'showRecords' => 'Rodyti rekordus',
    'details' => 'Detalės',
    'playedBy' => 'Žaista',

    /* Stats */
    'improvementStats' => 'Tobulėjimo statistika',
    //keep ':name'
    'date' => 'Data',
    'result' => 'Rezultatas',
    'submit' => 'Pateikti',
    'dispAll' => 'Rodyti visus žaidimus',
    
    /* About */
    'aboutInfo' => 'Jstris yra paprastas online multiplayer blokų žaidimas padarytas su Javascript, HTML5 ir Python (server).',
    'version' => 'Versija',
    'changelog' => 'Pakeitimai',
    'discussion' => 'Diskusija',
    'learnMore' => 'Sužinoti daugiau',
    'contact' => 'Kontaktai',
    'supporters' => 'Projekto remėjai',
    'translators' => 'Vertėjai',
    'moderators' => 'Moderatoriai',
    
    /* Other */
    'notFound' => 'Nerasta.',
    'brb' => 'Tuoj grįšiu.',
    'tryAgain' => 'Saitas yra atnaujinamas, bandykite vėliau.',

    /* Settings - Other options */
    'setOther' => 'Kiti nustatymai',
    'hideAcc' => 'Paslėpta paskyra',
    'accVisibility' => 'Matomumas',
    'hideAccInfo' => 'Jei įgalintas, paskyra bus neįtraukta į viešas lyderiu lenteles.',
    
    /* Friends */
    'accept' => 'Priimti',
    'ignore' => 'Ignoruoti',
    'pending' => 'Prašymas laukiamas peržiūros',
    'frFilter' => 'Filtruoti vardus',
    'noPending' => 'Šiuo metu jus neturite peržiūros laukiančiu užklausų.',
    'onlineNow' => 'Prisijungęs',
    'recentlyAc' => 'Neseniai prisijungęs',
    'lastActive' => 'Aktyvus prieš :when',
    'noFriends' => 'Šiuo metu jūsų draugų sąrašas yra tuščias.',
    'ruSure' => 'A tu tuom tikras?',
    'rmFriend' => 'A nuori išmest šį žmogą iš draugų?',
    'rmConfirm' => 'Tėp, išmesk',
    
    /* Settings - Navigation */
    'setProfileNav' => 'Profilis',
    'setLocalizationNav' => 'Lokalizacija',
    'setPasswordNav' => 'Slaptažodis',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => 'Kita',

    /* Settings - Discord */
    'setDiscordTitle' => 'Prijungti Discord',
    'disconnect' => 'Atjungti',
    'connectDiscord' => 'Prijungti Discord',

    /* Settings - Other */
    'setExperiments' => 'Eksperimentai',
    'setExperimentsDesc' => 'Įjungti bandomąją prieigą prie eksperimentinių/nebaigtų funkcijų',
    'setExperimentsNote' => 'Dalinkitės idėjomis apie testuotas funkcijas Jstris Discorde',
    'deleteAccount' => 'Ištrinti paskyrą',

    /* Settings - Supporter History */
    'returnBack' => 'Grįžti',
    'giftBalanceHistory' => 'Dovanų balanso istorija',
    'message' => 'Žinutė',
    'change' => 'Pakeitimas',
    'before' => 'Prieš',
    'after' => 'Po',
    'relative' => 'Santykinis',
    'none' => 'Nėra',

    /* Settings - Supporter Status */
    'subscription' => 'Prenumerata',
    'active' => 'aktyvi',
    'manage' => 'Tvarkyti',
    'renewsOn' => 'Atnaujinama:',
    'oneTime' => 'Vienkartinė',
    'expires' => 'Baigiasi',
    'extend' => 'Pratęsti',
    'giftingBalance' => 'Dovanų balansas',
    'days' => 'dienos',
    'add' => 'Pridėti',
    'useCode' => 'Naudoti kodą',
    'balanceHistory' => 'Balanso istorija',
    'noExpiration' => 'Be galiojimo',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'Įkelti pasirinktinį paveikslėlį',
    'uploadCustomImageDesc' => 'Pasirinkite paveikslėlį viešam profilio vaizdui Jstryje. Gali būti pašalintas, jei pranešta kaip netinkamas.',
    'supporterOption' => 'Supporter parinktis',
    'seeDetails' => 'Žiūrėti detales',
    'uploadPreviewCrop' => 'Įkelti peržiūrai ir apkirpti',

    /* Settings - Profile */
    'remove' => 'Pašalinti',
    'noImageSelected' => 'Dar nepasirinktas joks paveikslėlis',
    'bioPlaceholder' => 'Įveskite žinutę, kuri bus rodoma jūsų profilyje',
    'bioFormatInfo' => 'Nuorodas galima formatuoti taip: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Supporter paskyros gali naudoti formatavimą, įterpti nuorodas ir emotikonus',
    'selectProfileImage' => 'Pasirinkite profilio paveikslėlį',
    'jstrisBlocks' => 'Jstris blokai',
    'animalArt' => 'Gyvūnų menas',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris be reklamų ir nemokamas. Remdami galite atrakinti šiuos privalumus:',
    'benefitProfileCustomizations' => 'Profilio pritaikymai',
    'benefitProfileCustomizationsDesc' => 'Galite įkelti pasirinktinį profilio paveikslėlį ir naudoti išplėstinį formatavimą skiltyje „Apie“ (iki 2000 simbolių, nuorodos ir emotikonai).',
    'benefitSaveMatchesBots' => 'Išsaugoti žaidimus prieš botus',
    'benefitSaveMatchesBotsDesc' => 'Jūsų 1v1 prieš botus bus išsaugoti rezultatuose, įskaitant pakartojimus ir statistiką.',
    'benefitUnlimitedReplays' => 'Neriboti pakartojimai',
    'benefitUnlimitedReplaysDesc' => 'Kol Supporter aktyvus, vieno žaidėjo režimų pakartojimai nebus trinami.',
    'getSupporterCta' => 'Gauti Jstris Supporter!',
    'configureBenefits' => 'Konfigūruoti privalumus',
    'nameChange' => 'Vardo keitimas',
    'nameChangeInfo' => 'Kaip Supporter, kartą per mėnesį galite pakeisti vardą. Pakeiskite čia:',
    'newNameLabel' => 'Naujas vardas',
    'newNamePlaceholder' => 'Įveskite naują naudotojo vardą',
    'manageSubscriptionTitle' => 'Tvarkyti Jstris prenumeratą',
    'manageSubscriptionInfo1' => 'Norėdami sustabdyti ar atšaukti, prisijunkite prie PayPal ir pasirinkite parinktį prenumeratos skydelyje.',
    'manageSubscriptionInfo2' => 'Iškilus problemoms, rašykite jstris@jezevec10.com.',
    'close' => 'Uždaryti',
];
