<?php

return [
    'leaderboard' => 'Pistetaulukko',
    'tournament' => 'Turnaus',
    'maps' => 'Kartat',
    'mapsBrowse' => 'Selaa',
    'myMaps' => 'Minun kartat',
    'mapsDesigner' => 'Karttaeditori',
    'randomMap' => 'Satunnainen kartta',
    'mapsLatestGames' => 'Viimeisimmät pelit',
    'guide' => 'Ohje',
    'login' => 'Kirjaudu',
    'register' => 'Rekisteröi',
    'myProfile' => 'Minun profiili',
    'myImprovement' => 'Edistykseni',
    'favReplays' => 'Suosikkitoistot',
    'settings' => 'Asetukset',
    'logout' => 'Kirjaudu ulos',
    
    /* Leaderboard */
    'name' => 'Nimi',
    'time' => 'Aika',
    'blocks' => 'Palikat',
    'PPS' => 'PPS',
    'finesse' => 'Taidokkuus',
    'date' => 'Päiväys',
    'replay' => 'Toisto',
    'place' => 'Sijoitus',
    'nli' => 'Ei kirjautuneena sisään!',
    'today' => 'Tänään',
    'lastWeek' => 'Viime viikko',
    'lastMonth' => 'Viime kuukausi',
    'lastYear' => 'Viime vuosi',
    'allTime' => 'Koskaan',
    'bestPlayers' => 'Parhaat pelaajat',
    'bestGames' => 'Parhaat pelit',
    'bestSubs' => 'Parhaat alle',
    'latestGames' => 'Viimeisimmät pelit',
    'leastBlocks' => 'Vähiten palikoita',
    'myTimes' => 'Minun aikani',
    'perfectFinesse' => 'Täydellinen taidokkuus',
    
    /* Replay */
    'load' => 'Lataa',
    'play' => 'Toista',
    'pause' => 'Tauko',
    'showSeg' => 'Näytä osat',
    'fastestSeg' => 'Nopeimmat osat',
    'slowestSeg' => 'Hitaimmat osat',
    'speedChart' => 'Nopeuskaavio',
    'moreStats' => 'Enemmän tilastoja',
    'lines' => 'Rivit',
    'scoringPlaylist' => 'Pisteiden soittolista',
    'filterSP' => 'Suodata pisteiden soittolista',
    'applyFilter' => 'Ota suodatin käyttöön',
    'timestamp' => 'Aikaleima',
    'action' => 'Toiminta', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Vastaavat pisteet',
    'position' => 'Sijainti', //position in a replay
    'lAVG' => 'Lokaali keskiarvo',
    'gAVG' => 'Globaali keskiarvo',
    'repHelp' => 'Apua', //link that shows information how to use the tool
    'repExport' => 'GIF tai video',
    
    /* PW change */
    'pwChange' => 'Vaihda salasana',
    'newPw' => 'Uusi salasana',
    'againPw' => 'Uudelleen',
    'applyChange' => 'Ota muutokset käyttöön',
    'emailChange' => 'Vaihda sähköpostiosoite',
    'currentEmail' => 'Nykyinen',
    'newEmail' => 'Uusi sähköpostiosoite',
    
    /* Localization settings */
    'localSettings' => 'Lokalisaation asetukset',
    'lang' => 'Kieli',
    'langNone' => 'Ei ole (valittavissa ylävalikosta)',
    'langDesc' => 'Valitse haluamasi kieli.',
    'timezone' => 'Aikavyöhyke',
    'timezoneDesc' => 'Käytetään ajan muuntamisessa paikalliseen aikaasi.',
    'country' => 'Maa',
    'continent' => 'Maanosa',
    'countryDesc' => 'Käytetään maankohtaisten pistetaulukoiden näyttämiseen.',
    
    /* Profile */
    'ownProfile' => 'Tämä on julkinen profiilisi, mihin pääsee',
    'bestTimes' => 'Parhaat ajat',
    'allTimes' => 'Näytä kaikki sprinttiajat',
    'userImpr' => 'Näytä edistymistilastot',
    'gameStats' => 'Pelitilastot',
    'latestGames' => 'Viimeisimmät pelit',
    'noGames' => 'Tämä käyttäjä ei ole pelannut yhtään peliä vielä.',
    'gamesPlayed' => 'Pelit',
    'totalTime' => 'Kokonaisaika',
    'linesSent' => 'Lähetetyt rivit',
    'linesRec' => 'Vastaanotetut rivit',
    'placedBlocks' => 'Asetetut palikat',
    'blockCnt' => ':cnt palikkaa',
    'APM10Games' => '10 pelin APM',
    'PPS10Games' => '10 pelin PPS',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Kombo',
    'longestGame' => 'Pisin peli',
    'totalB2B' => 'B2B:t yhteensä',
    'mostSent' => 'Eniten lähetetty',
    'hours' => 'tuntia',
    'minutes' => 'minuuttia',
    'createdMaps' => 'Luodut kartat',
    'viewMapsBy' => 'Näytä kaikki kartat tekijältä',
    'playersCount' => 'Pelaajat',
    'gameResultPosition' => 'Sijoitus',
    'gameResultRoundTime' => 'Peliaika',
    'viewAllGamesOf' => 'Näytä kaikki :mode-pelit',
    'noGamesOf' => ':name ei ole pelannut yhtään :mode-peliä vielä.',
    
    /* Maps */
    'map' => 'Kartta',
    'mapCreate' => 'Luo uusi',
    'mapName' => 'Nimi',
    'mapNameLong' => 'Kartan nimi',
    'mapDesc' => 'Kuvaus',
    'mapRules' => 'Säännöt',
    'mapOptions' => 'Asetukset',
    'mapPlay' => 'Pelaa',
    'mapPlayLink' => 'Pelaa Karttaa',
    'mapAuthor' => 'Tekijä',
    'mapCreatedBy' => 'Kartan teki',
    'backToMaps' => 'Takaisin karttoihin',
    'playThisMap' => 'Pelaa tätä karttaa',
    'search' => 'Hae',
    'myMaps' => 'Minun karttani',
    'mapsByUser' => ':name:n kartat',
    'displayUnpublished' => 'Näytä :cnt julkaisematonta karttaa',
    'displayPublished' => 'Näytä :cnt julkaistua karttaa',
    'usersMapMedals' => ':name:n karttamitalit',
    'usersCompletedMaps' => ':name: suoritetut kartat',
    'showRecords' => 'Näytä ennätykset',
    'details' => 'Yksityiskohdat',
    'playedBy' => 'Pelannut',
    'latestMapGames' => 'Viimeisimmät karttapelit',

    /* Stats */
    'improvementStats' => 'Edistymisen tilastot',
    //keep ':name'
    'improvementInfo' => 'Seuraava kaavio näyttää rivikisan ajan (Y-akseli) vs pelin päiväyksen (X-akseli). Korostettu viiva näyttää :name:n edistymisen omissa ennätyksissä. Voit asettaa kursorisi mihin pisteelle tahansa nähdäksesi pelin yksityiskohdat.',
    'date' => 'Päiväys',
    'result' => 'Tulos',
    'submit' => 'Lähetä',
    'qSettings' => 'Tiedustelun asetukset',
    'dispAll' => 'Näytä kaikki pelit',
    
    /* About */
    'aboutInfo' => 'Jstris on yksinkertainen verkkomoninpeli rakennettu Javascriptillä, HTML5:llä ja Pythonilla (palvelin).',
    'version' => 'Versio',
    'changelog' => 'Muutosloki',
    'discussion' => 'Keskustelu',
    'learnMore' => 'Lue lisää',
    'contact' => 'Ota yhteyttä',
    'serverCoverage' => 'Palvelimen kustannusten kattavuus',
    'supporters' => 'Projektin tukijat',
    'translators' => 'Kääntäjät',
    'moderators' => 'Valvojat',
    
    /* Other */
    'notFound' => 'Ei löydy.',
    'invalidLink' => 'Pyydetty linkki on kelvoton.',
    'brb' => 'Palataan pian.',
    'tryAgain' => 'Sivua päivitetään, yritä uudelleen hetken kuluttua.',

    /* Settings - Other options */
    'setOther' => 'Muut asetukset',
    'hideAcc' => 'Piilotettu tili',
    'accVisibility' => 'Näkyvyys',
    'hideAccInfo' => 'Jos päällä, tiliä ei näytetä julkisilla pistetaulukoilla.',

    /* Chat reports */
    'reportU' => 'Ilmoita käyttäjästä',
    'reportDesc' => 'Täältä voit ilmoittaa, jos joku on mielestäsi väärinkäyttänyt pelin chattiä.',
    'user' => 'Käyttäjä',
    'reason' => 'Syy',
    'rr0' => 'Roskapostia tai epätoivottua mainostusta',
    'rr1' => 'Seksuaalista sisältöä',
    'rr2' => 'Vihapuhetta',
    'rr3' => 'Häirintä tai kiusaaminen',
    'rr4' => 'Muu (täsmennä)',
    'sendReport' => 'Lähetä ilmoitus',

    /* Settings - Navigation */
    'setProfileNav' => 'Profiili',
    'setLocalizationNav' => 'Lokalisaatio',
    'setPasswordNav' => 'Salasana',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => 'Muut',

    /* Settings - Discord */
    'setDiscordTitle' => 'Yhdistä Discord',
    'disconnect' => 'Katkaise',
    'connectDiscord' => 'Yhdistä Discord',

    /* Settings - Other */
    'setExperiments' => 'Kokeilut',
    'setExperimentsDesc' => 'Ota käyttöön testipääsy kokeellisiin/keskeneräisiin ominaisuuksiin',
    'setExperimentsNote' => 'Jaa ideasi testatuista ominaisuuksista Jstris Discordissa',
    'deleteAccount' => 'Poista tili',

    /* Settings - Supporter History */
    'returnBack' => 'Palaa',
    'giftBalanceHistory' => 'Lahjasaldon historia',
    'message' => 'Viesti',
    'change' => 'Muutos',
    'before' => 'Ennen',
    'after' => 'Jälkeen',
    'relative' => 'Suhteellinen',
    'none' => 'Ei mitään',

    /* Settings - Supporter Status */
    'subscription' => 'Tilaus',
    'active' => 'aktiivinen',
    'manage' => 'Hallinnoi',
    'renewsOn' => 'Uusii:',
    'oneTime' => 'Kertaluonteinen',
    'expires' => 'Vanhenee',
    'extend' => 'Pidennä',
    'giftingBalance' => 'Lahjasaldo',
    'days' => 'päivää',
    'add' => 'Lisää',
    'useCode' => 'Käytä koodia',
    'balanceHistory' => 'Saldon historia',
    'noExpiration' => 'Ei vanhene',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'Lataa oma kuva',
    'uploadCustomImageDesc' => 'Valitse kuva julkiseksi profiilikuvaksi Jstrisiin. Kuva voidaan poistaa, jos se ilmoitetaan asiattomaksi.',
    'supporterOption' => 'Supporter-vaihtoehto',
    'seeDetails' => 'Katso tiedot',
    'uploadPreviewCrop' => 'Lataa esikatselua ja rajausta varten',

    /* Settings - Profile */
    'remove' => 'Poista',
    'noImageSelected' => 'Kuvaa ei ole vielä valittu',
    'bioPlaceholder' => 'Kirjoita viesti, joka näkyy profiilissasi',
    'bioFormatInfo' => 'Voit muotoilla linkit näin: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Supporter-tilit voivat käyttää muotoiluja, lisätä linkkejä ja emojeja',
    'selectProfileImage' => 'Valitse profiilikuva',
    'jstrisBlocks' => 'Jstris-palikat',
    'animalArt' => 'Eläintaide',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris on ilmainen ja mainokseton. Tukemalla saat käyttöösi seuraavat edut:',
    'benefitProfileCustomizations' => 'Profiilin muokkaukset',
    'benefitProfileCustomizationsDesc' => 'Voit ladata oman profiilikuvan ja käyttää laajennettua muotoilua "Tietoja"-viestissä (jopa 2000 merkkiä, linkit ja emotet).',
    'benefitSaveMatchesBots' => 'Tallenna pelit botteja vastaan',
    'benefitSaveMatchesBotsDesc' => '1v1 botteja vastaan tallentuu tuloksiin, mukaan lukien uusinnat ja tilastot.',
    'benefitUnlimitedReplays' => 'Rajattomat uusinnat',
    'benefitUnlimitedReplaysDesc' => 'Yksinpelitilojen uusintoja ei poisteta Supporter-jäsenyyden aikana.',
    'getSupporterCta' => 'Hanki Jstris Supporter!',
    'configureBenefits' => 'Määritä edut',
    'nameChange' => 'Nimen vaihto',
    'nameChangeInfo' => 'Supporterina voit vaihtaa nimesi kerran kuukaudessa. Vaihda nimi täällä:',
    'newNameLabel' => 'Uusi nimi',
    'newNamePlaceholder' => 'Anna uusi käyttäjänimi',
    'manageSubscriptionTitle' => 'Hallitse Jstris-tilausta',
    'manageSubscriptionInfo1' => 'Keskeyttääksesi tai peruuttaaksesi tilauksen, kirjaudu PayPaliin ja valitse vaihtoehto tilaushallinnassa.',
    'manageSubscriptionInfo2' => 'Ongelmatilanteissa: jstris@jezevec10.com.',
    'close' => 'Sulje',
];
