<?php

return [
    'leaderboard' => 'Πίνακας βαθμολογίας',
    'tournament' => 'Τουρνουά',
    'maps' => 'Χάρτες',
    'mapsBrowse' => 'Περιήγηση',
    'myMaps' => 'Οι χάρτες μου',
    'mapsDesigner' => 'Σχεδιαστής χαρτών',
    'randomMap' => 'Τυχαίος χάρτης',
    'mapsLatestGames' => 'Τελευταία παιχνίδια',
    'guide' => 'Οδηγός',
    'login' => 'Σύνδεση',
    'register' => 'Εγγραφή',
    'myProfile' => 'Το προφίλ μου',
    'myImprovement' => 'Η βελτίωσή μου',
    'favReplays' => 'Αγαπημένες επαναλήψεις',
    'friends' => 'Φίλοι',
    'settings' => 'Ρυθμίσεις',
    'logout' => 'Αποσύνδεση',
    
    /* Leaderboard */
    'name' => 'Όνομα',
    'time' => 'Χρόνος',
    'blocks' => 'μπλόκ',
    'PPS' => 'ΚΑΔ',
    'finesse' => 'Φινέτσα',
    'date' => 'Ημερομηνία',
    'replay' => 'Επανάληψη',
    'place' => 'Θέση',
    'nli' => 'Δεν έχετε συνδεθεί!',
    'today' => 'Σήμερα',
    'lastWeek' => 'Την προηγούμενη εβδομάδα',
    'lastMonth' => 'Τον τελευταίο μήνα',
    'lastYear' => 'Πέρυσι',
    'allTime' => 'Όλα',
    'bestPlayers' => 'Καλύτεροι παίκτες',
    'bestGames' => 'Καλύτερα Παιχνίδια',
    'bestSubs' => 'Καλύτερα υπό',
    'latestGames' => 'Τελευταία παιχνίδια',
    'leastBlocks' => 'Τα λιγότερα μπλοκς',
    'myTimes' => 'Οι χρόνοι μου',
    'perfectFinesse' => '0 φινέτσα',
    
    /* Replay */
    'load' => 'Φόρτωση',
    'play' => 'Παίξε',
    'pause' => 'Παύση',
    'showSeg' => 'Εμφάνιση τμημάτων',
    'fastestSeg' => 'Ταχύτερα τμήματα',
    'slowestSeg' => 'Αργότερα τμήματα',
    'speedChart' => 'Διάγραμμα ταχύτητας',
    'moreStats' => 'Περισσότερα στατιστικά',
    'lines' => 'Γραμμές',
    'scoringPlaylist' => 'Βαθμολογίκή λίστα',
    'filterSP' => 'Φίλτρα βαθμολογικής λίστας',
    'applyFilter' => 'Εφαρμόστε φίλτρο',
    'timestamp' => 'Χρονική σήμανση',
    'action' => 'Ενέργεια', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Ισοδύναμο σκορ',
    'position' => 'Θέση', //position in a replay
    'lAVG' => 'Τοπικός μέσος όρος',
    'gAVG' => 'Παγκόσμιος μέσος όρος',
    'repHelp' => 'Βοήθεια', //link that shows information how to use the tool
    'repExport' => 'GIF ή βίντεο',
    
    /* PW change */
    'pwChange' => 'Αλλαγή κωδικού',
    'newPw' => 'Νέος Κωδικός',
    'againPw' => 'Επανάληψη',
    'applyChange' => 'Εφαρμογή αλλαγής',
    'emailChange' => 'Αλλαγή email',
    'currentEmail' => 'Τρέχον',
    'newEmail' => 'Νέο email',
    
    /* Localization settings */
    'localSettings' => 'Ρυθμίσεις τοπικής προσαρμογής',
    'lang' => 'Γλώσσα',
    'langNone' => 'Κανένα (επιλέξιμο στο επάνω μενού)',
    'langDesc' => 'Επιλέξτε την προτιμώμενη γλώσσα.',
    'timezone' => 'Ζώνη ώρας',
    'timezoneDesc' => 'Χρησιμοποιείται για τη μετατροπή της ώρας στην τοπική ώρα.',
    'country' => 'Χώρα',
    'continent' => 'Ήπειρος',
    'countryDesc' => 'Χρησιμοποιείται για την εμφάνιση πινάκων ηγετών ανά χώρα.',
    
    /* Profile */
    'ownProfile' => 'Αυτό είναι το δημόσιο προφίλ σας προσβάσιμο στη διεύθυνση',
    'bestTimes' => 'Καλύτεροι χρόνοι',
    'allTimes' => 'Προβολή όλων των χρόνων σπριντ',
    'userImpr' => 'Στατιστικά βελτίωσης',
    'userRanking' => 'Στατιστικά κατάταξης',
    'gameStats' => 'Στατιστικά παιχνιδιών',
    'latestGames' => 'Τελευταία παιχνίδια',
    'noGames' => 'Αυτός ο χρήστης δεν έχει παίξει ακόμα παιχνίδια.',
    'gamesPlayed' => 'Παιχνίδια',
    'totalTime' => 'Συνολικός χρόνος',
    'linesSent' => 'Απεσταλμένες γραμμές',
    'linesRec' => 'Ληφθείσες γραμμές',
    'placedBlocks' => 'Τοποθετημένα μπλοκ',
    'blockCnt' => ':cnt μπλοκς',
    'APM10Games' => '10-παιχνίδια ΠΑΛ',
    'PPS10Games' => '10-παιχνίδια ΚΑΔ',
    'maxAPM' => 'Μέγιστο APM',
    'maxREN' => 'Μέγιστο Κόμμπο',
    'longestGame' => 'Το μεγαλύτερο παιχνίδι',
    'totalB2B' => 'Συνολικά B2Bs',
    'mostSent' => 'Τα περισσότερα που στάλθηκαν',
    'hours' => 'ώρες',
    'minutes' => 'λεπτά',
    'createdMaps' => 'Χάρτες που Δημιουργήθηκαν',
    'viewMapsBy' => 'Δείτε όλους τους χάρτες που δημιουργήθηκαν από τον/ην',
    'playersCount' => 'Παίκτες',
    'gameResultPosition' => 'Θέση',
    'gameResultRoundTime' => 'Χρόνος παιχνιδιού',
    'viewAllGamesOf' => 'Όλα τα παιχνίδια του :mode',
    'noGamesOf' => ':name δεν έχει παίξει παιχνίδια απο :mode ακόμη.',
    
    /* Maps */
    'map' => 'Χάρτης',
    'mapCreate' => 'Δημιουργία νέου',
    'mapName' => 'Όνομα',
    'mapNameLong' => 'Όνομα Χάρτη',
    'mapDesc' => 'Περιγραφή',
    'mapRules' => 'Κανόνες',
    'mapOptions' => 'Ρυθμίσεις',
    'mapPlay' => 'Παίξε',
    'mapPlayLink' => 'Παίξε στον Χάρτη',
    'mapAuthor' => 'Συγγραφέας',
    'mapCreatedBy' => 'Δημιουργήθηκε απο',
    'backToMaps' => 'Πίσω στους χάρτες',
    'playThisMap' => 'Παίξε σε αυτόν τον χάρτη',
    'search' => 'Ανζήτηση',
    'myMaps' => 'Οι χάρτες μου',
    'mapsByUser' => ':name\'s χάρτες',
    'displayUnpublished' => 'Απεικόνιση :cnt αδημοσίευτων χαρτών',
    'displayPublished' => 'Απεικόνιση :cnt δημοσιευμένων χαρτών',
    'usersMapMedals' => ':name\'s μετάλλια χάρτη',
    'usersCompletedMaps' => ':name\'s ολοκληρωμένοι χάρτες',
    'showRecords' => 'Εμφάνιση ρεκόρ',
    'details' => 'Λεπτομέριες',
    'playedBy' => 'Παίχτηκε από',
    'latestMapGames' => 'Τα τελευταία παιχνίδια χαρτών',

    /* Stats */
    'improvementStats' => 'Στατιστικά βελτίωσης',
    //keep ':name'
    'improvementInfo' => 'Το ακόλουθο γράφημα δείχνει τον χρόνο του αγώνα γραμμών (Y άξονας) vs ημερομηνία παιχνιδιού (X άξονας). Η υπογραμμισμένη γραμμή δείχνει βελτιώσεις στα :name\'s προσωπικά ρεκόρ. Μπορείς να τοποθετήσεις τον κέρσορα σου πανώ απο οποιδήποτε σημείο για να εμφανιστούν πληροφορίες.',
    'date' => 'Ημερομηνία',
    'result' => 'Αποτέλεσμα',
    'submit' => 'Υποβολή',
    'qSettings' => 'Ρυθμίσεις ερωτήματος',
    'dispAll' => 'Εμφάνιση όλων των παιχνιδιών',
    
    /* About */
    'aboutInfo' => 'Το Jstris είναι ένα απλό διαδυκτιακό παιχνίδι, πολλαπλών παικτών, με μπλοκς που έχει αναπτυχθεί σε Javascript, HTML5 και Python (διακομιστής).',
    'version' => 'Έκδοση',
    'changelog' => 'Αλλαγή αρχείου καταγραφής',
    'discussion' => 'Συζήτηση',
    'learnMore' => 'Μάθε Περισσότερα',
    'contact' => 'Επικοινωνία',
    'serverCoverage' => 'Κάλυψη κόστους διακομιστή',
    'supporters' => 'Υποστηρικτές του έργου',
    'translators' => 'Μεταφραστές',
    'moderators' => 'Συντονιστές',
    
    /* Other */
    'notFound' => 'Δεν βρέθηκε.',
    'invalidLink' => 'Ο σύνδεσμος που ζητήθηκε δεν είναι έγκυρος.',
    'brb' => 'Επιστρέφω αμέσως.',
    'tryAgain' => 'Ο ιστότοπος ενημερώνεται. Δοκιμάστε ξανά σε λίγα λεπτά.',
    'wasteDesc' => 'Αναλογία κομματιών T που δεν χρησιμοποιούνται σε T-Spin (προς συνολικά κομμάτια T)',

    /* Settings - Other options */
    'setOther' => 'Αλλες επιλογές',
    'hideAcc' => 'Κρυμμένος λογαριασμός',
    'accVisibility' => 'Ορατότητα',
    'hideAccInfo' => 'Εάν ενεργοποιηθεί, ο λογαριασμός θα εξαιρείται από τους δημόσιους πίνακες βαθμολογίας.',

    /* Chat reports */
    'reportU' => 'Αναφορά χρήστη',
    'reportDesc' => 'Εδώ μπορείτε να δημιουργήσετε μια αναφορά εάν πιστεύετε ότι κάποιος έχει κάνει κατάχρηση της συνομιλίας παιχνιδιών.',
    'user' => 'Χρήστης',
    'reason' => 'Λόγος',
    'rr0' => 'Σπάμ ή ανεπιθύμητη διαφήμιση',
    'rr1' => 'Σεξουαλικό άσεμνο περιεχόμενο',
    'rr2' => 'Εχθρικός λόγος',
    'rr3' => 'Παρενόχληση ή εκφοβισμός',
    'rr4' => 'Άλλο (προσδιορίστε)',
    'sendReport' => 'Αποστολή αναφοράς',
    
    /* Friends */
    'accept' => 'Αποδοχή',
    'ignore' => 'Αγνόηση',
    'pending' => 'Εκκρεμείς αιτήσεις',
    'frFilter' => 'Φίλτραρισμα ονομάτων',
    'noPending' => 'Προς το παρόν δεν έχετε εκκρεμή αιτήματα φίλων.',
    'onlineNow' => 'Συνδεδεμένος τώρα',
    'recentlyAc' => 'Πρόσφατα ενεργός',
    'lastActive' => 'Ενεργός :when',
    'noFriends' => 'Προς το παρόν, η λίστα φίλων σας είναι κενή.',
    'ruSure' => 'Είσαι σίγουρος;',
    'rmFriend' => 'Θέλετε να καταργήσετε αυτό το άτομο από τη λίστα φίλων σας;',
    'rmConfirm' => 'Ναι, κατάργηση',
    
    /* Settings - Navigation */
    'setProfileNav' => 'Προφίλ',
    'setLocalizationNav' => 'Τοπικοποίηση',
    'setPasswordNav' => 'Κωδικός',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => 'Άλλα',

    /* Settings - Discord */
    'setDiscordTitle' => 'Σύνδεση με Discord',
    'disconnect' => 'Αποσύνδεση',
    'connectDiscord' => 'Σύνδεση Discord',

    /* Settings - Other */
    'setExperiments' => 'Πειράματα',
    'setExperimentsDesc' => 'Ενεργοποίηση δοκιμαστικής πρόσβασης σε πειραματικές/ημιτελείς λειτουργίες',
    'setExperimentsNote' => 'Μοιραστείτε ιδέες για τις δοκιμασμένες λειτουργίες στο Jstris Discord',
    'deleteAccount' => 'Διαγραφή λογαριασμού',

    /* Settings - Supporter History */
    'returnBack' => 'Επιστροφή',
    'giftBalanceHistory' => 'Ιστορικό υπολοίπου δώρων',
    'message' => 'Μήνυμα',
    'change' => 'Αλλαγή',
    'before' => 'Πριν',
    'after' => 'Μετά',
    'relative' => 'Σχετικό',
    'none' => 'Κανένα',

    /* Settings - Supporter Status */
    'subscription' => 'Συνδρομή',
    'active' => 'ενεργό',
    'manage' => 'Διαχείριση',
    'renewsOn' => 'Ανανεώνεται στις:',
    'oneTime' => 'Μία φορά',
    'expires' => 'Λήγει',
    'extend' => 'Παράταση',
    'giftingBalance' => 'Υπόλοιπο δώρων',
    'days' => 'ημέρες',
    'add' => 'Προσθήκη',
    'useCode' => 'Χρήση κωδικού',
    'balanceHistory' => 'Ιστορικό υπολοίπου',
    'noExpiration' => 'Χωρίς λήξη',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'Μεταφόρτωση προσαρμοσμένης εικόνας',
    'uploadCustomImageDesc' => 'Επιλέξτε εικόνα ως δημόσια εικόνα προφίλ στο Jstris. Μπορεί να αφαιρεθεί εάν αναφερθεί ως απρεπής.',
    'supporterOption' => 'Επιλογή Supporter',
    'seeDetails' => 'Δείτε λεπτομέρειες',
    'uploadPreviewCrop' => 'Μεταφόρτωση για προεπισκόπηση & περικοπή',

    /* Settings - Profile */
    'remove' => 'Αφαίρεση',
    'noImageSelected' => 'Δεν έχει επιλεγεί εικόνα ακόμα',
    'bioPlaceholder' => 'Εισάγετε μήνυμα που θα εμφανίζεται στο προφίλ σας',
    'bioFormatInfo' => 'Μπορείτε να μορφοποιήσετε συνδέσμους έτσι: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Οι Supporter λογαριασμοί μπορούν να χρησιμοποιούν μορφοποίηση, να εισάγουν συνδέσμους και emotes',
    'selectProfileImage' => 'Επιλέξτε εικόνα προφίλ',
    'jstrisBlocks' => 'Jstris μπλοκς',
    'animalArt' => 'Καλλιτεχνία ζώων',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Το Jstris είναι χωρίς διαφημίσεις και δωρεάν. Με την υποστήριξή σας ξεκλειδώνετε τα ακόλουθα οφέλη:',
    'benefitProfileCustomizations' => 'Προσαρμογές προφίλ',
    'benefitProfileCustomizationsDesc' => 'Μπορείτε να ανεβάσετε προσαρμοσμένη εικόνα προφίλ και να χρησιμοποιήσετε εκτεταμένη μορφοποίηση στο "Σχετικά" (έως 2000 χαρακτήρες, σύνδεσμοι και emotes).',
    'benefitSaveMatchesBots' => 'Αποθήκευση παιχνιδιών με bots',
    'benefitSaveMatchesBotsDesc' => 'Τα 1v1 με bots αποθηκεύονται στα αποτελέσματα συμπεριλαμβανομένων replays και στατιστικών.',
    'benefitUnlimitedReplays' => 'Απεριόριστα replays',
    'benefitUnlimitedReplaysDesc' => 'Κανένα replay από singleplayer δεν διαγράφεται όσο είστε Supporter.',
    'getSupporterCta' => 'Αποκτήστε Jstris Supporter!',
    'configureBenefits' => 'Ρύθμιση οφελών',
    'nameChange' => 'Αλλαγή ονόματος',
    'nameChangeInfo' => 'Ως Supporter, μπορείτε να αλλάξετε όνομα μία φορά το μήνα. Αλλάξτε το εδώ:',
    'newNameLabel' => 'Νέο όνομα',
    'newNamePlaceholder' => 'Εισάγετε νέο όνομα χρήστη',
    'manageSubscriptionTitle' => 'Διαχείριση συνδρομής Jstris',
    'manageSubscriptionInfo1' => 'Για παύση ή ακύρωση, συνδεθείτε στο PayPal και επιλέξτε την επιλογή στο ταμπλό συνδρομής.',
    'manageSubscriptionInfo2' => 'Για προβλήματα: jstris@jezevec10.com.',
    'close' => 'Κλείσιμο',
];
