<?php
return [
    'leaderboard' => 'Leaderboard',
    'tournament' => 'Comórtas',
    'login' => 'Logáil isteach',
    'register' => 'Clárú',
    'myProfile' => 'mo phróifíl',
    'myImprovement' => 'Mo fheabhsú',
    'settings' => 'Socruithe',
    'logout' => 'Logáil Amach',
    
    /* Leaderboard */
    'name' => 'Ainm',
    'time' => 'Am',
    'blocks' => 'Bloic',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Dáta',
    'replay' => 'Athsheoladh',
    'place' => 'Áit',
    'nli' => 'Gan logáil isteach!',
    'today' => 'Inniu',
    'lastWeek' => 'An tseachtain seo caite',
    'lastMonth' => 'An mhí seo caite',
    'lastYear' => 'Anuraidh',
    'allTime' => 'Riamh',
    'bestPlayers' => 'Na himreoirí is fearr',
    'bestGames' => 'Cluichí is fearr',
    'bestSubs' => 'An chuid is fearr',
    'latestGames' => 'Cluichí is déanaí',
    'leastBlocks' => 'Na bloic is lú',
    'myTimes' => 'Mo chuid ama',
    
    /* Replay */
    'load' => 'Luchtaigh',
    'play' => 'Imirt',
    'pause' => 'Sos',
    'showSeg' => 'Taispeáin deighleoga',
    'fastestSeg' => 'Is tapúla daighleoga',
    'slowestSeg' => 'Níos moille daighleoga',
    'speedChart' => 'Cairt luas',
    'moreStats' => 'Tuilleadh stats',
    
    /* PW change */
    'pwChange' => 'Athraigh do phasfhocal',
    'newPw' => 'Focal Faire Nua',
    'againPw' => 'Arís',
    'applyChange' => 'Cuir iarratas ar athrú',
    'emailChange' => 'Athraigh ríomhphost',
    'currentEmail' => 'Reatha',
    'newEmail' => 'Ríomhphost nua',
    
    /* Profile */
    'ownProfile' => 'Seo do phróifíl phoiblí atá inrochtana ag',
    'bestTimes' => 'Amanna is Fearr',
    'allTimes' => 'Féach ar gach uair sprint',
    'userImpr' => 'Féach stats feabhsaithe',
    'gameStats' => 'Stats cluiche',
    'latestGames' => 'Cluichí is déanaí',
    'noGames' => 'Níl cluichí ar bith fós ag an úsáideoir seo.',
    'gamesPlayed' => 'Cluichí',
    'totalTime' => 'Am iomlán',
    'linesSent' => 'Na línte a seoladh',
    'linesRec' => 'Línte a fuarthas',
    'placedBlocks' => 'Bloic curtha sios',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Combo',
    'longestGame' => 'Cluiche is faide',
    'totalB2B' => 'Iomlán B2Bs',
    'mostSent' => 'An chuid is mó a sheoladh',
    'hours' => 'Uair',
    'minutes' => 'Nóiméad',
    
    /* Stats */
    'improvementStats' => 'Improvement stats',
    //keep ':name'
    'improvementInfo' => 'The following graph shows line race time (Y axis) vs game date (X axis). Highlighted line shows improvements in :name\'s personal records. You can place your cursor over any point to show the game details.',
    'date' => 'Date',
    'result' => 'Result',
    'submit' => 'Submit',
    'qSettings' => 'Query settings',
    'dispAll' => 'Display all games',
    
    /* About */
    'aboutInfo' => 'Jstris is a simple online multiplayer block game built in Javascript, HTML5 and Python (server).',
    'version' => 'Leagan',
    'discussion' => 'Plé',
    'learnMore' => 'foghlaim níos mó',
    'contact' => 'Déan teagmháil',
    'serverCoverage' => 'Server Clúdach costas (Jstris)',
    'supporters' => 'Tacaitheoirí tionscadail',
    
    /* Other */
    'notFound' => 'Ní bhfuarthas',
    'invalidLink' => 'Tá nasc iarrtha neamhbhailí.',
    'brb' => 'A bheith ceart ar ais',
    'tryAgain' => 'Tá an suíomh á nuashonrú, déan iarracht arís i gceann cúpla nóiméad.',
];
