<?php

return [
    'leaderboard' => 'Ranglista',
    'tournament' => 'Bajnokság',
    'maps' => 'Pályák',
    'mapsBrowse' => 'Böngészés',
    'myMaps' => 'Pályáim',
    'mapsDesigner' => 'Pályakészítő',
    'randomMap' => 'Véletlenszerű pálya',
    'mapsLatestGames' => 'Legfrissebb játékok',
    'guide' => 'Útmutató',
    'login' => 'Bejelentkezés',
    'register' => 'Regisztráció',
    'myProfile' => 'Profilom',
    'myImprovement' => 'Saját fejlődésem',
    'favReplays' => 'Kedvenc visszajátszások',
    'friends' => 'Barátok',
    'settings' => 'Beállítások',
    'logout' => 'Kijelentkezés',

    /* Leaderboard */
    'name' => 'Név',
    'time' => 'Idő',
    'blocks' => 'Elemek',
    'PPS' => 'PPS',
    'finesse' => 'Lépéshiba',
    'date' => 'Dátum',
    'replay' => 'Visszajátszás',
    'place' => 'Helyezés',
    'nli' => 'Nem vagy bejelentkezve!',
    'today' => 'Ma',
    'lastWeek' => 'Múlt hét',
    'lastMonth' => 'Az elmúlt hónap',
    'lastYear' => 'Az elmúlt év',
    'allTime' => 'Összesen',
    'bestPlayers' => 'Legjobb játékosok',
    'bestGames' => 'Legjobb játékok',
    'bestSubs' => 'Részidők',
    'latestGames' => 'Legutolsó játékok',
    'leastBlocks' => 'A legkevesebb elem',
    'myTimes' => 'Saját idő',
    'perfectFinesse' => '0 lépéshiba',

    /* Replay */
    'load' => 'Betöltés',
    'play' => 'Lejátszás',
    'pause' => 'Szünet',
    'showSeg' => 'Szegmensek megjelenítése',
    'fastestSeg' => 'Leggyorsabb szegmensek',
    'slowestSeg' => 'Leglassabb szegmensek',
    'speedChart' => 'Sebességgrafikon',
    'moreStats' => 'További statisztikák',
    'lines' => 'Sorok',
    'scoringPlaylist' => 'Pontozási lista',
    'filterSP' => 'Pontozási lista szűrése',
    'applyFilter' => 'Szűrő alkalmazása',
    'timestamp' => 'Időbélyeg',
    'action' => 'Akció', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Pontérték megfelelője',
    'position' => 'Helyzet', //position in a replay
    'lAVG' => 'Aktuális átlag',
    'gAVG' => 'Globális átlag',
    'repHelp' => 'Segítség', //link that shows information how to use the tool
    'repExport' => 'GIF vagy videó',

    /* PW change */
    'pwChange' => 'Jelszó módosítás',
    'newPw' => 'Új jelszó',
    'againPw' => 'Új jelszó ismét',
    'applyChange' => 'Alkalmazás',

    /* Localization settings */
    'localSettings' => 'Lokalizációs beállítások',
    'lang' => 'Nyelv',
    'langNone' => 'Nincs (a felső menüben válaszható)',
    'langDesc' => 'Válassza ki a kívánt nyelvet.',
    'timezone' => 'Időzóna',
    'timezoneDesc' => 'Az idő helyi időre való átváltására szolgál.',
    'country' => 'Ország',
    'continent' => 'Kontinens',
    'countryDesc' => 'Országonkénti ranglisták megjelenítésére szolgál.',

    /* Profile */
    'ownProfile' => 'This is your public profile accessible at',
    'bestTimes' => 'Legjobb eredménye(i)',
    'allTimes' => 'Összes sprintidő megtekintése',
    'userImpr' => 'Fejlődés megtekintése',
    'userRanking' => 'Rang megtekintése',
    'gameStats' => 'Statisztika',
    'latestGames' => 'Legújabb játékai',
    'noGames' => 'Ez a felhasználó még nem játszott semmilyen játékot.',
    'gamesPlayed' => 'Játékok',
    'totalTime' => 'Összes játékidő',
    'linesSent' => 'Küldött sorok',
    'linesRec' => 'Kapott sorok',
    'placedBlocks' => 'Elhelyezett elemek',
    'blockCnt' => ':cnt elemek',
    'APM10Games' => 'Legutolsó 10-játék APM',
    'PPS10Games' => 'Legutolsó 10-játék PPS',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Kombó',
    'longestGame' => 'Leghosszabb játék',
    'totalB2B' => 'Összes B2B',
    'mostSent' => 'Legtöbb elküldött',
    'hours' => 'óra',
    'minutes' => 'perc',
    'createdMaps' => 'Készített pályák',
    'viewMapsBy' => 'Létrehozott pályák megtekintése',
    'playersCount' => 'Játékosok száma',
    'gameResultPosition' => 'Pozíció',
    'gameResultRoundTime' => 'Játékidő',
    'viewAllGamesOf' => 'A :mode összes játékának megtekintése',
    'noGamesOf' => ':name még nem játszott egyetlen :mode játékot sem.',

    /* Maps */
    'map' => 'Pálya',
    'mapCreate' => 'Új létrehozása',
    'mapName' => 'Név',
    'mapNameLong' => 'Pálya neve',
    'mapDesc' => 'Leírás',
    'mapRules' => 'Szabályok',
    'mapOptions' => 'Opciók',
    'mapPlay' => 'Játék',
    'mapPlayLink' => 'Pálya elindítása',
    'mapAuthor' => 'Készítő',
    'mapCreatedBy' => 'Készítette:',
    'backToMaps' => 'Vissza a pályákhoz',
    'playThisMap' => 'Pálya elindítása',
    'search' => 'Keresés',
    'myMaps' => 'Saját pályáim',
    'mapsByUser' => ':name Pályái',
    'displayUnpublished' => 'A közzé nem tett :cnt pálya megjelenítése',
    'displayPublished' => 'A közzé tett :cnt pálya megjelenítése ',
    'usersMapMedals' => ':name Pálya érmei',
    'usersCompletedMaps' => ':name befejezett Pályái',
    'showRecords' => 'Legjobb eredmények megjelenítése',
    'details' => 'Részletek',
    'playedBy' => 'Játszotta:',
    'latestMapGames' => 'A legújabb Pálya játékok',

    /* Stats */
    'improvementStats' => 'Fejlődési statisztika',
    //keep ':name'
    'improvementInfo' => 'A következő grafikon a sprint játékmód idejét (Y tengely) és a játék dátumát mutatja (X tengely).  A kiemelt vonal :name egyéni rekordjainak javulását mutatja. A kurzort bármely pont fölé helyezve megjelenítheti a játék részleteit.',
    'date' => 'Dátum',
    'result' => 'Eredmény',
    'submit' => 'Lekérdezés',
    'qSettings' => 'Lekérdezési beállítások',
    'dispAll' => 'Minden játék megjelenítése',

    /* About */
    'aboutInfo' => 'A Jstris egy egyszerű online többjátékos blokkjáték, amely Javascriptben, HTML5-ben és Pythonban (szerver) készült.',
    'version' => 'Verzió',
    'changelog' => 'Changelog',
    'discussion' => 'Közösség',
    'learnMore' => 'További információk',
    'contact' => 'Kapcsolatfelvétel',
    'serverCoverage' => 'Szerver költségfedezete',
    'supporters' => 'A projekt támogatói',
    'translators' => 'Fordítók',
    'moderators' => 'Moderátorok',

    /* Other */
    'notFound' => 'Nem található.',
    'invalidLink' => 'A kért link érvénytelen.',
    'brb' => 'Hamarosan visszajövünk.',
    'tryAgain' => 'Az oldal frissítése folyamatban van, kérjük, próbáld meg újra néhány perc múlva.',
    'wasteDesc' => 'A T-Spinhez fel nem használt T-elemek aránya (az összes T-elemhez viszonyítva)',

    /* Settings - Other options */
    'setOther' => 'Egyéb beállítások',
    'hideAcc' => 'Rejtett felhasználó',
    'accVisibility' => 'Láthatóság',
    'hideAccInfo' => 'Ha engedélyezve van, a fiókot kizárjuk a nyilvános ranglistákból.',

    /* Chat reports */
    'reportU' => 'Felhasználó jelentése',
    'reportDesc' => 'Itt tudsz jelentést tenni, ha úgy gondolod, hogy valaki visszaélt a játék chatj funkciójával.',
    'user' => 'Felhasználó',
    'reason' => 'Indok',
    'rr0' => 'Spam vagy nem kívánt reklám',
    'rr1' => 'Szexuális tartalom',
    'rr2' => 'Gyűlöletbeszéd',
    'rr3' => 'Zaklatás vagy bullying',
    'rr4' => 'Egyéb (kérem részletezd)',
    'sendReport' => 'Jelentés küldése',

    /* Friends */
    'accept' => 'Visszaigazolás',
    'ignore' => 'Figyelmen kívül hagyás',
    'pending' => 'Függő kérelmek',
    'frFilter' => 'Nevek szűrése',
    'noPending' => 'Jelenleg nincsenek függőben lévő baráti kéréseid.',
    'onlineNow' => 'Most online',
    'recentlyAc' => 'Nemrégiben aktív',
    'lastActive' => 'Atív :when',
    'noFriends' => 'Jelenleg a barátlistád üres.',
    'ruSure' => 'Biztos vagy benne?',
    'rmFriend' => 'Szeretnéd törölni ezt a személyt a barátlistádról?',
    'rmConfirm' => 'Igen, eltávolítom',
];
