<?php

return [
    'leaderboard' => 'Bảng xếp hạng',
    'tournament' => 'Giải đấu',
    'maps' => 'Map',
    'mapsBrowse' => 'Tìm kiếm Map',
    'myMaps' => 'Map của tôi',
    'mapsDesigner' => 'Tạo map',
    'randomMap' => 'Map ngẫu nhiên',
    'mapsLatestGames' => 'Những ván map mới chơi',
    'guide' => 'Hướng dẫn',
    'login' => 'Đăng nhập',
    'register' => 'Đăng kí',
    'myProfile' => 'Trang cá nhân',
    'myImprovement' => 'Độ tiến triển',
    'favReplays' => 'Replay ưa thích',
    'settings' => 'Cài đặt',
    'logout' => 'Đăng xuất',
    
    /* Leaderboard */
    'name' => 'Tên',
    'time' => 'Thời gian',
    'blocks' => 'Số gạch',
    'PPS' => 'PPS',
    'finesse' => 'Lỗi di chuyển',
    'date' => 'Thời điểm hoàn thành',
    'replay' => 'Replay',
    'place' => 'Địa điểm',
    'nli' => 'Chưa đăng nhập',
    'today' => 'Hôm nay',
    'lastWeek' => 'Tuần trước',
    'lastMonth' => 'Tháng trước',
    'lastYear' => 'Năm trước',
    'allTime' => 'Tất cả',
    'bestPlayers' => 'Theo người chơi',
    'bestGames' => 'Game tốt nhất',
    'bestSubs' => 'Đạt mốc ngắn nhất',
    'latestGames' => 'Game mới nhất',
    'leastBlocks' => 'Ít gạch nhất',
    'myTimes' => 'Thời gian của tôi',
    'perfectFinesse' => '0 lỗi di chuyển',
    
    /* Replay */
    'load' => 'Tải',
    'play' => 'Phát',
    'pause' => 'Ngừng',
    'showSeg' => 'Xem phân khúc',
    'fastestSeg' => 'Phân khúc nhanh nhất',
    'slowestSeg' => 'Phân khúc chậm nhất',
    'speedChart' => 'Biểu đồ tốc độ',
    'moreStats' => 'Thêm chi tiết',
    'lines' => 'Hàng',
    'scoringPlaylist' => 'Danh sách ghi điểm',
    'filterSP' => 'Lọc danh sách điểm',
    'applyFilter' => 'Áp dụng bộ lọc',
    'timestamp' => 'Thởi điểm',
    'action' => 'Kiểu loại hàng', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Điểm tương ứng',
    'position' => 'Thời điểm hiện tại', //position in a replay
    'lAVG' => 'Trung bình nội địa',
    'gAVG' => 'Trung bình quốc tế',
    'repHelp' => 'Help', //link that shows information how to use the tool
    
    /* PW change */
    'pwChange' => 'Đổi mật khẩu',
    'newPw' => 'Mật khẩu mới',
    'againPw' => 'Nhập lại',
    'applyChange' => 'Áp dụng thay đổi',
    
    /* Localization settings */
    'localSettings' => 'Cài đặt ngôn ngữ và quốc gia',
    'lang' => 'Ngôn ngữ game',
    'langNone' => 'Không có gì (Có thể chọn được trong menu trên cùng)',
    'langDesc' => 'Lựa chọn ngôn ngữ ưa thích.',
    'timezone' => 'Múi giờ',
    'timezoneDesc' => 'Dùng để chuyển đổi sang thời gian nội của múi giờ được chọn.',
    'country' => 'Quốc gia',
    'countryDesc' => 'Dùng để xem bảng xếp hạng của quốc gia.',
    
    /* Profile */
    'ownProfile' => 'Đây là nơi mà bạn có thể thấy thông tin công khai của mình',
    'bestTimes' => 'Thời gian tốt nhất',
    'allTimes' => 'Xem tất cả thời gian Sprint',
    'userImpr' => 'Xem thông tin về tiến triển',
    'gameStats' => 'Thông tin game',
    'latestGames' => 'Game mới nhất',
    'noGames' => 'Người dùng này chưa chơi game nào.',
    'gamesPlayed' => 'Game',
    'totalTime' => 'Tổng thời gian',
    'linesSent' => 'Hàng đã gửi',
    'linesRec' => 'Hàng đã nhận',
    'placedBlocks' => 'Số gạch đã đặt',
    'maxAPM' => 'APM cao nhất',
    'maxREN' => 'Combo cao nhất',
    'longestGame' => 'Game dài nhất',
    'totalB2B' => 'Tổng B2Bs',
    'mostSent' => 'Gửi nhiều nhất',
    'hours' => 'tiếng',
    'minutes' => 'phút',
    
    /* Stats */
    'improvementStats' => 'Thông tin tiến triển',
    //keep ':name'
    'improvementInfo' => 'Biểu đồ này cho thấy thời gian Sprint (trục Y) với thời điểm game (trục X). Dòng nổi bật cho thấy những tiến triển của :name. Bạn có thể đặt chuột qua bất kì điểm nào để xem thông tin của game đó.',
    'date' => 'Thời điểm',
    'result' => 'Kết quả',
    'submit' => 'Tải lên',
    'qSettings' => 'Cài đặt biểu đồ',
    'dispAll' => 'Hiển thị tất cả',
    
    /* About */
    'aboutInfo' => 'Jstris là game xếp gạch đơn giản được lập trình trên Javascript, HTML5 và Python (máy chủ).',
    'version' => 'Phiên bản',
    'changelog' => 'Các thay đổi',
    'discussion' => 'Bàn luận thêm',
    'learnMore' => 'Thêm chi tiết',
    'contact' => 'Liên hệ',
    'serverCoverage' => 'Tiền chi trên máy chủ',
    'supporters' => 'Những người ủng hộ',
    
    /* Other */
    'notFound' => 'Không thấy.',
    'invalidLink' => 'Link được yêu cầu không phù hợp.',
    'brb' => 'Sẽ quay lại ngay.',
    'tryAgain' => 'Trang web đang được bảo trì, vui lòng thử lại trong một lát.',
];
