<?php

return [
    'leaderboard' => 'Bảng xếp hạng',
    'tournament' => 'Giải đấu',
    'maps' => 'Map',
    'mapsBrowse' => 'Tìm kiếm Map',
    'myMaps' => 'Map của tôi',
    'mapsDesigner' => 'Tạo map',
    'randomMap' => 'Map ngẫu nhiên',
    'mapsLatestGames' => 'Những ván map mới chơi',
    'guide' => 'Hướng dẫn',
    'login' => 'Đăng nhập',
    'register' => 'Đăng kí',
    'myProfile' => 'Trang cá nhân',
    'myImprovement' => 'Độ tiến triển',
    'favReplays' => 'Replay ưa thích',
    'settings' => 'Cài đặt',
    'logout' => 'Đăng xuất',
    
    /* Leaderboard */
    'name' => 'Tên',
    'time' => 'Thời gian',
    'blocks' => 'Số gạch',
    'PPS' => 'PPS',
    'finesse' => 'Lỗi di chuyển',
    'date' => 'Thời điểm hoàn thành',
    'replay' => 'Replay',
    'place' => 'Địa điểm',
    'nli' => 'Chưa đăng nhập',
    'today' => 'Hôm nay',
    'lastWeek' => 'Tuần trước',
    'lastMonth' => 'Tháng trước',
    'lastYear' => 'Năm trước',
    'allTime' => 'Tất cả',
    'bestPlayers' => 'Theo người chơi',
    'bestGames' => 'Game tốt nhất',
    'bestSubs' => 'Mốc thời gian',
    'latestGames' => 'Game mới nhất',
    'leastBlocks' => 'Ít gạch nhất',
    'myTimes' => 'Thời gian của tôi',
    'perfectFinesse' => '0 lỗi di chuyển',
    
    /* Replay */
    'load' => 'Tải',
    'play' => 'Phát',
    'pause' => 'Ngừng',
    'showSeg' => 'Xem phân khúc',
    'fastestSeg' => 'Phân khúc nhanh nhất',
    'slowestSeg' => 'Phân khúc chậm nhất',
    'speedChart' => 'Biểu đồ tốc độ',
    'moreStats' => 'Thêm chi tiết',
    'lines' => 'Hàng',
    'scoringPlaylist' => 'Danh sách ghi điểm',
    'filterSP' => 'Lọc danh sách điểm',
    'applyFilter' => 'Áp dụng bộ lọc',
    'timestamp' => 'Thởi điểm',
    'action' => 'Kiểu lấp hàng', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Điểm tương ứng',
    'position' => 'Thời điểm hiện tại', //position in a replay
    'lAVG' => 'Trung bình nội địa',
    'gAVG' => 'Trung bình quốc tế',
    'repHelp' => 'Help', //link that shows information how to use the tool
    
    /* PW change */
    'pwChange' => 'Đổi mật khẩu',
    'newPw' => 'Mật khẩu mới',
    'againPw' => 'Nhập lại',
    'applyChange' => 'Áp dụng thay đổi',
    
    /* Localization settings */
    'localSettings' => 'Cài đặt ngôn ngữ và quốc gia',
    'lang' => 'Ngôn ngữ game',
    'langNone' => 'Không có gì (Có thể chọn được trong menu trên cùng)',
    'langDesc' => 'Lựa chọn ngôn ngữ ưa thích.',
    'timezone' => 'Múi giờ',
    'timezoneDesc' => 'Dùng để chuyển đổi sang thời gian nội của múi giờ được chọn.',
    'country' => 'Quốc gia',
    'countryDesc' => 'Dùng để xem bảng xếp hạng của quốc gia.',
    
    /* Profile */
    'ownProfile' => 'Đây là nơi mà bạn có thể thấy thông tin công khai của mình',
    'bestTimes' => 'Thời gian tốt nhất',
    'allTimes' => 'Xem tất cả thời gian Sprint',
    'userImpr' => 'Xem thông tin về tiến triển',
    'gameStats' => 'Thông tin game',
    'latestGames' => 'Game mới nhất',
    'noGames' => 'Người dùng này chưa chơi game nào.',
    'gamesPlayed' => 'Game',
    'totalTime' => 'Tổng thời gian',
    'linesSent' => 'Hàng đã gửi',
    'linesRec' => 'Hàng đã nhận',
    'placedBlocks' => 'Số gạch đã đặt',
    'maxAPM' => 'APM cao nhất',
    'maxREN' => 'Combo cao nhất',
    'longestGame' => 'Game dài nhất',
    'totalB2B' => 'Tổng B2Bs',
    'mostSent' => 'Gửi nhiều nhất',
    'hours' => 'tiếng',
    'minutes' => 'phút',
    
    /* Stats */
    'improvementStats' => 'Thông tin tiến triển',
    //keep ':name'
    'improvementInfo' => 'Biểu đồ này cho thấy thời gian Sprint (trục Y) với thời điểm game (trục X). Dòng nổi bật cho thấy những tiến triển của :name. Bạn có thể đặt chuột qua bất kì điểm nào để xem thông tin của game đó.',
    'date' => 'Thời điểm',
    'result' => 'Kết quả',
    'submit' => 'Tải lên',
    'qSettings' => 'Cài đặt biểu đồ',
    'dispAll' => 'Hiển thị tất cả',
    
    /* About */
    'aboutInfo' => 'Jstris là game xếp gạch đơn giản được lập trình trên Javascript, HTML5 và Python (máy chủ).',
    'version' => 'Phiên bản',
    'changelog' => 'Các thay đổi',
    'discussion' => 'Bàn luận thêm',
    'learnMore' => 'Thêm chi tiết',
    'contact' => 'Liên hệ',
    'serverCoverage' => 'Tiền chi trên máy chủ',
    'supporters' => 'Những người ủng hộ',
    
    /* Other */
    'notFound' => 'Không thấy.',
    'invalidLink' => 'Link được yêu cầu không phù hợp.',
    'brb' => 'Sẽ quay lại ngay.',
    'tryAgain' => 'Trang web đang được bảo trì, vui lòng thử lại trong một lát.',
    
    'repExport' => 'GIF hoặc video',
    'continent' => 'Lục địa',
    'blockCnt' => ':cnt gạch',
    'APM10Games' => 'Trung bình APM trong 10 game',
    'PPS10Games' => 'Trong bình PPS trong 10 game',
    'createdMaps' => 'Map đã tạo',
    'viewMapsBy' => 'Xem tất cả map của',
    'playersCount' => 'Số người chơi',
    'gameResultPosition' => 'Hạng',
    'gameResultRoundTime' => 'Thời gian chơi',
    'viewAllGamesOf' => 'Xem tất cả game của chế độ :mode',
    'noGamesOf' => ':name chưa chơi chế độ :mode .',
    'map' => 'Map',
    'mapCreate' => 'Tạo mới',
    'mapName' => 'Tên',
    'mapNameLong' => 'Tên map',
    'mapDesc' => 'Mô tả',
    'mapRules' => 'Luật',
    'mapOptions' => 'Cài đặt',
    'mapPlay' => 'Chơi',
    'mapPlayLink' => 'Chơi map này',
    'mapAuthor' => 'Người tạo',
    'mapCreatedBy' => 'Được tạo bởi',
    'backToMaps' => 'Quay lại tìm kiếm',
    'playThisMap' => 'Play this map',
    'search' => 'Tìm kiếm',
    'mapsByUser' => 'Map của :name',
    'displayUnpublished' => 'Xem :cnt map chưa được công bố',
    'displayPublished' => 'Xem :cnt map đã được công bố',
    'usersMapMedals' => 'Huy chương của :name',
    'usersCompletedMaps' => 'Map hoàn thành bởi :name',
    'showRecords' => 'Xem kết quả',
    'details' => 'Thông tin chi tiết',
    'playedBy' => 'Hoàn thành bởi',
    'latestMapGames' => 'Những map mới chơi nhất',
    'translators' => 'Người dịch',
    'moderators' => 'Người điều hành',
    'setOther' => 'Tùy chọn khác', 
    'hideAcc' => 'Ẩn tài khoản', 
    'accVisibility' => 'Hiển thị', 
    'hideAccInfo' => 'Nếu bật, tài khoản này sẽ không được liệt kê vào bảng xếp hạng công khai',
    'friends' => 'Bạn bè',
    'mostGames' => 'Nhiều ván nhất',
    'userRanking' => 'Thống kê xếp hạng',
    'wasteDesc' => 'Tỉ lệ khối chữ T không được sử dụng trong T-spin (chia cho tổng số khối chữ T)',
    'reportU' => 'Tố cáo người chơi',
    'reportDesc' => 'Ở đây bạn có thể tạo đơn tố cáo nếu bạn nghĩ ai đó đang quấy rối ở khu vực chat.',
    'user' => 'Người chơi',
    'reason' => 'Lý do',
    'rr0' => 'Spam hoặc quảng cáo không mong muốn',
    'rr1' => 'Nội dung khiêu dâm',
    'rr2' => 'Ngôn từ gây thù ghét',
    'rr3' => 'Quấy rối hoặc bắt nạt',
    'rr4' => 'Vấn đề khác (nêu rõ)',
    'sendReport' => 'Gửi đơn tố cáo',
    'accept' => 'Chấp nhận',
    'ignore' => 'Từ chối',
    'pending' => 'Yêu cầu đang chờ xử lý',
    'frFilter' => 'Lọc tên',
    'noPending' => 'Bạn đang không có lời mời kết bạn đang chờ nào cả.',
    'onlineNow' => 'Đang trực tuyến',
    'recentlyAc' => 'Mới hoạt động',
    'lastActive' => 'Hoạt động cuối :when',
    'noFriends' => 'Danh sách bạn bè của bạn hiện tại đang trống.',
    'ruSure' => 'Bạn chắc chắn chứ?',
    'rmFriend' => 'Bạn có muốn bỏ người này khỏi danh sách bạn bè của bạn?',
    'rmConfirm' => 'Có, tôi muốn bỏ',
];
