<?php

return [
    'leaderboard' => 'Таблиця лідерів',
    'tournament' => 'Турнір',
    'maps' => 'Карти',
    'mapsBrowse' => 'Огляд',
    'myMaps' => 'Мої карти',
    'mapsDesigner' => 'Дизайнер карт',
    'randomMap' => 'Випадкова карта',
    'mapsLatestGames' => 'Останні ігри',
    'guide' => 'Посібник',
    'login' => 'Увійти',
    'register' => 'Зареєструватися',
    'myProfile' => 'Мій профіль',
    'myImprovement' => 'Мої покращення',
    'favReplays' => 'Улюблені повтори',
    'friends' => 'Друзі',
    'settings' => 'Налаштування',
    'logout' => 'Вийти',
    
    /* Leaderboard */
    'name' => 'Ім’я',
    'time' => 'Час',
    'blocks' => 'Фігури',
    'PPS' => 'PPS',
    'finesse' => 'Техніка',
    'date' => 'Дата',
    'replay' => 'Повтор',
    'place' => 'Місце',
    'nli' => 'Ви не авторизовані!',
    'today' => 'Сьогодні',
    'lastWeek' => 'Минулого тижня',
    'lastMonth' => 'Минулого місяця',
    'lastYear' => 'Минулого року',
    'allTime' => 'За весь час',
    'bestPlayers' => 'Кращі гравці',
    'bestGames' => 'Найкращі ігри',
    'bestSubs' => 'Кращі ігри',
    'latestGames' => 'Останні ігри',
    'leastBlocks' => 'За меншу кількість фігур',
    'myTimes' => 'Мої рекорди',
    'perfectFinesse' => 'Без помилок',
    
    /* Replay */
    'load' => 'Загрузити',
    'play' => 'Продовжити',
    'pause' => 'Пауза',
    'showSeg' => 'Показати сегменти',
    'fastestSeg' => 'Найшвидші сегменти',
    'slowestSeg' => 'Найповільніші сегменти',
    'speedChart' => 'Графік швидкості',
    'moreStats' => 'Більше статистики',
    'lines' => 'Лінії',
    'scoringPlaylist' => 'Звіт очок',
    'filterSP' => 'Фільтрувати звіт очок',
    'applyFilter' => 'Застосувати фільтр',
    'timestamp' => 'Час',
    'action' => 'Дія', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Очки',
    'position' => 'Позиція', //position in a replay
    'lAVG' => 'Локальне середнє значення',
    'gAVG' => 'Глобальне середнє значення',
    'repHelp' => 'Допомога', //link that shows information how to use the tool
    'repExport' => 'GIF або відео',
    
    /* PW change */
    'pwChange' => 'Змінити пароль',
    'newPw' => 'Новий пароль',
    'againPw' => 'Знову',
    'applyChange' => 'Застосувати зміни',
    'emailChange' => 'Змінити електронну пошту',
    'currentEmail' => 'Поточна',
    'newEmail' => 'Нова електронна пошта',
    
    /* Localization settings */
    'localSettings' => 'Параметри локалізації',
    'lang' => 'Мова',
    'langNone' => 'За замовчуванням (можна вибрати в верхньому меню)',
    'langDesc' => 'Виберіть бажану мову.',
    'timezone' => 'Часовий пояс',
    'timezoneDesc' => 'Використовується для перетворення часу в ваш місцевий час.',
    'country' => 'Країна',
    'continent' => 'Континент',
    'countryDesc' => 'Використовується для фільтрації рекордів за країною.',
    
    /* Profile */
    'ownProfile' => 'Це ваш публічний профіль доступний за',
    'bestTimes' => 'Найкращий час',
    'allTimes' => 'Переглянути всі рекорди спринту',
    'userImpr' => 'Статистика покращення',
    'userRanking' => 'Рейтинг рекордів',
    'gameStats' => 'Статистика гри',
    'latestGames' => 'Останні ігри',
    'noGames' => 'Цей користувач ще не брав участі в іграх.',
    'gamesPlayed' => 'Ігри',
    'totalTime' => 'Проведений час',
    'linesSent' => 'Ліній відправлено',
    'linesRec' => 'Ліній отримано',
    'placedBlocks' => 'Поставлено фігур',
    'blockCnt' => ':cnt фігур',
    'APM10Games' => '10 ігор APM',
    'PPS10Games' => '10 ігор PPS',
    'maxAPM' => 'Макс. APM',
    'maxREN' => 'Макс. Комбо',
    'longestGame' => 'Найдовша гра',
    'totalB2B' => 'Всього B2B',
    'mostSent' => 'Часто надіслані',
    'hours' => 'годин',
    'minutes' => 'хвилин',
    'createdMaps' => 'Створені карти',
    'viewMapsBy' => 'Переглянути всі створені карти',
    'playersCount' => 'Гравці',
    'gameResultPosition' => 'Місце',
    'gameResultRoundTime' => 'Час гри',
    'viewAllGamesOf' => 'Всі ігри у :mode',
    'noGamesOf' => ':name ще не грав у :mode.',
    
    /* Maps */
    'map' => 'Карта',
    'mapCreate' => 'Створити нову',
    'mapName' => 'Назва',
    'mapNameLong' => 'Назва карти',
    'mapDesc' => 'Опис',
    'mapRules' => 'Правила',
    'mapOptions' => 'Параметри',
    'mapPlay' => 'Грати',
    'mapPlayLink' => 'Грати карту',
    'mapAuthor' => 'Автор',
    'mapCreatedBy' => 'Створено',
    'backToMaps' => 'Назад до карт',
    'playThisMap' => 'Грати цю карту',
    'search' => 'Пошук',
    'myMaps' => 'Мої карти',
    'mapsByUser' => 'Карти від :name',
    'displayUnpublished' => 'Відобразити :cnt неопублікованих карт',
    'displayPublished' => 'Відобразити :cnt опубліковані карти',
    'usersMapMedals' => ':name медалі за карти',
    'usersCompletedMaps' => ':name завершені карти',
    'showRecords' => 'Показати рекорди',
    'details' => 'Подробиці',
    'playedBy' => 'Зіграно',
    'latestMapGames' => 'Останні зіграні карти',

    /* Stats */
    'improvementStats' => 'Статистика покращення',
    //keep ':name'
    'improvementInfo' => 'Цей графік показує рекорди спринтів по осі Y та дати цих рекордів по осі X. Виділена лінія показує покращення в рекордах :name. Наведіть курсор на будь-яке місце, щоб переглянути більше.',
    'date' => 'Дата',
    'result' => 'Результат',
    'submit' => 'Підтвердити',
    'qSettings' => 'Налаштування запиту',
    'dispAll' => 'Показати всі ігри',
    
    /* About */
    'aboutInfo' => 'Jstris це проста багатокористувацька онлайн гра, побудована на Javascript, HTML5 і Python (сервер).',
    'version' => 'Версія',
    'changelog' => 'Список змін',
    'discussion' => 'Обговорення',
    'learnMore' => 'Дізнатися більше',
    'contact' => 'Контакт',
    'serverCoverage' => 'Покриття вартості сервера',
    'supporters' => 'Підтримувачі проєкту',
    'translators' => 'Перекладачі',
    'moderators' => 'Модератори',
    
    /* Other */
    'notFound' => 'Не знайдено.',
    'invalidLink' => 'Запитане посилання недійсне.',
    'brb' => 'Тимчасово недоступний.',
    'tryAgain' => 'Сайт оновлюється, зайдіть пізніше.',
    'wasteDesc' => 'Співвідношення кількості Т-Фігур, не використаних у Т-Поворотах, до загальної кількості Т-Фігур',

    /* Settings - Other options */
    'setOther' => 'Інші варіанти',
    'hideAcc' => 'Приховати акаунт',
    'accVisibility' => 'Видимість',
    'hideAccInfo' => 'Якщо цей параметр увімкнено, обліковий запис буде виключено з публічної таблиці лідерів.',

    /* Chat reports */
    'reportU' => 'Поскаржитися на користувача',
    'reportDesc' => 'Ви можете надіслати скаргу, якщо хтось зловживає чатом.',
    'user' => 'Користувач',
    'reason' => 'Причина',
    'rr0' => 'Спам або небажана реклама',
    'rr1' => 'Вміст сексуального характеру',
    'rr2' => 'Вороже ставлення',
    'rr3' => 'Домагання чи знущання',
    'rr4' => 'Інше (вкажіть)',
    'sendReport' => 'Надіслати',
    
    /* Friends */
    'accept' => 'Прийняти',
    'ignore' => 'Ігнорувати',
    'pending' => 'Запити в очікування',
    'frFilter' => 'Фільтрувати за іменем',
    'noPending' => 'У Вас немає запитів у друзі.',
    'onlineNow' => 'Зараз у мережі',
    'recentlyAc' => 'Нещодавно активні',
    'lastActive' => 'Був у мережі :when',
    'noFriends' => 'Ваш список друзів порожній.',
    'ruSure' => 'Ви впевнені?',
    'rmFriend' => 'Ви хочете видалити цього гравця зі списку друзів?',
    'rmConfirm' => 'Так, видалити',
    
    /* Settings - Navigation */
    'setProfileNav' => 'Профіль',
    'setLocalizationNav' => 'Локалізація',
    'setPasswordNav' => 'Пароль',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => 'Інше',

    /* Settings - Discord */
    'setDiscordTitle' => 'Підключити Discord',
    'disconnect' => 'Від’єднати',
    'connectDiscord' => 'Підключити Discord',

    /* Settings - Other */
    'setExperiments' => 'Експерименти',
    'setExperimentsDesc' => 'Увімкнути тестовий доступ до експериментальних/незавершених функцій',
    'setExperimentsNote' => 'Діліться ідеями щодо протестованих функцій у Discord Jstris',
    'deleteAccount' => 'Видалити акаунт',

    /* Settings - Supporter History */
    'returnBack' => 'Повернутися',
    'giftBalanceHistory' => 'Історія подарункового балансу',
    'message' => 'Повідомлення',
    'change' => 'Зміна',
    'before' => 'До',
    'after' => 'Після',
    'relative' => 'Відносно',
    'none' => 'Немає',

    /* Settings - Supporter Status */
    'subscription' => 'Підписка',
    'active' => 'активна',
    'manage' => 'Керувати',
    'renewsOn' => 'Поновлюється:',
    'oneTime' => 'Одноразова',
    'expires' => 'Завершується',
    'extend' => 'Продовжити',
    'giftingBalance' => 'Подарунковий баланс',
    'days' => 'днів',
    'add' => 'Додати',
    'useCode' => 'Ввести код',
    'balanceHistory' => 'Історія балансу',
    'noExpiration' => 'Без строку дії',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'Завантажити власне зображення',
    'uploadCustomImageDesc' => 'Виберіть зображення для публічного аватара у Jstris. Може бути видалено, якщо буде поскаржено як неприпустиме.',
    'supporterOption' => 'Опція Supporter',
    'seeDetails' => 'Переглянути деталі',
    'uploadPreviewCrop' => 'Завантажити для попереднього перегляду та обрізання',

    /* Settings - Profile */
    'remove' => 'Вилучити',
    'noImageSelected' => 'Зображення ще не вибрано',
    'bioPlaceholder' => 'Введіть повідомлення, що з’явиться у вашому профілі',
    'bioFormatInfo' => 'Можна форматувати посилання так: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Акаунти Supporter можуть використовувати форматування, вставляти посилання та емодзі',
    'selectProfileImage' => 'Виберіть зображення профілю',
    'jstrisBlocks' => 'Блоки Jstris',
    'animalArt' => 'Тваринний арт',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris без реклами та безкоштовний для всіх. Підтримуючи, ви відкриваєте такі переваги:',
    'benefitProfileCustomizations' => 'Налаштування профілю',
    'benefitProfileCustomizationsDesc' => 'Можна завантажити власне фото профілю та використовувати розширене форматування в «Про мене» (до 2000 символів, посилання та емодзі).',
    'benefitSaveMatchesBots' => 'Збереження ігор проти ботів',
    'benefitSaveMatchesBotsDesc' => 'Ваші 1v1 проти ботів зберігатимуться в результатах, включно з повторами та статистикою.',
    'benefitUnlimitedReplays' => 'Необмежені реплеї',
    'benefitUnlimitedReplaysDesc' => 'Жоден реплей з одиночних режимів не буде видалено, доки Supporter активний.',
    'getSupporterCta' => 'Отримати Jstris Supporter!',
    'configureBenefits' => 'Налаштувати переваги',
    'nameChange' => 'Зміна імені',
    'nameChangeInfo' => 'Як Supporter, ви можете змінювати ім’я раз на місяць. Змініть тут:',
    'newNameLabel' => 'Нове ім’я',
    'newNamePlaceholder' => 'Введіть нове ім’я користувача',
    'manageSubscriptionTitle' => 'Керування підпискою Jstris',
    'manageSubscriptionInfo1' => 'Щоб призупинити або скасувати, увійдіть у PayPal і виберіть потрібну опцію на панелі підписки.',
    'manageSubscriptionInfo2' => 'У разі проблем: jstris@jezevec10.com.',
    'close' => 'Закрити',
];
