<?php

return [
    'leaderboard' => 'Таблиця лідерів',
    'tournament' => 'Турнір',
    'maps' => 'Карти',
    'mapsBrowse' => 'Огляд',
    'myMaps' => 'Мої карти',
    'mapsDesigner' => 'Дизайнер карт',
    'randomMap' => 'Випадкова карта',
    'mapsLatestGames' => 'Останні ігри',
    'guide' => 'Посібник',
    'login' => 'Увійти',
    'register' => 'Зареєструватися',
    'myProfile' => 'Мій профіль',
    'myImprovement' => 'Мої покращення',
    'favReplays' => 'Улюблені повтори',
    'friends' => 'Друзі',
    'settings' => 'Налаштування',
    'logout' => 'Вийти',
    
    /* Leaderboard */
    'name' => 'Ім’я',
    'time' => 'Час',
    'blocks' => 'Фігури',
    'PPS' => 'PPS',
    'finesse' => 'Техніка',
    'date' => 'Дата',
    'replay' => 'Повтор',
    'place' => 'Місце',
    'nli' => 'Ви не авторизовані!',
    'today' => 'Сьогодні',
    'lastWeek' => 'Минулого тижня',
    'lastMonth' => 'Минулого місяця',
    'lastYear' => 'Минулого року',
    'allTime' => 'За весь час',
    'bestPlayers' => 'Кращі гравці',
    'bestGames' => 'Найкращі ігри',
    'bestSubs' => 'Кращі ігри',
    'latestGames' => 'Останні ігри',
    'leastBlocks' => 'За меншу кількість фігур',
    'myTimes' => 'Мої рекорди',
    'perfectFinesse' => 'Без помилок',
    
    /* Replay */
    'load' => 'Загрузити',
    'play' => 'Продовжити',
    'pause' => 'Пауза',
    'showSeg' => 'Показати сегменти',
    'fastestSeg' => 'Найшвидші сегменти',
    'slowestSeg' => 'Найповільніші сегменти',
    'speedChart' => 'Графік швидкості',
    'moreStats' => 'Більше статистики',
    'lines' => 'Лінії',
    'scoringPlaylist' => 'Звіт очок',
    'filterSP' => 'Фільтрувати звіт очок',
    'applyFilter' => 'Застосувати фільтр',
    'timestamp' => 'Час',
    'action' => 'Дія', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Очки',
    'position' => 'Позиція', //position in a replay
    'lAVG' => 'Локальне середнє значення',
    'gAVG' => 'Глобальне середнє значення',
    'repHelp' => 'Допомога', //link that shows information how to use the tool
    'repExport' => 'GIF або відео',
    
    /* PW change */
    'pwChange' => 'Змінити пароль',
    'newPw' => 'Новий пароль',
    'againPw' => 'Знову',
    'applyChange' => 'Застосувати зміни',
    
    /* Localization settings */
    'localSettings' => 'Параметри локалізації',
    'lang' => 'Мова',
    'langNone' => 'За замовчуванням (можна вибрати в верхньому меню)',
    'langDesc' => 'Виберіть бажану мову.',
    'timezone' => 'Часовий пояс',
    'timezoneDesc' => 'Використовується для перетворення часу в ваш місцевий час.',
    'country' => 'Країна',
    'continent' => 'Континент',
    'countryDesc' => 'Використовується для фільтрації рекордів за країною.',
    
    /* Profile */
    'ownProfile' => 'Це ваш публічний профіль доступний за',
    'bestTimes' => 'Найкращий час',
    'allTimes' => 'Переглянути всі рекорди спринту',
    'userImpr' => 'Статистика покращення',
    'userRanking' => 'Рейтинг рекордів',
    'gameStats' => 'Статистика гри',
    'latestGames' => 'Останні ігри',
    'noGames' => 'Цей користувач ще не брав участі в іграх.',
    'gamesPlayed' => 'Ігри',
    'totalTime' => 'Проведений час',
    'linesSent' => 'Ліній відправлено',
    'linesRec' => 'Ліній отримано',
    'placedBlocks' => 'Поставлено фігур',
    'blockCnt' => ':cnt фігур',
    'APM10Games' => '10 ігор APM',
    'PPS10Games' => '10 ігор PPS',
    'maxAPM' => 'Макс. APM',
    'maxREN' => 'Макс. Комбо',
    'longestGame' => 'Найдовша гра',
    'totalB2B' => 'Всього B2B',
    'mostSent' => 'Часто надіслані',
    'hours' => 'годин',
    'minutes' => 'хвилин',
    'createdMaps' => 'Створені карти',
    'viewMapsBy' => 'Переглянути всі створені карти',
    'playersCount' => 'Гравці',
    'gameResultPosition' => 'Місце',
    'gameResultRoundTime' => 'Час гри',
    'viewAllGamesOf' => 'Всі ігри у :mode',
    'noGamesOf' => ':name ще не грав у :mode.',
    
    /* Maps */
    'map' => 'Карта',
    'mapCreate' => 'Створити нову',
    'mapName' => 'Назва',
    'mapNameLong' => 'Назва карти',
    'mapDesc' => 'Опис',
    'mapRules' => 'Правила',
    'mapOptions' => 'Параметри',
    'mapPlay' => 'Грати',
    'mapPlayLink' => 'Грати карту',
    'mapAuthor' => 'Автор',
    'mapCreatedBy' => 'Створено',
    'backToMaps' => 'Назад до карт',
    'playThisMap' => 'Грати цю карту',
    'search' => 'Пошук',
    'myMaps' => 'Мої карти',
    'mapsByUser' => 'Карти від :name',
    'displayUnpublished' => 'Відобразити :cnt неопублікованих карт',
    'displayPublished' => 'Відобразити :cnt опубліковані карти',
    'usersMapMedals' => ':name медалі за карти',
    'usersCompletedMaps' => ':name завершені карти',
    'showRecords' => 'Показати рекорди',
    'details' => 'Подробиці',
    'playedBy' => 'Зіграно',
    'latestMapGames' => 'Останні зіграні карти',

    /* Stats */
    'improvementStats' => 'Статистика покращення',
    //keep ':name'
    'improvementInfo' => 'Цей графік показує рекорди спринтів по осі Y та дати цих рекордів по осі X. Виділена лінія показує покращення в рекордах :name. Наведіть курсор на будь-яке місце, щоб переглянути більше.',
    'date' => 'Дата',
    'result' => 'Результат',
    'submit' => 'Підтвердити',
    'qSettings' => 'Налаштування запиту',
    'dispAll' => 'Показати всі ігри',
    
    /* About */
    'aboutInfo' => 'Jstris це проста багатокористувацька онлайн гра, побудована на Javascript, HTML5 і Python (сервер).',
    'version' => 'Версія',
    'changelog' => 'Список змін',
    'discussion' => 'Обговорення',
    'learnMore' => 'Дізнатися більше',
    'contact' => 'Контакт',
    'serverCoverage' => 'Покриття вартості сервера',
    'supporters' => 'Підтримувачі проєкту',
    'translators' => 'Перекладачі',
    'moderators' => 'Модератори',
    
    /* Other */
    'notFound' => 'Не знайдено.',
    'invalidLink' => 'Запитане посилання недійсне.',
    'brb' => 'Тимчасово недоступний.',
    'tryAgain' => 'Сайт оновлюється, зайдіть пізніше.',
    'wasteDesc' => 'Співвідношення кількості Т-Фігур, не використаних у Т-Поворотах, до загальної кількості Т-Фігур',

    /* Settings - Other options */
    'setOther' => 'Інші варіанти',
    'hideAcc' => 'Приховати акаунт',
    'accVisibility' => 'Видимість',
    'hideAccInfo' => 'Якщо цей параметр увімкнено, обліковий запис буде виключено з публічної таблиці лідерів.',

    /* Chat reports */
    'reportU' => 'Поскаржитися на користувача',
    'reportDesc' => 'Ви можете надіслати скаргу, якщо хтось зловживає чатом.',
    'user' => 'Користувач',
    'reason' => 'Причина',
    'rr0' => 'Спам або небажана реклама',
    'rr1' => 'Вміст сексуального характеру',
    'rr2' => 'Вороже ставлення',
    'rr3' => 'Домагання чи знущання',
    'rr4' => 'Інше (вкажіть)',
    'sendReport' => 'Надіслати',
    
    /* Friends */
    'accept' => 'Прийняти',
    'ignore' => 'Ігнорувати',
    'pending' => 'Запити в очікування',
    'frFilter' => 'Фільтрувати за іменем',
    'noPending' => 'У Вас немає запитів у друзі.',
    'onlineNow' => 'Зараз у мережі',
    'recentlyAc' => 'Нещодавно активні',
    'lastActive' => 'Був у мережі :when',
    'noFriends' => 'Ваш список друзів порожній.',
    'ruSure' => 'Ви впевнені?',
    'rmFriend' => 'Ви хочете видалити цього гравця зі списку друзів?',
    'rmConfirm' => 'Так, видалити',
];
