<?php

return [
    'leaderboard' => 'تابلوی امتیازات',
    'tournament' => 'مسابقات',
    'maps' => 'نقشه ها',
    'mapsBrowse' => 'مرور',
    'myMaps' => 'نقشه های من',
    'mapsDesigner' => 'طراحی نقشه',
    'randomMap' => 'نقشه تصادفی',
    'mapsLatestGames' => 'جدیدترین بازی ها',
    'guide' => 'آموزش',
    'login' => 'ورود',
    'register' => 'ثبت نام',
    'myProfile' => 'پروفایل',
    'myImprovement' => 'پیشرفت های من',
    'favReplays' => 'بازپخش های مورد علاقه',
    'friends' => 'دوستان',
    'settings' => 'تنظیمات',
    'logout' => 'خروج',
    'stats' => 'آمار ها',
    'rankingStats' => 'آمار های امتیازات',
    'botMatches' => 'بازی های با بات',
    'activity' => 'فعالیت',
    'supporter' => 'حامی',
    
    /* Leaderboard */
    'name' => 'نام',
    'time' => 'زمان',
    'blocks' => 'مهره ها',
    'PPS' => 'PPS',
    'finesse' => 'دقت',
    'date' => 'زمان',
    'replay' => 'بازپخش',
    'place' => 'مکان',
    'nli' => 'وارد نشدید!',
    'today' => 'امروز',
    'lastWeek' => 'هفته اخیر',
    'lastMonth' => 'ماه اخیر',
    'lastYear' => 'سال اخیر',
    'allTime' => 'هر زمان',
    'bestPlayers' => 'بهترین بازیکنان',
    'bestGames' => 'بهترین بازی ها',
    'bestSubs' => 'بهترین اعضا',
    'latestGames' => 'جدیدترین بازی ها',
    'leastBlocks' => 'کمترین مهره ها',
    'myTimes' => 'زمان های من',
    'perfectFinesse' => 'دقت ۰',
    'mostGames' => 'بیشترین بازی ها',
    
    /* Replay */
    'load' => 'بازگذاری',
    'play' => 'پخش',
    'pause' => 'توقف',
    'showSeg' => 'نمایش بخش',
    'fastestSeg' => 'سریع ترین بخش',
    'slowestSeg' => 'کند ترین بخش',
    'speedChart' => 'جدول شرعت',
    'moreStats' => 'آمار بیشتر',
    'lines' => 'ردیف ها',
    'scoringPlaylist' => 'فهرست پخش امتیازی',
    'filterSP' => 'فیلتر فهرست پخش امتیازی',
    'applyFilter' => 'اعمال فیلتر',
    'timestamp' => 'مهر زمانی',
    'action' => 'عمل', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'معادل امتیازیt',
    'position' => 'موقعیت', //position in a replay
    'lAVG' => 'میانگین محلی',
    'gAVG' => 'میانگین جهانی',
    'repHelp' => 'کمک', //link that shows information how to use the tool
    'repExport' => 'گیف یا ویدیو',
    
    /* PW change */
    'pwChange' => 'تغییر گذرواژه',
    'newPw' => 'گذرواژه جدید',
    'againPw' => 'دوباره',
    'applyChange' => 'اعمال تغییرات',
    'emailChange' => 'تغییر ایمیل',
    'currentEmail' => 'کنونی',
    'newEmail' => 'ایمیل جدید',
    
    /* Localization settings */
    'localSettings' => 'تنظیمات محلی سازی',
    'lang' => 'زبان',
    'langNone' => 'هیچکدام (قابل انتخاب در منو بالا)',
    'langDesc' => 'زبان پیشنهادی را انتخاب کنید',
    'timezone' => 'موقعیت زمانی',
    'timezoneDesc' => 'برای تبدیل زمان به زمان محلی تان استفاده میشود',
    'country' => 'کشور',
    'continent' => 'قاره',
    'countryDesc' => 'برای نمایش تابلوی امتیازات کشوری',
    
    /* Profile */
    'ownProfile' => 'این پروفایل عمومیتان در دسترس است از',
    'bestTimes' => 'بهترین زمان ها',
    'allTimes' => 'نمایش همه زمان های سرعتی',
    'userImpr' => 'آمار های بهبود',
    'userRanking' => 'آمار های رنکیگ',
    'gameStats' => 'آمار های بازی',
    'latestGames' => 'جدیدترین بازی ها',
    'noGames' => 'این کاربر تا کنون هیچ بازیی نکرده است',
    'gamesPlayed' => 'بازی ها',
    'totalTime' => 'مجموع زمان',
    'linesSent' => 'ردیف های ارسال شده',
    'linesRec' => 'ردیف های دریافت شده',
    'placedBlocks' => 'مهره های چیده شده',
    'blockCnt' => ':cnt مهره ها',
    'APM10Games' => 'APM ۱۰ بازی',
    'PPS10Games' => 'PPS ۱۰ بازی',
    'maxAPM' => 'حداکثر APM',
    'maxREN' => 'حداکثر کمبو',
    'longestGame' => 'طولانی ترین بازی',
    'totalB2B' => 'مجموع پشت به پشت',
    'mostSent' => 'بیشترین ارسال',
    'hours' => 'ساعت',
    'minutes' => 'دقیقه',
    'createdMaps' => 'نقشه های ساخته شده',
    'viewMapsBy' => 'نمایش همه نقشه های ساخته شده توسط',
    'playersCount' => 'بازیکنان',
    'gameResultPosition' => 'موقعیت',
    'gameResultRoundTime' => 'زمان بازی',
    'viewAllGamesOf' => 'همه بازی های :mode',
    'noGamesOf' => ':name تا کنون های بازیی از :mode نکرده است.',
    
    /* Maps */
    'map' => 'نقشه',
    'mapCreate' => 'ایجاد جدید',
    'mapName' => 'نام',
    'mapNameLong' => 'نام نقشه',
    'mapDesc' => 'توضیحات',
    'mapRules' => 'قوانین',
    'mapOptions' => 'گزینه ها',
    'mapPlay' => 'اجرا',
    'mapPlayLink' => 'اجرای نقشه',
    'mapAuthor' => 'سازنده',
    'mapCreatedBy' => 'ساخته شده توسط',
    'backToMaps' => 'بازگشت به نقشه ها',
    'playThisMap' => 'اجرای این نقشه',
    'search' => 'جستجو',
    'myMaps' => 'نقشه های من',
    'mapsByUser' => 'نقشه های :name',
    'displayUnpublished' => 'نمایش :cnt نقشه منتشر نشده',
    'displayPublished' => 'نمایش :cnt نقشه منتشر نشده',
    'usersMapMedals' => 'نقشه های معین :name',
    'usersCompletedMaps' => 'نقشه های کامل شده :name',
    'showRecords' => 'نمایش رکورد',
    'details' => 'جزئیات',
    'playedBy' => 'اجرا شده توسط',
    'latestMapGames' => 'جدیدترین بازی های نقشه',

    /* Stats */
    'improvementStats' => 'آمار های بهبود',
    //keep ':name'
    'improvementInfo' => 'نمودار زیر ردیف های زمان مسابقه (محور Y) در مقابل زمان بازی (محور X) را نشان میدهد.ردیف های هایلایت شده بهبود رکورد شخصی :name را نشان میدهد. میتوانید برای اطلاعات بیشتر اشاره گر را سمت نقطه ها ببرید.',
    'date' => 'زمان',
    'result' => 'نتیجه',
    'submit' => 'ثبت',
    'qSettings' => 'تنظیمات پرسش',
    'dispAll' => 'نمایش همه بازی ها',
    
    /* About */
    'aboutInfo' => 'Jstris یک بازی ساده آنلاین چند نفره چینش مهره است که توسط جاوا اسکریپت، اچ تی ام ال ۵ و پایتون (سرور) ساخته شده است.',
    'version' => 'نسخه',
    'changelog' => 'تغییرات',
    'discussion' => 'بحث',
    'learnMore' => 'بیشتر بدانید',
    'contact' => 'تماس',
    'serverCoverage' => 'هزینه نگهداری سرور',
    'supporters' => 'حامیان پروژه',
    'translators' => 'مترجمان',
    'moderators' => 'مدیران',
    
    /* Other */
    'notFound' => 'پیدا نشد.',
    'invalidLink' => 'پیوند پیشنهادی نامعتبر است',
    'brb' => 'بر میگردیم.',
    'tryAgain' => 'پایگاه در حال بروزرسانی است، لطفا چند لحظه بعد مجددا تلاش کنید.',
    'wasteDesc' => 'نسبت مهره های T استفاده نشده برای تی اسپین (به مجموع مهره های T)',

    /* Settings - Other options */
    'setOther' => 'بقیه گزینه ها',
    'hideAcc' => 'مخفی کردن حساب',
    'accVisibility' => 'قابل دیدن',
    'hideAccInfo' => 'اگر فعال شود، حسابتان از تابلوی امتیازات خارج میشود',

    /* Chat reports */
    'reportU' => 'گزارش کاربر',
    'reportDesc' => 'اینجا میتوانید گزارش ایجاد کنید اگر فکر میکنید کسی از گفتگوی بازی سوء استفاده میکند.',
    'user' => 'کاربر',
    'reason' => 'دلیل',
    'rr0' => 'هرزنامه یا تبلیغات ناخواسته',
    'rr1' => 'محتوای صریح جنسی',
    'rr2' => 'صحبت نفرت آمیز',
    'rr3' => 'آزار و اذیت یا قلدری',
    'rr4' => 'سایر (مشخص کنید)',
    'sendReport' => 'ثبت گزارش',
    
    /* Friends */
    'accept' => 'قبول',
    'ignore' => 'نادیده',
    'pending' => 'درخواست های در انتظار',
    'frFilter' => 'فیلتر نام ها',
    'noPending' => 'اکنون هیچ درخواست دوستی در انتظاری نداربد',
    'onlineNow' => 'حالا برخط است',
    'recentlyAc' => 'اخیرا فعال بوده',
    'lastActive' => 'فعالیت در :when',
    'noFriends' => 'فعلا فهرست دوستانتان خالی است',
    'ruSure' => 'مطمئنید؟',
    'rmFriend' => 'آیا قصد حذف کردن این فرد از فهرست دوستان را دارید؟',
    'rmConfirm' => 'بله. حذف کن',

    /* Settings - Navigation */
    'setProfileNav' => 'پروفایل',
    'setLocalizationNav' => 'محلی سازی',
    'setPasswordNav' => 'گذرواژه',
    'setSupporterNav' => 'حمایت',
    'setOtherNav' => 'سایر',

    /* Settings - Discord */
    'setDiscordTitle' => 'اتصال دیسکورد',
    'disconnect' => 'قطع اتصال',
    'connectDiscord' => 'اتصال دیسکورد',

    /* Settings - Other */
    'setExperiments' => 'آزمایشات',
    'setExperimentsDesc' => 'فعالسازی دسترسی آزمایش به ویژگی های آزمایشی/تکمیل نشده',
    'setExperimentsNote' => 'ایده های خود درباره ویژگی های آزمایشی Jstris را در دیسکورد ما به اشتراک بگذارید',
    'deleteAccount' => 'حذف حساب',

    /* Settings - Supporter History */
    'returnBack' => 'عقب برگردید',
    'giftBalanceHistory' => 'تاریخچه تعادل هدیه',
    'message' => 'پیام',
    'change' => 'تغییر',
    'before' => 'قبل',
    'after' => 'بعد',
    'relative' => 'مرتبط',
    'none' => 'هیچکدام',

    /* Settings - Supporter Status */
    'subscription' => 'عضویت',
    'active' => 'فعال',
    'manage' => 'مدیریت',
    'renewsOn' => 'تجدید میشود در:',
    'oneTime' => 'تک زمانه',
    'expires' => 'منقضی شده',
    'extend' => 'تمدید',
    'giftingBalance' => 'تعادل هدیه',
    'days' => 'روز',
    'add' => 'افزودن',
    'useCode' => 'استفاده از کد',
    'balanceHistory' => 'تاریخچه تعادل',
    'noExpiration' => 'منقضی نشده',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'ارسال عکس سفارشی',
    'uploadCustomImageDesc' => 'عکس برای پروفایل خود در Jstris انتخاب کنید. عکس در صورت داشتن محتوای صریح یا خشونت آمیز حذف خواهد شد.',
    'supporterOption' => 'گزینه حمایت',
    'seeDetails' => 'دیدن جزئیات',
    'uploadPreviewCrop' => 'پیشنمایش را ارسال و برش دهید',

    /* Settings - Profile */
    'remove' => 'حذف',
    'noImageSelected' => 'هنوز هیچ عکسی انتخاب نشده',
    'bioPlaceholder' => 'پیام متنی وارد کنید تا در پروفایلتان قرار بگیرد',
    'bioFormatInfo' => 'شما میتوانید فراپیوند را اینجوری درست کنید: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'حساب های حامی میتوانند از فرمت متن، پیوند و شکلک استفاده کنند',
    'selectProfileImage' => 'انتخاب عکس پروفایل',
    'jstrisBlocks' => 'مهره های Jstris',
    'animalArt' => 'طرح حیوانات',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'حمایت از Jstris',
    'supporterLead' => 'Jstris بدون تبلیغات و رایگان برای همه است. شما با حمایت میتوانید این ویژگی های زیر را باز کنید:',
    'benefitProfileCustomizations' => 'سفارشی سازی پروفایل',
    'benefitProfileCustomizationsDesc' => 'شما میتوانید عکس پروفایل سفارشی آپلود کنید و از فرمت بندی اضافه در پیام «درباره» پروفایلتان استفاده کنید (بیش از ۲۰۰۰ کاراکتر، استفاده از فراپیوند و شکلک).',
    'benefitSaveMatchesBots' => 'ذخیره بازی های در مقابل بات ها',
    'benefitSaveMatchesBotsDesc' => 'بازی های 1v1 مقابل بات ها در نتایج بازی ها از جمله بازپخش و آمار پیشرفته ذخیره میشود.',
    'benefitUnlimitedReplays' => 'بازپخش بینهایت',
    'benefitUnlimitedReplaysDesc' => 'هیچکدام از بازپخش های حالت های تک نفره شما حذف نمیشود تا زمانی که حامی فعال باشید.',
    'getSupporterCta' => 'حامی Jstris شود!',
    'configureBenefits' => 'پیکربندی ویژگی ها',
    'nameChange' => 'تغییر نام',
    'nameChangeInfo' => 'یک حامی میتواند ماهی یکبار نام خود را عوض کند. میتوانید نام خود را اینجا تغییر دهید:',
    'newNameLabel' => 'نام جدید',
    'newNamePlaceholder' => 'نام کاربری جدید را وارد کنید',
    'manageSubscriptionTitle' => 'مدیریت عضویت Jstris',
    'manageSubscriptionInfo1' => 'برای بستن یا لغو اشتراک، وارد پی پال خود شوید و گزینه های مربوط را در داشبورد عضویت انتخاب کنید.',
    'manageSubscriptionInfo2' => 'در صورت بروز مشکل، میتوانید باما تماس بگیرید: jstris@jezevec10.com.',
    'close' => 'بستن',
];
