<?php

return [
    'leaderboard' => 'Ranking',
    'tournament' => 'Torneo',
    'maps' => 'Mapas',
    'mapsBrowse' => 'Explorar',
    'myMaps' => 'Mis mapas',
    'mapsDesigner' => 'diseñador de Mapas',
    'randomMap' => 'Mapa aleatorio',
    'mapsLatestGames' => 'Últimos juegos',
    'guide' => 'Guía',
    'login' => 'Conectarse',
    'register' => 'Registrarse',
    'myProfile' => 'Mi Perfil',
    'myImprovement' => 'Mi desarrollo',
    'favReplays' => 'Repeticiones favoritas',
    'settings' => 'Configuraciones',
    'logout' => 'Desconectarse',
    
    /* Leaderboard */
    'name' => 'Nombre',
    'time' => 'Tiempo',
    'blocks' => 'Piezas',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Fecha y Hora',
    'replay' => 'Repetición',
    'place' => 'Lugar',
    'nli' => '¡Desconectado!',
    'today' => 'Hoy',
    'lastWeek' => 'Semana pasada',
    'lastMonth' => 'Mes pasado',
    'lastYear' => 'Año pasado',
    'allTime' => 'Histórico',
    'bestPlayers' => 'Mejores jugadores',
    'bestGames' => 'Mejores partidas',
    'bestSubs' => 'Mejores tiempos',
    'latestGames' => 'Últimos juegos',
    'leastBlocks' => 'Menor cantidad de piezas',
    'myTimes' => 'Mis tiempos',
    'perfectFinesse' => '0 finesse',
    
    /* Replay */
    'load' => 'Cargar',
    'play' => 'Jugar',
    'pause' => 'Pausar',
    'showSeg' => 'Mostrar segmentos',
    'fastestSeg' => 'Segmentos rápidos',
    'slowestSeg' => 'Segmentos lentos',
    'speedChart' => 'Gráfico de velocidad',
    'moreStats' => 'Más estadísticas',
    'lines' => 'Líneas',
    'scoringPlaylist' => 'Lista de puntuación',
    'filterSP' => 'Filtrar lista de puntuación',
    'applyFilter' => 'Aplicar filtro',
    'timestamp' => 'Marca de tiempo',
    'action' => 'Acción', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Equivalente de puntuación',
    'position' => 'Posición', //position in a replay
    'lAVG' => 'Promedio local',
    'gAVG' => 'Promedio global',
    'repHelp' => 'Ayuda', //link that shows information how to use the tool
    'repExport' => 'GIF ó video',
    
    /* PW change */
    'pwChange' => 'Cambiar contraseña',
    'newPw' => 'Nueva contraseña',
    'againPw' => 'Reingresar contraseña',
    'applyChange' => 'Aplicar cambios',

    /* Localization settings */
    'localSettings' => 'Configuraciónes de localización',
    'lang' => 'Idioma',
    'langNone' => 'Ninguno (seleccionable en el menú superior)',
    'langDesc' => 'Seleccionar el idioma preferido.',
    'timezone' => 'Zona horaria',
    'timezoneDesc' => 'Usado para convertir el tiempo en tu hora local.',
    'country' => 'País',
    'continent' => 'Continente',
    'countryDesc' => 'Usado para mostrar tablas de posiciones por país.',
    
    /* Profile */
    'ownProfile' => 'Este es tu perfil público accesible en',
    'bestTimes' => 'Mejores tiempos',
    'allTimes' => 'Mirar tiempos de Carrera',
    'userImpr' => 'Ver estadísticas de mejora',
    'gameStats' => 'Estadísticas de partidas',
    'latestGames' => 'Últimos juegos',
    'noGames' => 'Este usuario aún no ha jugado todavía.',
    'gamesPlayed' => 'Partidas',
    'totalTime' => 'Tiempo total',
    'linesSent' => 'Líneas enviadas',
    'linesRec' => 'Líneas recibidas',
    'placedBlocks' => 'Piezas jugadas',
    'blockCnt' => ':cnt piezas',
    'APM10Games' => '10-juegos APM',
    'PPS10Games' => '10-juegos PPS',
    'maxAPM' => 'APM máximo',
    'maxREN' => 'Combo máximo',
    'longestGame' => 'Partida mas larga',
    'totalB2B' => 'B2Bs totales',
    'mostSent' => 'Enviadas máxima',
    'hours' => 'horas',
    'minutes' => 'minutos',
    'createdMaps' => 'Mapas creados',
    'viewMapsBy' => 'Ver todos los mapas creados por',
    'playersCount' => 'Jugadores',
    'gameResultPosition' => 'Posición',
    'gameResultRoundTime' => 'Tiempo de juego',
    'viewAllGamesOf' => 'Ver todos los juegos en :mode',
    'noGamesOf' => ':name aún no ha jugado todavía en :mode',
    
    /* Maps */
    'map' => 'Mapa',
    'mapCreate' => 'Crear nuevo',
    'mapName' => 'Nombre',
    'mapNameLong' => 'Nombre del Mapa',
    'mapDesc' => 'Descripción',
    'mapRules' => 'Regla',
    'mapOptions' => 'Opciones',
    'mapPlay' => 'Jugar',
    'mapPlayLink' => 'Jugar Mapa',
    'mapAuthor' => 'Autor',
    'mapCreatedBy' => 'Creado por',
    'backToMaps' => 'Volver a Mapas',
    'playThisMap' => 'Jugar este Mapa',
    'search' => 'Buscar',
    'myMaps' => 'Mis mapas',
    'mapsByUser' => 'Mapas de :name',
    'displayUnpublished' => 'Mostar :cnt mapas sin publicar',
    'displayPublished' => 'Mostar :cnt mapas publicados',
    'usersMapMedals' => 'Medallas de :name',
    'usersCompletedMaps' => 'Mapas completados de :name',
    'showRecords' => 'Ver marcas personales',
    'details' => 'Detalles',
    'playedBy' => 'Jugado por',
    'latestMapGames' => 'Los últimos juegos en Mapas',
    
    /* Stats */
    'improvementStats' => 'Estadísticas de mejora',
    //keep ':name'
    'improvementInfo' => 'El siguiente gráfico muestra el tiempo de Carrera (Eje Y) versus la fecha de la partida (Eje X). Las líneas destacadas muestran mejoras en el récord personal de :name. Puedes colocar el cursor sobre cualquier punto para ver más detalles.',
    'date' => 'Fecha',
    'result' => 'Resultado',
    'submit' => 'Enviar',
    'qSettings' => 'Configuración de solicitud',
    'dispAll' => 'Mostrar todas las partidas',
    
    /* About */
    'aboutInfo' => 'Jstris es un sencillo juego de bloques multijugador online, hecho en Javascript. HTML5 y Python (server).',
    'version' => 'Versión',
    'changelog' => 'Control de cambios',
    'discussion' => 'Discusión',
    'learnMore' => 'Conoce más',
    'contact' => 'Contacto',
    'serverCoverage' => 'Cobertura del costo para el servidor',
    'supporters' => 'Patrocinadores del proyecto',
    'translators' => 'Traductores',
    'moderators' => 'Moderadores',
    
    /* Other */
    'notFound' => 'No se encontró.',
    'invalidLink' => 'El enlace es inválido.',
    'brb' => 'Ya volvemos.',
    'tryAgain' => 'El sitio está siendo actualizado, por favor regresa en un momento.',

    /* Settings - Other options */
    'setOther' => 'Otras opciones',
    'hideAcc' => 'Esconder cuenta',
    'accVisibility' => 'Visibilidad',
    'hideAccInfo' => 'Si está habilitado la cuenta se excluirá en el Ranking público',

];
