<?php

return [
    'leaderboard' => 'Ranking',
    'tournament' => 'Torneo',
    'maps' => 'Mapas',
    'mapsBrowse' => 'Explorar',
    'myMaps' => 'Mis mapas',
    'mapsDesigner' => 'diseñador de Mapas',
    'randomMap' => 'Mapa aleatorio',
    'mapsLatestGames' => 'Últimos juegos',
    'guide' => 'Guía',
    'login' => 'Conectarse',
    'register' => 'Registrarse',
    'myProfile' => 'Mi Perfil',
    'myImprovement' => 'Mi desarrollo',
    'favReplays' => 'Repeticiones favoritas',
    'friends' => 'Amigos',
    'settings' => 'Configuraciones',
    'logout' => 'Desconectarse',
    
    /* Leaderboard */
    'name' => 'Nombre',
    'time' => 'Tiempo',
    'blocks' => 'Piezas',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Fecha y Hora',
    'replay' => 'Repetición',
    'place' => 'Lugar',
    'nli' => '¡Desconectado!',
    'today' => 'Hoy',
    'lastWeek' => 'Semana pasada',
    'lastMonth' => 'Mes pasado',
    'lastYear' => 'Año pasado',
    'allTime' => 'Histórico',
    'bestPlayers' => 'Mejores jugadores',
    'bestGames' => 'Mejores partidas',
    'bestSubs' => 'Mejores tiempos',
    'latestGames' => 'Últimos juegos',
    'leastBlocks' => 'Menor cantidad de piezas',
    'myTimes' => 'Mis tiempos',
    'perfectFinesse' => '0 finesse',
    
    /* Replay */
    'load' => 'Cargar',
    'play' => 'Jugar',
    'pause' => 'Pausar',
    'showSeg' => 'Mostrar segmentos',
    'fastestSeg' => 'Segmentos rápidos',
    'slowestSeg' => 'Segmentos lentos',
    'speedChart' => 'Gráfico de velocidad',
    'moreStats' => 'Más estadísticas',
    'lines' => 'Líneas',
    'scoringPlaylist' => 'Lista de puntuación',
    'filterSP' => 'Filtrar lista de puntuación',
    'applyFilter' => 'Aplicar filtro',
    'timestamp' => 'Marca de tiempo',
    'action' => 'Acción', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Equivalente de puntuación',
    'position' => 'Posición', //position in a replay
    'lAVG' => 'Promedio local',
    'gAVG' => 'Promedio global',
    'repHelp' => 'Ayuda', //link that shows information how to use the tool
    'repExport' => 'GIF ó video',
    
    /* PW change */
    'pwChange' => 'Cambiar contraseña',
    'newPw' => 'Nueva contraseña',
    'againPw' => 'Reingresar contraseña',
    'applyChange' => 'Aplicar cambios',
    'emailChange' => 'Cambiar correo electrónico',
    'currentEmail' => 'Actual',
    'newEmail' => 'Nuevo correo electrónico',

    /* Localization settings */
    'localSettings' => 'Configuraciónes de localización',
    'lang' => 'Idioma',
    'langNone' => 'Ninguno (seleccionable en el menú superior)',
    'langDesc' => 'Seleccionar el idioma preferido.',
    'timezone' => 'Zona horaria',
    'timezoneDesc' => 'Usado para convertir el tiempo en tu hora local.',
    'country' => 'País',
    'continent' => 'Continente',
    'countryDesc' => 'Usado para mostrar tablas de posiciones por país.',
    
    /* Profile */
    'ownProfile' => 'Este es tu perfil público accesible en',
    'bestTimes' => 'Mejores tiempos',
    'allTimes' => 'Mirar tiempos de Carrera',
    'userImpr' => 'Ver estadísticas de mejora',
    'userRanking' => 'Estadísticas de ranking',
    'gameStats' => 'Estadísticas de partidas',
    'latestGames' => 'Últimos juegos',
    'noGames' => 'Este usuario aún no ha jugado todavía.',
    'gamesPlayed' => 'Partidas',
    'totalTime' => 'Tiempo total',
    'linesSent' => 'Líneas enviadas',
    'linesRec' => 'Líneas recibidas',
    'placedBlocks' => 'Piezas jugadas',
    'blockCnt' => ':cnt piezas',
    'APM10Games' => '10-juegos APM',
    'PPS10Games' => '10-juegos PPS',
    'maxAPM' => 'APM máximo',
    'maxREN' => 'Combo máximo',
    'longestGame' => 'Partida mas larga',
    'totalB2B' => 'B2Bs totales',
    'mostSent' => 'Enviadas máxima',
    'hours' => 'horas',
    'minutes' => 'minutos',
    'createdMaps' => 'Mapas creados',
    'viewMapsBy' => 'Ver todos los mapas creados por',
    'playersCount' => 'Jugadores',
    'gameResultPosition' => 'Posición',
    'gameResultRoundTime' => 'Tiempo de juego',
    'viewAllGamesOf' => 'Ver todos los juegos en :mode',
    'noGamesOf' => ':name aún no ha jugado todavía en :mode',
    
    /* Maps */
    'map' => 'Mapa',
    'mapCreate' => 'Crear nuevo',
    'mapName' => 'Nombre',
    'mapNameLong' => 'Nombre del Mapa',
    'mapDesc' => 'Descripción',
    'mapRules' => 'Regla',
    'mapOptions' => 'Opciones',
    'mapPlay' => 'Jugar',
    'mapPlayLink' => 'Jugar Mapa',
    'mapAuthor' => 'Autor',
    'mapCreatedBy' => 'Creado por',
    'backToMaps' => 'Volver a Mapas',
    'playThisMap' => 'Jugar este Mapa',
    'search' => 'Buscar',
    'myMaps' => 'Mis mapas',
    'mapsByUser' => 'Mapas de :name',
    'displayUnpublished' => 'Mostar :cnt mapas sin publicar',
    'displayPublished' => 'Mostar :cnt mapas publicados',
    'usersMapMedals' => 'Medallas de :name',
    'usersCompletedMaps' => 'Mapas completados de :name',
    'showRecords' => 'Ver marcas personales',
    'details' => 'Detalles',
    'playedBy' => 'Jugado por',
    'latestMapGames' => 'Los últimos juegos en Mapas',
    
    /* Stats */
    'improvementStats' => 'Estadísticas de mejora',
    //keep ':name'
    'improvementInfo' => 'El siguiente gráfico muestra el tiempo de Carrera (Eje Y) versus la fecha de la partida (Eje X). Las líneas destacadas muestran mejoras en el récord personal de :name. Puedes colocar el cursor sobre cualquier punto para ver más detalles.',
    'date' => 'Fecha',
    'result' => 'Resultado',
    'submit' => 'Enviar',
    'qSettings' => 'Configuración de solicitud',
    'dispAll' => 'Mostrar todas las partidas',
    
    /* About */
    'aboutInfo' => 'Jstris es un sencillo juego de bloques multijugador online, hecho en Javascript. HTML5 y Python (server).',
    'version' => 'Versión',
    'changelog' => 'Control de cambios',
    'discussion' => 'Discusión',
    'learnMore' => 'Conoce más',
    'contact' => 'Contacto',
    'serverCoverage' => 'Cobertura del costo para el servidor',
    'supporters' => 'Patrocinadores del proyecto',
    'translators' => 'Traductores',
    'moderators' => 'Moderadores',
    
    /* Other */
    'notFound' => 'No se encontró.',
    'invalidLink' => 'El enlace es inválido.',
    'brb' => 'Ya volvemos.',
    'tryAgain' => 'El sitio está siendo actualizado, por favor regresa en un momento.',
    'wasteDesc' => 'Proporción de piezas T no usadas en un T-spin (Al total de piezas T)',

    /* Settings - Other options */
    'setOther' => 'Otras opciones',
    'hideAcc' => 'Esconder cuenta',
    'accVisibility' => 'Visibilidad',
    'hideAccInfo' => 'Si está habilitado la cuenta se excluirá en el Ranking público',


    /* Chat reports */
    'reportU' => 'Reportar usuario',
    'reportDesc' => 'Aquí puedes crear un reporte si piensas que alguien está abusando del chat.',
    'user' => 'Usuario',
    'reason' => 'Motivo',
    'rr0' => 'Spam o publicidad no deseada',
    'rr1' => 'Contenido sexualmente explícito',
    'rr2' => 'Discriminación',
    'rr3' => 'Acoso o Intimidación',
    'rr4' => 'Otro (especifíca)',
    'sendReport' => 'Enviar reporte',

    /* Friends */
    'accept' => 'Aceptar',
    'ignore' => 'Ignorar',
    'pending' => 'Solicitudes pendientes',
    'frFilter' => 'Filtrar nombres',
    'noPending' => 'Por el momento no tienes solicitudes pendientes.',
    'onlineNow' => 'En linea',
    'recentlyAc' => 'Activo recientemente',
    'lastActive' => 'Activo :when',
    'noFriends' => 'Por el momento tu lista de amigos está vacía.',
    'ruSure' => '¿Estás seguro?',
    'rmFriend' => '¿Quiéres eliminar a esta persona de tu lista de amigos?',
    'rmConfirm' => 'Si, eliminar',
    
    /* Settings - Navigation */
    'setProfileNav' => 'Perfil',
    'setLocalizationNav' => 'Localización',
    'setPasswordNav' => 'Contraseña',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => 'Otros',

    /* Settings - Discord */
    'setDiscordTitle' => 'Conectar Discord',
    'disconnect' => 'Desconectar',
    'connectDiscord' => 'Conectar Discord',

    /* Settings - Other */
    'setExperiments' => 'Experimentos',
    'setExperimentsDesc' => 'Habilita el acceso de prueba a funciones experimentales/en desarrollo',
    'setExperimentsNote' => 'Comparte tus ideas sobre funciones de prueba en el Discord de Jstris',
    'deleteAccount' => 'Eliminar cuenta',

    /* Settings - Supporter History */
    'returnBack' => 'Regresar',
    'giftBalanceHistory' => 'Historial de saldo de regalos',
    'message' => 'Mensaje',
    'change' => 'Cambio',
    'before' => 'Antes',
    'after' => 'Después',
    'relative' => 'Relativo',
    'none' => 'Ninguno',

    /* Settings - Supporter Status */
    'subscription' => 'Suscripción',
    'active' => 'activa',
    'manage' => 'Administrar',
    'renewsOn' => 'Renueva el:',
    'oneTime' => 'Única vez',
    'expires' => 'Expira',
    'extend' => 'Extender',
    'giftingBalance' => 'Saldo para regalar',
    'days' => 'días',
    'add' => 'Agregar',
    'useCode' => 'Usar código',
    'balanceHistory' => 'Historial de saldo',
    'noExpiration' => 'Sin vencimiento',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'Subir imagen personalizada',
    'uploadCustomImageDesc' => 'Elige una imagen para usar como foto pública de perfil en Jstris. Puede ser removida si se reporta como inapropiada.',
    'supporterOption' => 'Opción para Supporter',
    'seeDetails' => 'Ver detalles',
    'uploadPreviewCrop' => 'Subir para previsualizar y recortar',

    /* Settings - Profile */
    'remove' => 'Quitar',
    'noImageSelected' => 'Aún no se seleccionó imagen',
    'bioPlaceholder' => 'Ingresa un mensaje que aparecerá en tu perfil',
    'bioFormatInfo' => 'Puedes formatear enlaces así: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Las cuentas Supporter pueden usar formato, insertar enlaces y emotes',
    'selectProfileImage' => 'Seleccionar imagen de perfil',
    'jstrisBlocks' => 'Bloques Jstris',
    'animalArt' => 'Arte de animales',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris es sin anuncios y gratis para todos. Al apoyar desbloqueas estos beneficios:',
    'benefitProfileCustomizations' => 'Personalizaciones de perfil',
    'benefitProfileCustomizationsDesc' => 'Puedes subir una foto de perfil personalizada y usar formato extendido en el mensaje "Acerca de" (hasta 2000 caracteres, usar hipervínculos y emotes).',
    'benefitSaveMatchesBots' => 'Guardar partidas contra bots',
    'benefitSaveMatchesBotsDesc' => 'Tus 1v1 contra bots se guardarán en resultados incluyendo replays y estadísticas avanzadas.',
    'benefitUnlimitedReplays' => 'Replays ilimitados',
    'benefitUnlimitedReplaysDesc' => 'Ninguno de tus replays de modos de un jugador será eliminado mientras Supporter esté activo.',
    'getSupporterCta' => '¡Consigue Jstris Supporter!',
    'configureBenefits' => 'Configurar beneficios',
    'nameChange' => 'Cambio de nombre',
    'nameChangeInfo' => 'Como Supporter, puedes cambiar el nombre una vez al mes. Hazlo aquí:',
    'newNameLabel' => 'Nuevo nombre',
    'newNamePlaceholder' => 'Ingresa nuevo nombre de usuario',
    'manageSubscriptionTitle' => 'Administrar suscripción Jstris',
    'manageSubscriptionInfo1' => 'Para pausar o cancelar, inicia sesión en PayPal y elige la opción en el panel de Suscripción.',
    'manageSubscriptionInfo2' => 'En caso de problemas, contacta jstris@jezevec10.com.',
    'close' => 'Cerrar',
];
