<?php

return [
    'leaderboard' => 'Scorebord',
    'tournament' => 'Toernooi',
    'maps' => 'Borden',
    'mapsBrowse' => 'Bladeren',
    'myMaps' => 'Mijn borden',
    'mapsDesigner' => 'Bordontwerper',
    'randomMap' => 'Willekeurig bord',
    'mapsLatestGames' => 'Meest recente spellen',
    'guide' => 'Gids',
    'login' => 'Inloggen',
    'register' => 'Aanmelden',
    'myProfile' => 'Mijn profiel',
    'myImprovement' => 'Mijn verbetering',
    'favReplays' => 'Favoriete replays',
    'settings' => 'Instellingen',
    'logout' => 'Uitloggen',
    
    /* Leaderboard */
    'name' => 'Naam',
    'time' => 'Tijd',
    'blocks' => 'Blokken',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Datum',
    'replay' => 'Replay',
    'place' => 'Plaats',
    'nli' => 'Niet ingelogd!',
    'today' => 'Vandaag',
    'lastWeek' => 'Vorige week',
    'lastMonth' => 'Vorige maand',
    'lastYear' => 'Vorig jaar',
    'allTime' => 'Aller tijden',
    'bestPlayers' => 'Beste spelers',
    'bestGames' => 'Beste spellen',
    'bestSubs' => 'Beste subs',
    'latestGames' => 'Meest recente spellen',
    'leastBlocks' => 'De minste blokken',
    'myTimes' => 'Mijn tijden',
    'perfectFinesse' => '0 finesse',
    
    /* Replay */
    'load' => 'Laden',
    'play' => 'Afspelen',
    'pause' => 'Pauzeren',
    'showSeg' => 'Toon segmenten',
    'fastestSeg' => 'Snelste segmenten',
    'slowestSeg' => 'Langzaamste segmenten',
    'speedChart' => 'Snelheidsgrafiek',
    'moreStats' => 'Meer statistieken',
    'lines' => 'Lijnen',
    'scoringPlaylist' => 'Scoring playlist',
    'filterSP' => 'Filter scoring playlist',
    'applyFilter' => 'Filter toepassen',
    'timestamp' => 'Timestamp',
    'action' => 'Actie', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Score equivalent',
    'position' => 'Positie', //position in a replay
    'lAVG' => 'Lokaal gemiddelde',
    'gAVG' => 'Globaal gemiddelde',
    'repHelp' => 'Help', //link that shows information how to use the tool
    'repExport' => 'GIF of video',
    
    /* PW change */
    'pwChange' => 'Wachtwoord veranderen',
    'newPw' => 'Nieuw wachtwoord',
    'againPw' => 'Opnieuw',
    'applyChange' => 'Verandering toepassen',
    'emailChange' => 'E-mailadres wijzigen',
    'currentEmail' => 'Huidig',
    'newEmail' => 'Nieuw e-mailadres',
    
    /* Localization settings */
    'localSettings' => 'Lokalisatie-instellingen',
    'lang' => 'Taal',
    'langNone' => 'Geen (selecteerbaar in menu rechtsboven)',
    'langDesc' => 'Selecteer de voorkeurstaal.',
    'timezone' => 'Tijdzone',
    'timezoneDesc' => 'Wordt gebruikt om de tijd om te rekenen naar lokale tijd.',
    'country' => 'Land',
    'continent' => 'Continent',
    'countryDesc' => 'Wordt gebruikt om scoreborden per land te tonen.',
    
    /* Profile */
    'ownProfile' => 'Dit is je openbare profiel beschikbaar bij',
    'bestTimes' => 'Beste tijden',
    'allTimes' => 'Bekijk alle sprinttijden',
    'userImpr' => 'Bekijk verbetering',
    'gameStats' => 'Spelstatistieken',
    'latestGames' => 'Meest recente spellen',
    'noGames' => 'Deze gebruiker heeft nog geen spellen gespeeld.',
    'gamesPlayed' => 'Spellen',
    'totalTime' => 'Totale tijd',
    'linesSent' => 'Lijnen gestuurd',
    'linesRec' => 'Lijnen ontvangen',
    'placedBlocks' => 'Geplaatste blokken',
    'blockCnt' => ':cnt blokken',
    'APM10Games' => '10-spellen APM',
    'PPS10Games' => '10-spellen PPS',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Combo',
    'longestGame' => 'Langste spel',
    'totalB2B' => 'Totale B2Bs',
    'mostSent' => 'Meest gestuurd',
    'hours' => 'uur',
    'minutes' => 'minuten',
    'createdMaps' => 'Gemaakte borden',
    'viewMapsBy' => 'Bekijk alle borden gemaakt door',
    'playersCount' => 'Spelers',
    'gameResultPosition' => 'Positie',
    'gameResultRoundTime' => 'Speltijd',
    'viewAllGamesOf' => 'Bekijk alle :mode spellen',
    'noGamesOf' => ':name heeft nog geen :mode spellen gespeeld.',
    
    /* Maps */
    'map' => 'Bord',
    'mapCreate' => 'Maak nieuw',
    'mapName' => 'Naam',
    'mapNameLong' => 'Naam Bord',
    'mapDesc' => 'Beschrijving',
    'mapRules' => 'Regels',
    'mapOptions' => 'Opties',
    'mapPlay' => 'Spelen',
    'mapPlayLink' => 'Bord spelen',
    'mapAuthor' => 'Auteur',
    'mapCreatedBy' => 'Gemaakt door',
    'backToMaps' => 'Terug naar borden',
    'playThisMap' => 'Speel dit bord',
    'search' => 'Zoeken',
    'myMaps' => 'Mijn borden',
    'mapsByUser' => ':name\'s borden',
    'displayUnpublished' => ':cnt niet-gepubliceerde borden weergeven',
    'displayPublished' => ':cnt gepubliceerde borden weergeven',
    'usersMapMedals' => ':name\'s bordmedailles',
    'usersCompletedMaps' => ':name\'s voltooide borden',
    'showRecords' => 'Toon records',
    'details' => 'Details',
    'playedBy' => 'Gespeeld door',
    'latestMapGames' => 'Meest recente spellen',

    /* Stats */
    'improvementStats' => 'Verbeteringsstatistieken',
    //keep ':name'
    'improvementInfo' => 'The following graph shows line race time (Y axis) vs game date (X axis). Highlighted line shows improvements in :name\'s personal records. You can place your cursor over any point to show the game details.',
    'improvementInfo' => 'De volgende grafiek toont de racetijd (Y-as) vs. datum (X-as). De gemarkeerde lijn laat de verbetering in :name\'s persoonlijke records zien. Plaats de cursor boven een punt om meer details te zien.',
    'date' => 'Datum',
    'result' => 'Resultaat',
    'submit' => 'Toepassen',
    'qSettings' => 'Query-instellingen',
    'dispAll' => 'Toon alle spellen',
    
    /* About */
    'aboutInfo' => 'Jstris is een simpel online multiplayerspel ontwikkeld in Javascript, HTML5 en Python (server).',
    'version' => 'Versie',
    'changelog' => 'Changelog',
    'discussion' => 'Discussie',
    'learnMore' => 'Meer weten',
    'contact' => 'Contact',
    'serverCoverage' => 'Dekking serverkosten',
    'supporters' => 'Project supporters',
    'translators' => 'Vertalers',
    'moderators' => 'Moderators',
    
    /* Other */
    'notFound' => 'Niet gevonden.',
    'invalidLink' => 'Aangevraagde link is ongeldig.',
    'brb' => 'Ben zo terug.',
    'tryAgain' => 'De site wordt momenteel geüpdatet, probeer het over enkele ogenblikken opnieuw.',

    /* Settings - Other options */
    'setOther' => 'Andere opties',
    'hideAcc' => 'Verborgen account',
    'accVisibility' => 'Zichtbaarheid',
    'hideAccInfo' => 'Als je dit inschakelt zal je account niet getoond worden op openbare scoreborden.',

    /* Chat reports */
    'reportU' => 'Misbruik melden',
    'reportDesc' => 'Als een gebruiker de gamechat misbruikt kun je dat hier melden.',
    'user' => 'Gebruiker',
    'reason' => 'Reden',
    'rr0' => 'Spam of ongewenste reclame',
    'rr1' => 'Sexueel expliciete inhoud',
    'rr2' => 'Haatzaaien',
    'rr3' => 'Pesten of intimidatie',
    'rr4' => 'Anders, namelijk:',
    'sendReport' => 'Melding versturen',
    
];
