<?php

return [
    'leaderboard' => '리더 보드',
    'tournament' => '토너먼트',
    'maps' => '맵',
    'mapsBrowse' => '둘러보기',
    'myMaps' => '내가 만든 맵',
    'mapsDesigner' => '맵 디자이너',
    'mapsLatestGames' => '최근 기록',
    'guide' => '가이드',
    'login' => '로그인',
    'register' => '가입',
    'myProfile' => '내 프로필',
    'myImprovement' => '나의 기록들',
    'favReplays' => '저장한 리플레이',
    'settings' => '설정',
    'logout' => '로그 아웃',
    
    /* Leaderboard */
    'name' => '이름',
    'time' => '시각',
    'blocks' => '블록',
    'PPS' => '초당 사용하는 블럭 갯수',
    'finesse' => '피네스',
    'date' => '날짜',
    'replay' => '다시보기',
    'place' => '공간',
    'nli' => '로그인 실패',
    'today' => '오늘',
    'lastWeek' => '지난주',
    'lastMonth' => '지난 달',
    'lastYear' => '작년',
    'allTime' => '모든 기록들',
    'bestPlayers' => '최고의 선수들',
    'bestGames' => '최고의 게임',
    'bestSubs' => '가장 빠른 시간',
    'latestGames' => '이전 게임들',
    'leastBlocks' => '적은 블럭수',
    'myTimes' => '나의 기록들',
    'perfectFinesse' => '0 피네스',
    
    /* Replay */
    'load' => '불러오기',
    'play' => '게임하기',
    'pause' => '멈춤',
    'showSeg' => '구분해서 보기',
    'fastestSeg' => '가장 빠른 구간',
    'slowestSeg' => '가장 느린 구간',
    'speedChart' => '속도 차트',
    'moreStats' => '스탯 더보기',
    'lines' => '줄',
    'scoringPlaylist' => '점수 명세',
    'filterSP' => '점수 명세 필터',
    'applyFilter' => '필터 적용',
    'timestamp' => '시간',
    'action' => '기술', // e.g. combo, tspin, perfect clear
    'scoreEq' => '점수',
    'position' => '현재 위치', //position in a replay
    'lAVG' => '구간 평균',
    'gAVG' => '전체 평균',
    'repHelp' => '도움말', //link that shows information how to use the tool
    
    /* PW change */
    'pwChange' => '비밀번호 변경',
    'newPw' => '새 비밀번호',
    'againPw' => '새 비밀번호 재입력',
    'applyChange' => '변경하기',
    
    /* Localization settings */
    'localSettings' => '지역 설정',
    'lang' => '언어',
    'langNone' => '설정 없음 (상단에서 직접 선택)',
    'langDesc' => '선호하는 언어를 설정하세요.',
    'timezone' => '시간대',
    'timezoneDesc' => '설정한 시간대에 맞춰 시간을 표시합니다.',
    'country' => '국가',
    'countryDesc' => '국가별 리더보드를 표시할 때 사용합니다.',
    
    /* Profile */
    'ownProfile' => '공개 프로필',
    'bestTimes' => '가장 좋은 시간',
    'allTimes' => '모든 스프린트 기록 보기',
    'userImpr' => '더 많은 게임 내용',
    'gameStats' => '게임 내용',
    'latestGames' => '지난 게임',
    'noGames' => '사용자가 아직 게임을 하지 않았습니다.',
    'gamesPlayed' => '게임 플레이',
    'totalTime' => '플레이 시간',
    'linesSent' => '보냄 ',
    'linesRec' => '받음',
    'placedBlocks' => '사용한 블럭 갯수',
    'maxAPM' => '최대 공격 속도',
    'maxREN' => '최대 콤보',
    'longestGame' => '가장 긴 게임',
    'totalB2B' => '모든 백투백',
    'mostSent' => '가장 많이 보낸 공격',
    'hours' => '시간',
    'minutes' => '분',
    
    /* Stats */
    'improvementStats' => '더 많은 내용',
    //keep ':name'
    'improvementInfo' => '게임 기록을 플레이한 날짜에 따라 정렬한 그래프입니다. 강조된 선은 :name님의 개인 기록 향상 추세를 나타냅니다. 마우스를 올려 각 게임에 대한 정보를 확인할 수 있습니다.',
    'date' => '날짜',
    'result' => '결과',
    'submit' => '제출',
    'qSettings' => '질문',
    'dispAll' => '모든 게임 보기',
    
    /* About */
    'aboutInfo' => 'Jstris는 자바스크립트를 이용한 쉽고 편한 블록 게임이며, 서버는 HTML5 와 Python을 사용합니다.',
    'version' => '버전',
    'changelog' => '변경사항',
    'discussion' => '토론',
    'learnMore' => '더보기',
    'contact' => '연락처',
    'serverCoverage' => '서버 후원',
    'supporters' => '후원자',
    
    /* Other */
    'notFound' => '찾을 수 없음',
    'invalidLink' => '존재하지 않는 링크입니다.',
    'brb' => '곧 돌아오겠습니다.',
    'tryAgain' => '현재 업데이트 중이니, 조금 있다 다시 시도해주시기 바랍니다.',
];
