<?php
return [
    'leaderboard' => 'Pointtavle',
    'tournament' => 'Turnering',
    'maps' => 'Baner',
    'mapsBrowse' => 'Vælg',
    'myMaps' => 'Mine baner',
    'mapsDesigner' => 'Bane Designer',
    'mapsLatestGames' => 'Seneste Spil',
    'guide' => 'Guide',
    'login' => 'Login',
    'register' => 'Registrer',
    'myProfile' => 'Min profil',
    'myImprovement' => 'Min fremskridt',
    'favReplays' => 'Favorit genafspilninger',
    'settings' => 'Indstillinger',
    'logout' => 'Log ud',
    
    /* Leaderboard */
    'name' => 'Navn',
    'time' => 'Tid',
    'blocks' => 'Blokke',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Dato',
    'replay' => 'Genafspilning',
    'place' => 'Placering',
    'nli' => 'Ikke logget ind!',
    'today' => 'I dag',
    'lastWeek' => 'Sidste uge',
    'lastMonth' => 'Sidste måned',
    'lastYear' => 'Sidste år',
    'allTime' => 'Alle tider',
    'bestPlayers' => 'Bedste spillere',
    'bestGames' => 'Bedste spil',
    'bestSubs' => 'Bedste subs',
    'latestGames' => 'Seneste spil',
    'leastBlocks' => 'Mindst blokke',
    'myTimes' => 'Mine tider',
    'perfectFinesse' => '0 finesse',
    
    /* Replay */
    'load' => 'Indlæs',
    'play' => 'Spil',
    'pause' => 'Pause',
    'showSeg' => 'Vis segmenter',
    'fastestSeg' => 'Hurtigste segments',
    'slowestSeg' => 'Langsomste segments',
    'speedChart' => 'Hastigheds kort',
    'moreStats' => 'Flere statistikker',
    'lines' => 'Linjer',
    'scoringPlaylist' => 'Scorende playlist',
    'filterSP' => 'Filtrér scorende playlist',
    'applyFilter' => 'Anvend filter',
    'timestamp' => 'Timestamp',
    'action' => 'Handling', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Score er ensbetydende',
    'position' => 'Position', //position in a replay
    'lAVG' => 'Lokal gennemsnitlig',
    'gAVG' => 'Global gennemsnitlig',
    'repHelp' => 'Hjælp', //link that shows information how to use the tool
    
    /* PW change */
    'pwChange' => 'Skift adgangskode',
    'newPw' => 'Ny adgangskode',
    'againPw' => 'Igen',
    'applyChange' => 'Anvend de skiftede indstillinger',
    
    /* Localization settings */
    'localSettings' => 'Lokaliserings indstillinger',
    'lang' => 'Sprog',
    'langNone' => 'Intet (Valgbar i top menuen)',
    'langDesc' => 'Vælg det foretrukne sprog.',
    'timezone' => 'Tidszone',
    'timezoneDesc' => 'Brugt til at omvende tid til lokal tid.',
    'country' => 'Land',
    'countryDesc' => 'Bliver brugt til at vise land på pointtavlen.',
    
    /* Profile */
    'ownProfile' => 'Det her er din offentlige profil adgang ved',
    'bestTimes' => 'Bedste tider',
    'allTimes' => 'Vis alle sprint tider',
    'userImpr' => 'Vis fremgangs statistikker',
    'gameStats' => 'Spil statistikker',
    'latestGames' => 'Seneste spil',
    'noGames' => 'Denne bruger har ikke spillet et spil endnu.',
    'gamesPlayed' => 'Spil',
    'totalTime' => 'Total tid',
    'linesSent' => 'Linjer sendt',
    'linesRec' => 'Linjer modtaget',
    'placedBlocks' => 'Placerede blokke',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Combo',
    'longestGame' => 'Længste game',
    'totalB2B' => 'Total B2Bs',
    'mostSent' => 'Flest sendt',
    'hours' => 'timer',
    'minutes' => 'minutter',
    
    /* Stats */
    'improvementStats' => 'Fremgangs statistikker',
    //keep ':name'
    'improvementInfo' => 'Den følgende graf viser linje race tid (Y axen) vs spil dato (X axen). Fremhævede linjer viser fremgang for :name\'s personlige rekorder. Du kan placere din mus over ethvert point for at se spil detaljer..',
    'date' => 'Dato',
    'result' => 'Resultater',
    'submit' => 'Send',
    'qSettings' => 'Spørgssmåls settings',
    'dispAll' => 'Vis alle spil',
    
    /* About */
    'aboutInfo' => 'Jstris er et simpelt online multiplayer blok spil bygget i Javascript, HTML5 og Python (server).',
    'version' => 'Version',
    'changelog' => 'Changelog',
    'discussion' => 'Diskussion',
    'learnMore' => 'Lær mere',
    'contact' => 'Kontakt',
    'serverCoverage' => 'Server omkostninger',
    'supporters' => 'Projekt støttere',
    
    /* Other */
    'notFound' => 'Ikke fundet.',
    'invalidLink' => 'Det følgende link er invalid.',
    'brb' => 'Snarest tilbage.',
    'tryAgain' => 'Siden bliver opdateret, prøv igen om lidt tid.',
];