<?php
return [
    'leaderboard' => 'Pointtavle',
    'tournament' => 'Turnering',
    'maps' => 'Baner',
    'mapsBrowse' => 'Vælg',
    'myMaps' => 'Mine baner',
    'mapsDesigner' => 'Bane Designer',
    'mapsLatestGames' => 'Seneste Spil',
    'guide' => 'Guide',
    'login' => 'Login',
    'register' => 'Registrer',
    'myProfile' => 'Min profil',
    'myImprovement' => 'Min fremskridt',
    'favReplays' => 'Favorit genafspilninger',
    'settings' => 'Indstillinger',
    'logout' => 'Log ud',
    
    /* Leaderboard */
    'name' => 'Navn',
    'time' => 'Tid',
    'blocks' => 'Blokke',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Dato',
    'replay' => 'Genafspilning',
    'place' => 'Placering',
    'nli' => 'Ikke logget ind!',
    'today' => 'I dag',
    'lastWeek' => 'Sidste uge',
    'lastMonth' => 'Sidste måned',
    'lastYear' => 'Sidste år',
    'allTime' => 'Alle tider',
    'bestPlayers' => 'Bedste spillere',
    'bestGames' => 'Bedste spil',
    'bestSubs' => 'Bedste subs',
    'latestGames' => 'Seneste spil',
    'leastBlocks' => 'Mindst blokke',
    'myTimes' => 'Mine tider',
    'perfectFinesse' => '0 finesse',
    
    /* Replay */
    'load' => 'Indlæs',
    'play' => 'Spil',
    'pause' => 'Pause',
    'showSeg' => 'Vis segmenter',
    'fastestSeg' => 'Hurtigste segments',
    'slowestSeg' => 'Langsomste segments',
    'speedChart' => 'Hastigheds kort',
    'moreStats' => 'Flere statistikker',
    'lines' => 'Linjer',
    'scoringPlaylist' => 'Scorende playlist',
    'filterSP' => 'Filtrér scorende playlist',
    'applyFilter' => 'Anvend filter',
    'timestamp' => 'Timestamp',
    'action' => 'Handling', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Score er ensbetydende',
    'position' => 'Position', //position in a replay
    'lAVG' => 'Lokal gennemsnitlig',
    'gAVG' => 'Global gennemsnitlig',
    'repHelp' => 'Hjælp', //link that shows information how to use the tool
    
    /* PW change */
    'pwChange' => 'Skift adgangskode',
    'newPw' => 'Ny adgangskode',
    'againPw' => 'Igen',
    'applyChange' => 'Anvend de skiftede indstillinger',
    'emailChange' => 'Skift e-mail',
    'currentEmail' => 'Nuværende',
    'newEmail' => 'Ny e-mail',
    
    /* Localization settings */
    'localSettings' => 'Lokaliserings indstillinger',
    'lang' => 'Sprog',
    'langNone' => 'Intet (Valgbar i top menuen)',
    'langDesc' => 'Vælg det foretrukne sprog.',
    'timezone' => 'Tidszone',
    'timezoneDesc' => 'Brugt til at omvende tid til lokal tid.',
    'country' => 'Land',
    'countryDesc' => 'Bliver brugt til at vise land på pointtavlen.',
    
    /* Profile */
    'ownProfile' => 'Det her er din offentlige profil adgang ved',
    'bestTimes' => 'Bedste tider',
    'allTimes' => 'Vis alle sprint tider',
    'userImpr' => 'Vis fremgangs statistikker',
    'gameStats' => 'Spil statistikker',
    'latestGames' => 'Seneste spil',
    'noGames' => 'Denne bruger har ikke spillet et spil endnu.',
    'gamesPlayed' => 'Spil',
    'totalTime' => 'Total tid',
    'linesSent' => 'Linjer sendt',
    'linesRec' => 'Linjer modtaget',
    'placedBlocks' => 'Placerede blokke',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Combo',
    'longestGame' => 'Længste game',
    'totalB2B' => 'Total B2Bs',
    'mostSent' => 'Flest sendt',
    'hours' => 'timer',
    'minutes' => 'minutter',
    
    /* Stats */
    'improvementStats' => 'Fremgangs statistikker',
    //keep ':name'
    'improvementInfo' => 'Den følgende graf viser linje race tid (Y axen) vs spil dato (X axen). Fremhævede linjer viser fremgang for :name\'s personlige rekorder. Du kan placere din mus over ethvert point for at se spil detaljer..',
    'date' => 'Dato',
    'result' => 'Resultater',
    'submit' => 'Send',
    'qSettings' => 'Spørgssmåls settings',
    'dispAll' => 'Vis alle spil',
    
    /* About */
    'aboutInfo' => 'Jstris er et simpelt online multiplayer blok spil bygget i Javascript, HTML5 og Python (server).',
    'version' => 'Version',
    'changelog' => 'Changelog',
    'discussion' => 'Diskussion',
    'learnMore' => 'Lær mere',
    'contact' => 'Kontakt',
    'serverCoverage' => 'Server omkostninger',
    'supporters' => 'Projekt støttere',
    
    /* Other */
    'notFound' => 'Ikke fundet.',
    'invalidLink' => 'Det følgende link er invalid.',
    'brb' => 'Snarest tilbage.',
    'tryAgain' => 'Siden bliver opdateret, prøv igen om lidt tid.',
    
    /* Settings - Navigation */
    'setProfileNav' => 'Profil',
    'setLocalizationNav' => 'Lokalisering',
    'setPasswordNav' => 'Adgangskode',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => 'Andre',

    /* Settings - Discord */
    'setDiscordTitle' => 'Forbind Discord',
    'disconnect' => 'Afbryd',
    'connectDiscord' => 'Forbind Discord',

    /* Settings - Other */
    'setExperiments' => 'Eksperimenter',
    'setExperimentsDesc' => 'Aktiver testadgang til eksperimentelle/ufærdige funktioner',
    'setExperimentsNote' => 'Del dine idéer om testede funktioner på Jstris Discord',
    'deleteAccount' => 'Slet konto',

    /* Settings - Supporter History */
    'returnBack' => 'Tilbage',
    'giftBalanceHistory' => 'Historik for gave-saldo',
    'message' => 'Besked',
    'change' => 'Ændring',
    'before' => 'Før',
    'after' => 'Efter',
    'relative' => 'Relativ',
    'none' => 'Ingen',

    /* Settings - Supporter Status */
    'subscription' => 'Abonnement',
    'active' => 'aktiv',
    'manage' => 'Administrer',
    'renewsOn' => 'Fornyes:',
    'oneTime' => 'Éngang',
    'expires' => 'Udløber',
    'extend' => 'Forlæng',
    'giftingBalance' => 'Gave-saldo',
    'days' => 'dage',
    'add' => 'Tilføj',
    'useCode' => 'Brug kode',
    'balanceHistory' => 'Saldo-historik',
    'noExpiration' => 'Ingen udløbsdato',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'Upload brugerdefineret billede',
    'uploadCustomImageDesc' => 'Vælg et billede som offentlig profilbillede på Jstris. Billedet kan fjernes, hvis det rapporteres som upassende.',
    'supporterOption' => 'Supporter-valgmulighed',
    'seeDetails' => 'Se detaljer',
    'uploadPreviewCrop' => 'Upload for at forhåndsvise og beskære',

    /* Settings - Profile */
    'remove' => 'Fjern',
    'noImageSelected' => 'Intet billede valgt endnu',
    'bioPlaceholder' => 'Indtast tekst, der vises på din profil',
    'bioFormatInfo' => 'Du kan formatere hyperlinks sådan her: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Supporter-konti kan bruge formatering, indsætte links og emotes',
    'selectProfileImage' => 'Vælg profilbillede',
    'jstrisBlocks' => 'Jstris blokke',
    'animalArt' => 'Dyre-kunst',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris er uden reklamer og gratis for alle. Ved at støtte kan du låse op for følgende fordele:',
    'benefitProfileCustomizations' => 'Profiltilpasninger',
    'benefitProfileCustomizationsDesc' => 'Du kan uploade brugerdefineret profilbillede og bruge udvidet formatering i "Om"-beskeden (op til 2000 tegn, brug hyperlinks og emotes).',
    'benefitSaveMatchesBots' => 'Gem kampe mod bots',
    'benefitSaveMatchesBotsDesc' => 'Dine 1v1 mod bots gemmes i kampresultater inklusiv replays og avancerede statistikker.',
    'benefitUnlimitedReplays' => 'Ubegrænsede replays',
    'benefitUnlimitedReplaysDesc' => 'Ingen af dine replays fra singleplayer-tilstande slettes, mens Supporter er aktiv.',
    'getSupporterCta' => 'Få Jstris Supporter!',
    'configureBenefits' => 'Konfigurer fordele',
    'nameChange' => 'Skift navn',
    'nameChangeInfo' => 'Som Supporter kan du ændre navn én gang om måneden. Ændr dit navn her:',
    'newNameLabel' => 'Nyt navn',
    'newNamePlaceholder' => 'Indtast nyt brugernavn',
    'manageSubscriptionTitle' => 'Administrer Jstris-abonnement',
    'manageSubscriptionInfo1' => 'For at sætte på pause eller annullere, log ind på din PayPal-konto og vælg indstillingen på abonnementspanelet.',
    'manageSubscriptionInfo2' => 'Hvis der opstår problemer, kontakt jstris@jezevec10.com.',
    'close' => 'Luk',
];