<?php

return [
    'leaderboard' => 'Classificação',
    'tournament' => 'Torneio',
    'maps' => 'Mapas',
    'mapsBrowse' => 'Navegar',
    'myMaps' => 'Meus mapas',
    'mapsDesigner' => 'Criador de Mapas',
    'randomMap' => 'Mapa aleatório',
    'mapsLatestGames' => 'Últimos jogos',
    'guide' => 'Guia',
    'login' => 'Entrar',
    'register' => 'Registrar',
    'myProfile' => 'Meu perfil',
    'myImprovement' => 'Meu progresso',
    'favReplays' => 'Replays favoritos',
    'friends' => 'Amigos',
    'settings' => 'Configurações',
    'logout' => 'Sair',
    
    /* Leaderboard */
    'name' => 'Nome',
    'time' => 'Tempo',
    'blocks' => 'Blocos',
    'PPS' => 'PPS',
    'finesse' => 'Fineza',
    'date' => 'Data',
    'replay' => 'Replay',
    'place' => 'Lugar',
    'nli' => 'Não está logado!',
    'today' => 'Hoje',
    'lastWeek' => 'Semana passada',
    'lastMonth' => 'Mês passado',
    'lastYear' => 'Ano passado',
    'allTime' => 'Tempo todo',
    'bestPlayers' => 'Melhores jogadores',
    'bestGames' => 'Melhores jogos',
    'bestSubs' => 'Melhores tempos',
    'latestGames' => 'Jogos recentes',
    'leastBlocks' => 'Menor quantia de blocos',
    'myTimes' => 'Meus tempos',
    'perfectFinesse' => 'Fineza 0',
    
    /* Replay */
    'load' => 'Carregar',
    'play' => 'Jogar',
    'pause' => 'Pausar',
    'showSeg' => 'Mostrar segmentos',
    'fastestSeg' => 'Segmentos mais rápidos',
    'slowestSeg' => 'Segmentos mais lentos',
    'speedChart' => 'Gráfico de velocidade',
    'moreStats' => 'Mais estatísticas',
    'lines' => 'Linhas',
    'scoringPlaylist' => 'Reprodução de pontuação',
    'filterSP' => 'Filtrar reprodução de pontuação',
    'applyFilter' => 'Aplicar filtro',
    'timestamp' => 'Marcação de tempo',
    'action' => 'Ação', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Equivalente de pontuação',
    'position' => 'Posição', //position in a replay
    'lAVG' => 'Média local',
    'gAVG' => 'Média global',
    'repHelp' => 'Ajuda', //link that shows information how to use the tool
    'repExport' => 'GIF ou vídeo',
	
    /* PW change */
    'pwChange' => 'Alterar senha',
    'newPw' => 'Nova senha',
    'againPw' => 'Novamente',
    'applyChange' => 'Aplicar alterações',
    
    /* Localization settings */
    'localSettings' => 'Configurações de localização',
    'lang' => 'Idioma',
    'langNone' => 'Nenhum (selecionável no menu de cima)',
    'langDesc' => 'Selecione o idioma preferido.',
    'timezone' => 'Fuso horário',
    'timezoneDesc' => 'Usado para converter o horário para seu horário local.',
    'country' => 'País',
    'countryDesc' => 'Usado para exibir classificações por país.',
    'continent' => 'Continente',
	
    /* Profile */
    'ownProfile' => 'Este é seu perfil público acessível em',
    'bestTimes' => 'Melhores tempos',
    'allTimes' => 'Ver todos os tempos de maratona',
    'userImpr' => 'Ver estatísticas de progresso',
    'userRanking' => 'Estatísticas de ranking',
    'gameStats' => 'Estatísticas de jogo',
    'latestGames' => 'Jogos recentes',
    'noGames' => 'Este usuário não jogou nenhuma partida ainda.',
    'gamesPlayed' => 'Jogos',
    'totalTime' => 'Tempo total',
    'linesSent' => 'Linhas enviadas',
    'linesRec' => 'Linhas recebidas',
    'placedBlocks' => 'Blocos colocados',
    'blockCnt' => ':cnt blocos',
    'APM10Games' => 'APM em 10 jogos',
    'PPS10Games' => 'PPS em 10 jogos',
    'maxAPM' => 'APM Máx.',
    'maxREN' => 'Combo Máx.',
    'longestGame' => 'Jogo mais longo',
    'totalB2B' => 'Total de B2Bs',
    'mostSent' => 'Mais enviado',
    'hours' => 'horas',
    'minutes' => 'minutos',
    'createdMaps' => 'Mapas criados',
    'viewMapsBy' => 'Ver todos os mapas criados por',
    'playersCount' => 'Jogadores',
    'gameResultPosition' => 'Posição',
    'gameResultRoundTime' => 'Tempo de jogo',
    'viewAllGamesOf' => 'Ver todos os jogos de :mode',
    'noGamesOf' => ':name não jogou nenhum jogo de :mode ainda.',
    
	/* Maps */
    'map' => 'Mapa',
    'mapCreate' => 'Criar novo',
    'mapName' => 'Nome',
    'mapNameLong' => 'Nome do mapa',
    'mapDesc' => 'Descrição',
    'mapRules' => 'Regras',
    'mapOptions' => 'Opções',
    'mapPlay' => 'Jogar',
    'mapPlayLink' => 'Jogar Mapa',
    'mapAuthor' => 'Autor',
    'mapCreatedBy' => 'Criado por',
    'backToMaps' => 'Voltar para mapas',
    'playThisMap' => 'Jogar este map',
    'search' => 'Procurar',
    'myMaps' => 'Meus mapas',
    'mapsByUser' => 'Mapas de :name',
    'displayUnpublished' => 'Exibir :cnt mapas não publicados',
    'displayPublished' => 'Exibir :cnt mapas publicados',
    'usersMapMedals' => 'Medalhas de :name em mapas',
    'usersCompletedMaps' => 'Mapas completados por :name',
    'showRecords' => 'Mostrar recordes',
    'details' => 'Detalhes',
    'playedBy' => 'Jogado por',
    'latestMapGames' => 'Os últimos jogos de mapas',
	
    /* Stats */
    'improvementStats' => 'Estatísticas de progresso',
    //keep ':name'
    'improvementInfo' => 'O seguinte gráfico mostra o tempo de corrida da linha (eixo Y) contra a data de jogo (eixo X). A linha destacada mostra melhoras nos recordes pessoais de :name. Você pode colocar seu cursor sobre qualquer ponto para mostrar detalhes do jogo.',
    'date' => 'Data',
    'result' => 'Resultado',
    'submit' => 'Enviar',
    'qSettings' => 'Configurações de inquirimento',
    'dispAll' => 'Exibir todos os jogos',
    
    /* About */
    'aboutInfo' => 'Jstris é um jogo de blocos multijogador online simples feito em Javascript, HTML5 e Python (servidor).',
    'version' => 'Versão',
    'changelog' => 'Registro de mudanças',
    'discussion' => 'Discussão',
    'learnMore' => 'Saiba mais',
    'contact' => 'Contato',
    'serverCoverage' => 'Cobertura do custo do servidor',
    'supporters' => 'Apoiadores do projeto',
    'translators' => 'Tradutores',
    'moderators' => 'Moderadores',
    
    /* Other */
    'notFound' => 'Não encontrado.',
    'invalidLink' => 'O link solicitado é inválido.',
    'brb' => 'Já voltamos.',
    'tryAgain' => 'O site está sendo atualizado, por favor tente novamente em alguns instantes.',
    'wasteDesc' => 'Taxa de peças T não usadas em um T-Spin (para o total de peças T)',

    /* Settings - Other options */
    'setOther' => 'Outras opções',
    'hideAcc' => 'Conta oculta',
    'accVisibility' => 'Visibilidade',
    'hideAccInfo' => 'Ao habilitar, a conta será excluída das classificações públicas.',

    /* Chat reports */
    'reportU' => 'Denunciar usuário',
    'reportDesc' => ' Aqui você pode fazer uma denúncia se acha que um usuário quebrou as regras no chat.',
    'user' => 'Usuário',
    'reason' => 'Motivo',
    'rr0' => 'Spam ou divulgação inadequada',
    'rr1' => 'Conteúdo sexualmente explícito',
    'rr2' => 'Discurso de ódio',
    'rr3' => 'Assédio ou bullying',
    'rr4' => 'Outro (especifique)',
    'sendReport' => 'Enviar denúncia',
    
    /* Friends */
    'accept' => 'Aceitar',
    'ignore' => 'Ignorar',
    'pending' => 'Solicitações pendentes',
    'frFilter' => 'Filtrar nomes',
    'noPending' => 'No momento você não tem nenhuma solicitação de amizade.',
    'onlineNow' => 'Online agora',
    'recentlyAc' => 'Recentemente ativo',
    'lastActive' => 'Ativo :when',
    'noFriends' => 'No momento sua lista de amizade está vazia.',
    'ruSure' => 'Você tem certeza?',
    'rmFriend' => 'Você quer remover essa pessoa dos amigos?',
    'rmConfirm' => 'Sim, remova',
];
