<?php

return [
    'leaderboard' => '排行榜',
    'tournament' => '錦標賽',
    'maps' => '地圖',
    'mapsBrowse' => '瀏覽',
    'myMaps' => '我的地圖',
    'mapsDesigner' => '地圖創作工具',
    'randomMap' => '隨機地圖',
    'mapsLatestGames' => '最新遊戲',
    'guide' => '遊戲指南',
    'login' => '登入',
    'register' => '註冊',
    'myProfile' => '個人檔案',
    'myImprovement' => '個人進步史',
    'favReplays' => '已收藏重播',
    'friends' => '朋友',
    'settings' => '設定',
    'logout' => '登出',
    
    /* Leaderboard */
    'name' => '名字',
    'time' => '時間',
    'blocks' => '方塊',
    'PPS' => 'PPS',
    'finesse' => '多餘操作',
    'date' => '日期',
    'replay' => '重播',
    'place' => '排名',
    'nli' => '未登入！',
    'today' => '今日',
    'lastWeek' => '一週內',
    'lastMonth' => '一個月內',
    'lastYear' => '一年內',
    'allTime' => '全部',
    'bestPlayers' => '最佳玩家',
    'bestGames' => '最佳戰局',
    'bestSubs' => '~秒以下最佳玩家',
    'latestGames' => '最新戰局',
    'leastBlocks' => '最少方塊',
    'myTimes' => '我的紀錄',
    'perfectFinesse' => '無多餘操作',
    
    /* Replay */
    'load' => '讀取',
    'play' => '播放',
    'pause' => '暫停',
    'showSeg' => '顯示部分',
    'fastestSeg' => '最快部分',
    'slowestSeg' => '最慢部分',
    'speedChart' => '速度圖表',
    'moreStats' => '更多資料',
    'lines' => '行數',
    'scoringPlaylist' => '計分總覽',
    'filterSP' => '過濾計分',
    'applyFilter' => '套用過濾',
    'timestamp' => '時間戳記',
    'action' => '動作', // e.g. combo, tspin, perfect clear
    'scoreEq' => '得分',
    'position' => '目前時間', //position in a replay
    'lAVG' => '區間平均',
    'gAVG' => '全域平均',
    'repHelp' => '提示', //link that shows information how to use the tool
    'repExport' => 'GIF 或影片',
    
    /* PW change */
    'pwChange' => '變更密碼',
    'newPw' => '新密碼',
    'againPw' => '再確認',
    'applyChange' => '套用變更',
    'emailChange' => '變更電子郵件',
    'currentEmail' => '目前',
    'newEmail' => '新電子郵件',
    
    /* Localization settings */
    'localSettings' => '在地化設定',
    'lang' => '語言',
    'langNone' => '未選擇 (可於頂部選單選擇)',
    'langDesc' => '選擇偏好語言',
    'timezone' => '時區',
    'timezoneDesc' => '用於轉換至當地時間',
    'country' => '國家',
    'continent' => '洲',
    'countryDesc' => '用於顯示國家內排行',
    
    /* Profile */
    'ownProfile' => '以下網址為您的公開個人檔案',
    'bestTimes' => '最佳競速紀錄',
    'allTimes' => '查看所有 Sprint 的紀錄',
    'userImpr' => '查看進步史',
    'userRanking' => 'Ranking stats',
    'gameStats' => '遊玩紀錄',
    'latestGames' => '最新遊戲',
    'noGames' => '該玩家還沒加入過任何遊戲.',
    'gamesPlayed' => '遊玩回合數',
    'totalTime' => '總計時間',
    'linesSent' => '送出行數',
    'linesRec' => '接收行數',
    'placedBlocks' => '放置方塊總數',
    'blockCnt' => ':cnt 個',
    'APM10Games' => '近十局平均 APM',
    'PPS10Games' => '近十局平均 PPS',
    'maxAPM' => '最大 APM',
    'maxREN' => '最高 Combo',
    'longestGame' => '最久時間',
    'totalB2B' => '總計 B2B 數',
    'mostSent' => '最高送出',
    'hours' => '小時',
    'minutes' => '分鐘',
    'createdMaps' => '創立的地圖',
    'viewMapsBy' => '查看此玩家建立的所有地圖',
    'playersCount' => '玩家數',
    'gameResultPosition' => '排名',
    'gameResultRoundTime' => '遊戲時間',
    'viewAllGamesOf' => '查看:mode模式的所有遊戲',
    'noGamesOf' => ':name 尚未遊玩過:mode模式',
    
    /* Maps */
    'map' => '地圖',
    'mapCreate' => '建立',
    'mapName' => '名稱',
    'mapNameLong' => '地圖名稱',
    'mapDesc' => '描述',
    'mapRules' => '規則',
    'mapOptions' => '選項',
    'mapPlay' => '遊玩',
    'mapPlayLink' => '遊玩此地圖',
    'mapAuthor' => '作者',
    'mapCreatedBy' => '作者',
    'backToMaps' => '回到地圖列表',
    'playThisMap' => '遊玩此地圖',
    'search' => '搜尋',
    'myMaps' => '我的地圖',
    'mapsByUser' => ':name的地圖',
    'displayUnpublished' => '顯示 :cnt 個未發表地圖',
    'displayPublished' => '顯示 :cnt 個已發表地圖',
    'usersMapMedals' => ':name的獎章',
    'usersCompletedMaps' => ':name玩過的地圖',
    'showRecords' => '顯示紀錄',
    'details' => '詳細資訊',
    'playedBy' => '玩家:',
    'latestMapGames' => '地圖模式最新遊戲',
    
    /* Stats */
    'improvementStats' => '進步史',
    //keep ':name'
    'improvementInfo' => '以下的圖表顯示競速時間 (縱軸) 和 遊玩日期 (橫軸). 加亮處為 :name 刷新紀錄的地方. 你可將滑鼠指向該行以顯示更多資訊.',
    'date' => '日期',
    'result' => '結果',
    'submit' => '送出',
    'qSettings' => '篩選設定',
    'dispAll' => '查看所有遊戲',
    
    /* About */
    'aboutInfo' => 'Jstris 是一個以 Javascript, HTML5 和 Python (伺服器端) 所製作的簡單多人俄羅斯方塊。',
    'version' => '版本',
    'changelog' => '更新日誌',
    'discussion' => '討論版',
    'learnMore' => '了解更多',
    'contact' => '聯繫',
    'serverCoverage' => '伺服器花費涵蓋',
    'supporters' => '專案支持者',
    'translators' => '翻譯者',
    'moderators' => '管理員',
    
    /* Other */
    'notFound' => '找不到',
    'invalidLink' => '要求的連結無效',
    'brb' => '待會回來',
    'tryAgain' => '網站正在更新中, 等一回再回來吧',
    'wasteDesc' => 'T方塊未被使用於T-Spin的比率',
    
    /* Settings - Other options */
    'setOther' => '其他設定',
    'hideAcc' => '隱藏帳號',
    'accVisibility' => '可見度',
    'hideAccInfo' => '啟用後，帳號將從公開排行榜中排除。',

    /* Chat reports */
    'reportU' => '檢舉使用者',
    'reportDesc' => '如果您認為某人在濫用遊戲內聊天，您可以在此處回報。',
    'user' => '使用者',
    'reason' => '原因',
    'rr0' => '洗版或打廣告',
    'rr1' => '露骨內容',
    'rr2' => '仇恨言論',
    'rr3' => '騷擾或霸凌',
    'rr4' => '其他 (請說明)',
    'sendReport' => '傳送報告',
    
    /* Friends */
    'accept' => '接受',
    'ignore' => '忽略',
    'pending' => '待處理邀請',
    'frFilter' => '過濾名稱',
    'noPending' => '您目前沒有待處理的交友邀請。',
    'onlineNow' => '線上',
    'recentlyAc' => '最近上線',
    'lastActive' => '最後上線於 :when',
    'noFriends' => '您的朋友列表目前空空如也。',
    'ruSure' => '您確定嗎？',
    'rmFriend' => '您要將此使用者從您的朋友列表中移除嗎？',
    'rmConfirm' => '是的，請移除',
    
    /* Settings - Navigation */
    'setProfileNav' => '個人檔案',
    'setLocalizationNav' => '在地化',
    'setPasswordNav' => '密碼',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => '其他',

    /* Settings - Discord */
    'setDiscordTitle' => '連結 Discord',
    'disconnect' => '中斷連線',
    'connectDiscord' => '連結 Discord',

    /* Settings - Other */
    'setExperiments' => '實驗功能',
    'setExperimentsDesc' => '啟用實驗性/未完成功能的測試存取',
    'setExperimentsNote' => '在 Jstris 的 Discord 分享你的想法',
    'deleteAccount' => '刪除帳號',

    /* Settings - Supporter History */
    'returnBack' => '返回',
    'giftBalanceHistory' => '贈禮餘額歷史',
    'message' => '訊息',
    'change' => '變更',
    'before' => '之前',
    'after' => '之後',
    'relative' => '相對',
    'none' => '無',

    /* Settings - Supporter Status */
    'subscription' => '訂閱',
    'active' => '啟用中',
    'manage' => '管理',
    'renewsOn' => '續訂於：',
    'oneTime' => '一次性',
    'expires' => '到期',
    'extend' => '延長',
    'giftingBalance' => '贈禮餘額',
    'days' => '天',
    'add' => '新增',
    'useCode' => '使用代碼',
    'balanceHistory' => '餘額歷史',
    'noExpiration' => '不會過期',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => '上傳自訂圖片',
    'uploadCustomImageDesc' => '選擇作為 Jstris 公開頭像的圖片。如被檢舉為不當，可能會被移除。',
    'supporterOption' => 'Supporter 選項',
    'seeDetails' => '查看詳情',
    'uploadPreviewCrop' => '上傳以預覽與裁切',

    /* Settings - Profile */
    'remove' => '移除',
    'noImageSelected' => '尚未選擇圖片',
    'bioPlaceholder' => '輸入將顯示於您個人檔案的文字',
    'bioFormatInfo' => '可以這樣格式化超連結：[YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Supporter 帳號可使用格式、插入連結與表情',
    'selectProfileImage' => '選擇個人圖片',
    'jstrisBlocks' => 'Jstris 方塊',
    'animalArt' => '動物藝術',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris 無廣告且免費遊玩。透過支持可解鎖以下好處：',
    'benefitProfileCustomizations' => '個人檔案自訂',
    'benefitProfileCustomizationsDesc' => '可上傳自訂個人圖片，並在「關於」訊息中使用進階格式（最多 2000 字、可用連結與表情）。',
    'benefitSaveMatchesBots' => '儲存對機器人的對戰',
    'benefitSaveMatchesBotsDesc' => '你與機器人的 1v1 將儲存於結果中，包含重播與進階統計。',
    'benefitUnlimitedReplays' => '重播無上限',
    'benefitUnlimitedReplaysDesc' => 'Supporter 期間內，你的單人模式重播不會被刪除。',
    'getSupporterCta' => '取得 Jstris Supporter！',
    'configureBenefits' => '設定好處',
    'nameChange' => '更改名稱',
    'nameChangeInfo' => '身為 Supporter，每月可更改一次名稱。於此更改：',
    'newNameLabel' => '新名稱',
    'newNamePlaceholder' => '輸入新使用者名稱',
    'manageSubscriptionTitle' => '管理 Jstris 訂閱',
    'manageSubscriptionInfo1' => '若要暫停或取消，請登入 PayPal 並在訂閱面板選擇相應選項。',
    'manageSubscriptionInfo2' => '若有任何問題，歡迎聯繫 jstris@jezevec10.com。',
    'close' => '關閉',
];
