<?php

return [
    'leaderboard' => '排行榜',
    'tournament' => '錦標賽',
    'maps' => '地圖',
    'mapsBrowse' => '瀏覽',
    'myMaps' => '我的地圖',
    'mapsDesigner' => '地圖創作工具',
    'randomMap' => '隨機地圖',
    'mapsLatestGames' => '最新遊戲',
    'guide' => '遊戲指南',
    'login' => '登入',
    'register' => '註冊',
    'myProfile' => '個人檔案',
    'myImprovement' => '個人進步史',
    'favReplays' => '已收藏重播',
    'settings' => '設定',
    'logout' => '登出',
    
    /* Leaderboard */
    'name' => '名字',
    'time' => '時間',
    'blocks' => '方塊',
    'PPS' => 'PPS',
    'finesse' => '多餘操作',
    'date' => '日期',
    'replay' => '重播',
    'place' => '排名',
    'nli' => '未登入!',
    'today' => '今日',
    'lastWeek' => '一週內',
    'lastMonth' => '一個月內',
    'lastYear' => '一年內',
    'allTime' => '全部',
    'bestPlayers' => '最佳玩家',
    'bestGames' => '最佳戰局',
    'bestSubs' => '~秒以下最佳玩家',
    'latestGames' => '最新戰局',
    'leastBlocks' => '最少方塊',
    'myTimes' => '我的紀錄',
    'perfectFinesse' => '無多餘操作',
    
    /* Replay */
    'load' => '讀取',
    'play' => '播放',
    'pause' => '暫停',
    'showSeg' => '顯示部分',
    'fastestSeg' => '最快部分',
    'slowestSeg' => '最慢部分',
    'speedChart' => '速度圖表',
    'moreStats' => '更多資料',
    'lines' => '行數',
    'scoringPlaylist' => '計分總覽',
    'filterSP' => '過濾計分',
    'applyFilter' => '套用過濾',
    'timestamp' => '時間戳記',
    'action' => '動作', // e.g. combo, tspin, perfect clear
    'scoreEq' => '得分',
    'position' => '目前時間', //position in a replay
    'lAVG' => '區間平均',
    'gAVG' => '全域平均',
    'repHelp' => '提示', //link that shows information how to use the tool
    'repExport' => 'GIF 或影片',
    
    /* PW change */
    'pwChange' => '變更密碼',
    'newPw' => '新密碼',
    'againPw' => '再確認',
    'applyChange' => '套用變更',
    
    /* Localization settings */
    'localSettings' => '在地化設定',
    'lang' => '語言',
    'langNone' => '未選擇 (可於頂部選單選擇)',
    'langDesc' => '選擇偏好語言',
    'timezone' => '時區',
    'timezoneDesc' => '用於轉換至當地時間',
    'country' => '國家',
    'continent' => '洲',
    'countryDesc' => '用於顯示國家內排行',
    
    /* Profile */
    'ownProfile' => '以下網址為你公開的個人檔案',
    'bestTimes' => '最佳競速紀錄',
    'allTimes' => '查看所有 Sprint 的紀錄',
    'userImpr' => '查看進步史',
    'gameStats' => '遊玩紀錄',
    'latestGames' => '最新遊戲',
    'noGames' => '該玩家還沒加入過任何遊戲.',
    'gamesPlayed' => '遊玩回合數',
    'totalTime' => '總計時間',
    'linesSent' => '送出行數',
    'linesRec' => '接收行數',
    'placedBlocks' => '放置方塊總數',
    'blockCnt' => ':cnt 個',
    'APM10Games' => '近十局平均 APM',
    'PPS10Games' => '近十局平均 PPS',
    'maxAPM' => '最大 APM',
    'maxREN' => '最高 Combo',
    'longestGame' => '最久時間',
    'totalB2B' => '總計 B2B 數',
    'mostSent' => '最高送出',
    'hours' => '小時',
    'minutes' => '分鐘',
    'createdMaps' => '創立的地圖',
    'viewMapsBy' => '察看此玩家建立的所有地圖',
    'playersCount' => '玩家數',
    'gameResultPosition' => '排名',
    'gameResultRoundTime' => '遊戲時間',
    'viewAllGamesOf' => '察看:mode模式的所有遊戲',
    'noGamesOf' => ':name 尚未遊玩過:mode模式',
    
    /* Maps */
    'map' => '地圖',
    'mapCreate' => '建立',
    'mapName' => '名稱',
    'mapNameLong' => '地圖名稱',
    'mapDesc' => '描述',
    'mapRules' => '規則',
    'mapOptions' => '選項',
    'mapPlay' => '遊玩',
    'mapPlayLink' => '遊玩此地圖',
    'mapAuthor' => '作者',
    'mapCreatedBy' => '作者',
    'backToMaps' => '回到地圖列表',
    'playThisMap' => '遊玩此地圖',
    'search' => '搜尋',
    'myMaps' => '我的地圖',
    'mapsByUser' => ':name的地圖',
    'displayUnpublished' => '顯示 :cnt 個未發表地圖',
    'displayPublished' => '顯示 :cnt 個已發表地圖',
    'usersMapMedals' => ':name的獎章',
    'usersCompletedMaps' => ':name玩過的地圖',
    'showRecords' => '顯示紀錄',
    'details' => '詳細資訊',
    'playedBy' => '玩家:',
    'latestMapGames' => '地圖模式最新遊戲',
    
    /* Stats */
    'improvementStats' => '進步史',
    //keep ':name'
    'improvementInfo' => '以下的圖表顯示競速時間 (縱軸) 和 遊玩日期(橫軸). 加亮處為 :name 刷新紀錄的地方. 你可將滑鼠指向該行以顯示更多資訊.',
    'date' => '日期',
    'result' => '結果',
    'submit' => '送出',
    'qSettings' => '篩選設定',
    'dispAll' => '查看所有遊戲',
    
    /* About */
    'aboutInfo' => 'Jstris 是一個以Javascript, HTML5 和 Python (伺服器端)所製作的簡單多人俄羅斯方塊.',
    'version' => '版本',
    'changelog' => '更新日誌',
    'discussion' => '討論版',
    'learnMore' => '了解更多',
    'contact' => '聯繫',
    'serverCoverage' => '伺服器花費涵蓋',
    'supporters' => '專案支持者',
    'translators' => '翻譯者',
    'moderators' => '管理員',
    
    /* Other */
    'notFound' => '找不到',
    'invalidLink' => '要求的連結無效',
    'brb' => '待會回來',
    'tryAgain' => '網站正在更新中, 等一回再回來吧',
];
