<?php

return [
    'leaderboard' => 'Leaderboard',
    'tournament' => 'Tournament',
    'maps' => 'Mga Mapa',
    'mapsBrowse' => 'Browse',
    'myMaps' => 'Aking mga Mapa',
    'mapsDesigner' => 'Map Designer',
    'randomMap' => 'Random na Mapa',
    'mapsLatestGames' => 'Latest games',
    'guide' => 'Patnubay',
    'login' => 'Mag-login',
    'register' => 'Mag Register',
    'myProfile' => 'Aking Profile',
    'myImprovement' => 'Aking pag-unlad',
    'favReplays' => 'Paboritong replays',
    'friends' => 'Mga Kaibigan',
    'settings' => 'Mga Settings',
    'logout' => 'Mag-logout',
    
    /* Leaderboard */
    'name' => 'Pangalang',
    'time' => 'Oras',
    'blocks' => 'Bloke',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Petsa',
    'replay' => 'Replay',
    'place' => 'Puwesto',
    'nli' => 'Hindi naka log-in!',
    'today' => 'Ngayong araw',
    'lastWeek' => 'Huling linggo',
    'lastMonth' => 'Huling buwan',
    'lastYear' => 'Huling taon',
    'allTime' => 'Lahat ng oras',
    'bestPlayers' => 'Best players',
    'bestGames' => 'Best games',
    'bestSubs' => 'Best subs',
    'latestGames' => 'Latest games',
    'leastBlocks' => 'The least blocks',
    'myTimes' => 'My times',
    'perfectFinesse' => '0 finesse',
    'mostGames' => 'The most games',
    
    /* Replay */
    'load' => 'I-Load',
    'play' => 'I-Play',
    'pause' => 'I-Pause',
    'showSeg' => 'Ipakita ang segment',
    'fastestSeg' => 'Pinaka-mabilis na mga segment',
    'slowestSeg' => 'Pinaka-mabagal na segments',
    'speedChart' => 'Speed chart',
    'moreStats' => 'Iba pang stats',
    'lines' => 'Linya',
    'scoringPlaylist' => 'Scoring playlist',
    'filterSP' => 'Filter scoring playlist',
    'applyFilter' => 'Apply filter',
    'timestamp' => 'Timestamp',
    'action' => 'Action', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Score equivalent',
    'position' => 'Position', //position in a replay
    'lAVG' => 'Local average',
    'gAVG' => 'Global average',
    'repHelp' => 'Help', //link that shows information how to use the tool
    'repExport' => 'GIF or video',
    
    /* PW change */
    'pwChange' => 'Baguhin ang password',
    'newPw' => 'Bagong password',
    'againPw' => 'Ulitin',
    'applyChange' => 'Ilapat ang pagbabago',
    
    /* Localization settings */
    'localSettings' => 'Settings ng lokalisasyon',
    'lang' => 'Wika',
    'langNone' => 'None (selectable in the top menu)',
    'langDesc' => 'Piliin ang iyong nais na Wika.',
    'timezone' => 'Timezone',
    'timezoneDesc' => 'Ginagamit para i-convert ang oras sa iyong lokas na oras.',
    'country' => 'Bansa',
    'continent' => 'Kontinente',
    'countryDesc' => 'Ginagamit para ipakita ang leaderboards sa bawat continente.',
    
    /* Profile */
    'ownProfile' => 'This is your public profile accessible at',
    'bestTimes' => 'Best times',
    'allTimes' => 'View all sprint times',
    'userImpr' => 'Improvement stats',
    'userRanking' => 'Ranking stats',
    'gameStats' => 'Game stats',
    'latestGames' => 'Latest games',
    'noGames' => 'This user has not played any games yet.',
    'gamesPlayed' => 'Games',
    'totalTime' => 'Total time',
    'linesSent' => 'Lines sent',
    'linesRec' => 'Lines received',
    'placedBlocks' => 'Placed blocks',
    'blockCnt' => ':cnt blocks',
    'APM10Games' => '10-games APM',
    'PPS10Games' => '10-games PPS',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Combo',
    'longestGame' => 'Longest game',
    'totalB2B' => 'Total B2Bs',
    'mostSent' => 'Most sent',
    'hours' => 'hours',
    'minutes' => 'minutes',
    'createdMaps' => 'Created maps',
    'viewMapsBy' => 'View all maps created by',
    'playersCount' => 'Players',
    'gameResultPosition' => 'Position',
    'gameResultRoundTime' => 'Gametime',
    'viewAllGamesOf' => 'All games of :mode',
    'noGamesOf' => ':name hasn\'t played any games of :mode yet.',
    
    /* Maps */
    'map' => 'Map',
    'mapCreate' => 'Create new',
    'mapName' => 'Name',
    'mapNameLong' => 'Map name',
    'mapDesc' => 'Description',
    'mapRules' => 'Rules',
    'mapOptions' => 'Options',
    'mapPlay' => 'Play',
    'mapPlayLink' => 'Play Map',
    'mapAuthor' => 'Author',
    'mapCreatedBy' => 'Created by',
    'backToMaps' => 'Back to maps',
    'playThisMap' => 'Play this map',
    'search' => 'Search',
    'myMaps' => 'My maps',
    'mapsByUser' => ':name\'s maps',
    'displayUnpublished' => 'Display :cnt unpublished maps',
    'displayPublished' => 'Display :cnt published maps',
    'usersMapMedals' => ':name\'s map medals',
    'usersCompletedMaps' => ':name\'s completed maps',
    'showRecords' => 'Show records',
    'details' => 'Details',
    'playedBy' => 'Played by',
    'latestMapGames' => 'The latest map games',

    /* Stats */
    'improvementStats' => 'Improvement stats',
    //keep ':name'
    'improvementInfo' => 'The following graph shows line race time (Y axis) vs game date (X axis). Highlighted line shows improvements in :name\'s personal records. You can place your cursor over any point to show the game details.',
    'date' => 'Date',
    'result' => 'Result',
    'submit' => 'Submit',
    'qSettings' => 'Query settings',
    'dispAll' => 'Display all games',
    
    /* About */
    'aboutInfo' => 'Jstris is a simple online multiplayer block game built in Javascript, HTML5 and Python (server).',
    'version' => 'Version',
    'changelog' => 'Changelog',
    'discussion' => 'Discussion',
    'learnMore' => 'Learn more',
    'contact' => 'Contact',
    'serverCoverage' => 'Server cost coverage',
    'supporters' => 'Project supporters',
    'translators' => 'Mga tagapagsaling-wika',
    'moderators' => 'Mga moderator',
    
    /* Other */
    'notFound' => 'Hindi nakita.',
    'invalidLink' => 'Hindi wasto ang ni-request na link.',
    'brb' => 'Magbabalik ng ilang sandali.',
    'tryAgain' => 'Ang website ay kasalukuyang in-uupdate. Maghintay ng ilang minuto.',
    'wasteDesc' => 'Ratio of T pieces not used in a T-Spin (to total T pieces)',

    /* Settings - Other options */
    'setOther' => 'Ibang options',
    'hideAcc' => 'Nakatagong account',
    'accVisibility' => 'Visibility',
    'hideAccInfo' => 'Kung bukas, ang iyong account ay hindi malilista sa mga leaderboards.',

    /* Chat reports */
    'reportU' => 'I-report ang user',
    'reportDesc' => ' Here you can create a report if you think someone has abused the game chat.',
    'user' => 'User',
    'reason' => 'Rason',
    'rr0' => 'Spam o hindi ninanais na pang-aadvertising',
    'rr1' => 'Mga nilalama na tahasang sekswal',
    'rr2' => 'Mapupuoot na salita',
    'rr3' => 'Panliligalig o pambu-bully',
    'rr4' => 'Other (specify)',
    'sendReport' => 'I-send ang report',
    
    /* Friends */
    'accept' => 'I-Accept',
    'ignore' => 'I-ignore',
    'pending' => 'Pending na Requests',
    'frFilter' => 'I-filter ang mga pangalan',
    'noPending' => 'Wala kang friend requests sa kasalukuyan.',
    'onlineNow' => 'Online ngayon',
    'recentlyAc' => 'Aktibo kailanmn',
    'lastActive' => 'Aktibo :noong',
    'noFriends' => 'At the moment your friend list is empty.',
    'ruSure' => 'Sigurado?',
    'rmFriend' => 'Nais mo bang tanggalin ang user na ito sa iyong friends list?',
    'rmConfirm' => 'Oo, tanggalin',
];
