<?php
return [
    'leaderboard' => 'Classement',
    'tournament' => 'Tournoi',
    'login' => 'Connexion',
    'register' => 'Inscription',
    'myProfile' => 'Mon profil',
    'myImprovement' => 'Ma progression',
    'settings' => 'Options',
    'logout' => 'Déconnexion',
    'favReplays' => 'Replays favoris',
    'mapsLatestGames' => 'Dernières parties',
    'randomMap' => 'Carte aléatoire',
    'mapsBrowse' => 'Parcourir',
    'maps' => 'Cartes',
    'guide' => 'Guide',

    /* Leaderboard */
    'name' => 'Nom',
    'time' => 'Temps',
    'blocks' => 'Blocs',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Date',
    'replay' => 'Revoir',
    'place' => 'Place',
    'nli' => 'Pas connecté!',
    'today' => 'Aujourd\'hui',
    'lastWeek' => 'Cette semaine',
    'lastMonth' => 'Ce mois-ci',
    'lastYear' => 'Cette année',
    'allTime' => 'Depuis toujours',
    'bestPlayers' => 'Meilleurs joueurs',
    'bestGames' => 'Meilleures parties',
    'bestSubs' => 'Intervalle spécifique',
    'latestGames' => 'Dernières parties',
    'leastBlocks' => 'Le moins de blocs',
    'myTimes' => 'Mes temps',

    /* Replay */
    'load' => 'Charger',
    'play' => 'Lecture',
    'pause' => 'Pause',
    'showSeg' => 'Afficher les segments',
    'fastestSeg' => 'Meilleurs segments',
    'slowestSeg' => 'Moins bons segments',
    'speedChart' => 'Graphe de vitesse',
    'moreStats' => 'Plus de stats',
    'applyFilter' => 'Appliquer le filtre',
    'scoreEq' => 'Score équivalent',
    'repHelp' => 'Aide', //link that shows information how to use the tool
    'repExport' => 'GIF ou vidéo',

    /* PW change */
    'pwChange' => 'Changer de mot de passe',
    'newPw' => 'Nouveau mot de passe',
    'againPw' => 'Répéter le mot de passe',
    'applyChange' => 'Mettre à jour',

    /* Localization settings */
    'localSettings' => 'Paramètres de localisation',
    'lang' => 'Langue',
    'country' => 'Pays',

    /* Profile */
    'ownProfile' => 'Ceci est votre profil public, accessible à l\'adresse',
    'bestTimes' => 'Meilleurs temps',
    'allTimes' => 'Voir tous les temps de sprint',
    'userImpr' => 'Voir les statistiques de progression',
    'gameStats' => 'Statistiques de jeu',
    'latestGames' => 'Dernières parties',
    'noGames' => 'Ce joueur n\'a pas encore joué de partie.',
    'gamesPlayed' => 'Parties',
    'totalTime' => 'Temps de jeu',
    'linesSent' => 'Lignes envoyées',
    'linesRec' => 'Lignes reçues',
    'placedBlocks' => 'Blocs placés',
    'maxAPM' => 'APM max.',
    'maxREN' => 'Combo max.',
    'longestGame' => 'Plus longue partie',
    'totalB2B' => 'Total de B2Bs',
    'mostSent' => 'Max. d\'envoyé',
    'hours' => 'heures',
    'minutes' => 'minutes',
    'viewAllGamesOf' => 'Voir toutes les parties du mode de jeu :mode',
    'noGamesOf' => ':name n\'a encore jamais joué dans le mode de jeu :mode.',
    'createdMaps' => 'Création de cartes',
    'playersCount' => 'Joueurs',
    'gameResultPosition' => 'Position',
    'gameResultRoundTime' => 'Temps de jeu',
    'blockCnt' => ':cnt blocs',

    /* Maps */
    'map' => 'Carte',
    'mapCreate' => 'Créer une nouvelle carte',
    'mapName' => 'Nom',
    'mapNameLong' => 'Nom de la carte',
    'mapDesc' => 'Description',
    'mapRules' => 'Régle',
    'mapOptions' => 'Options',
    'mapPlay' => 'Jouer',
    'mapAuthor' => 'Auteur',
    'mapCreatedBy' => 'Créé par',
    'playThisMap' => 'Jouer cette carte',
    'search' => 'Rechercher',
    'myMaps' => 'Mes cartes',
    'showRecords' => 'Voir les records',
    'details' => 'Détails',
    'playedBy' => 'Joué par',
    'latestMapGames' => 'La dernière carte joué',

    /* Stats */
    'improvementStats' => 'Statistiques de progression',
    //keep ':name'
    'improvementInfo' => 'Le graphe ci-dessous montre les temps de sprint (axe des ordonnées) en fonction de leur date (axe des abscisses). La ligne surlignée montre l\'évolution du record personnel de :name. Passez votre souris sur un point pour afficher les détails du sprint correspondant.',
    'date' => 'Date',
    'result' => 'Résultat',
    'submit' => 'Afficher',
    'qSettings' => 'Afficher un autre graphe',
    'dispAll' => 'Afficher toutes les parties',

    /* About */
    'aboutInfo' => 'Jstris est un jeu multijoueur en ligne simple d\'empilement de blocs codé en Javascript, HTML5, et Python (côté serveur).',
    'version' => 'Version',
    'discussion' => 'Discussion',
    'learnMore' => 'En savoir plus',
    'contact' => 'Contact',
    'serverCoverage' => 'Frais d\'hébergement du site',
    'supporters' => 'Donateurs',
    'moderators' => 'Modérateurs',
    'translators' => 'Traducteurs',
    'changelog' => 'Notes de mise à jour',

    /* Other */
    'notFound' => 'Introuvable.',
    'invalidLink' => 'Le lien entré n\'est pas valide.',
    'brb' => 'Je reviens tout de suite.',
    'tryAgain' => 'Le site est en cours de mise à jour, merci de réessayer ultérieurement.',
];
