<?php

return [
    'leaderboard' => 'Classement',
    'tournament' => 'Tournoi',
    'maps' => 'Cartes',
    'mapsBrowse' => 'Parcourir',
    'mapsDesigner' => 'Créateur de cartes',
    'randomMap' => 'Carte aléatoire',
    'mapsLatestGames' => 'Dernières parties',
    'guide' => 'Guide',
    'login' => 'Connexion',
    'register' => 'Inscription',
    'myProfile' => 'Mon profil',
    'myImprovement' => 'Ma progression',
    'favReplays' => 'Replays favoris',
    'friends' => 'Amis',
    'settings' => 'Options',
    'logout' => 'Déconnexion',

    /* Leaderboard */
    'name' => 'Nom',
    'time' => 'Temps',
    'blocks' => 'Blocs',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'replay' => 'Revoir',
    'place' => 'Place',
    'nli' => 'Pas connecté!',
    'today' => 'Aujourd\'hui',
    'lastWeek' => 'Cette semaine',
    'lastMonth' => 'Ce mois-ci',
    'lastYear' => 'Cette année',
    'allTime' => 'Depuis toujours',
    'bestPlayers' => 'Meilleurs joueurs',
    'bestGames' => 'Meilleures parties',
    'bestSubs' => 'Intervalle spécifique',
    'leastBlocks' => 'Le moins de blocs',
    'myTimes' => 'Mes temps',
    'perfectFinesse' => '0 finesse',
    'mostGames' => 'le plus de parties',

    /* Replay */
    'load' => 'Charger',
    'play' => 'Lecture',
    'pause' => 'Pause',
    'showSeg' => 'Afficher les segments',
    'fastestSeg' => 'Meilleurs segments',
    'slowestSeg' => 'Moins bons segments',
    'speedChart' => 'Graphe de vitesse',
    'moreStats' => 'Plus de stats',
    'lines' => 'Lignes',
    'scoringPlaylist' => 'Playlist des scores',
    'applyFilter' => 'Appliquer le filtre',
    'timestamp' => 'Moment',
    'action' => 'Action',
    'scoreEq' => 'Score équivalent',
    'position' => 'Position',
    'lAVG' => 'Moyenne locale',
    'gAVG' => 'Moyenne mondiale',
    'repHelp' => 'Aide', //link that shows information how to use the tool
    'repExport' => 'GIF ou vidéo',
    'filterSP' => 'Filtrer la playlist scores',

    /* PW change */
    'pwChange' => 'Changer de mot de passe',
    'newPw' => 'Nouveau mot de passe',
    'againPw' => 'Répéter le mot de passe',
    'applyChange' => 'Mettre à jour',
    'emailChange' => 'Changer d\'e-mail',
    'currentEmail' => 'Actuel',
    'newEmail' => 'Nouvel e-mail',

    /* Localization settings */
    'localSettings' => 'Paramètres de localisation',
    'lang' => 'Langue',
    'langNone' => 'Aucun (selectionnable dans le menu en haut',
    'langDesc' => 'Selectionnez votre langue préférée.',
    'timezone' => 'Fuseau horaire',
    'timezoneDesc' => 'Utilisé pour afficher les heures en heure locale.',
    'country' => 'Pays',
    'continent' => 'Continent',
    'countryDesc' => 'Utilisé pour montrer les classements par pays',

    /* Profile */
    'ownProfile' => 'Ceci est votre profil public, accessible à l\'adresse',
    'bestTimes' => 'Meilleurs temps',
    'allTimes' => 'Voir tous les temps de sprint',
    'userImpr' => 'Voir les statistiques de progression',
    'userRanking' => 'Statistiques de vos rangs',
    'gameStats' => 'Statistiques de jeu',
    'latestGames' => 'Dernières parties',
    'noGames' => 'Ce joueur n\'a pas encore joué de partie.',
    'gamesPlayed' => 'Parties',
    'totalTime' => 'Temps de jeu',
    'linesSent' => 'Lignes envoyées',
    'linesRec' => 'Lignes reçues',
    'placedBlocks' => 'Blocs placés',
    'APM10Games' => 'APM sur 10 parties',
    'PPS10Games' => 'PPS sur 10 parties',
    'maxAPM' => 'APM max.',
    'maxREN' => 'Combo max.',
    'longestGame' => 'Plus longue partie',
    'totalB2B' => 'Total de B2Bs',
    'mostSent' => 'Max. d\'envoyé',
    'hours' => 'heures',
    'minutes' => 'minutes',
    'viewAllGamesOf' => 'Voir toutes les parties du mode de jeu :mode',
    'noGamesOf' => ':name n\'a encore jamais joué dans le mode de jeu :mode.',
    'createdMaps' => 'Création de cartes',
    'playersCount' => 'Joueurs',
    'gameResultPosition' => 'Position',
    'gameResultRoundTime' => 'Temps de jeu',
    'blockCnt' => ':cnt blocs',

    /* Maps */
    'map' => 'Carte',
    'mapCreate' => 'Créer une nouvelle carte',
    'mapName' => 'Nom',
    'mapNameLong' => 'Nom de la carte',
    'mapDesc' => 'Description',
    'mapRules' => 'Règles',
    'mapOptions' => 'Options',
    'mapPlay' => 'Jouer',
    'mapPlayLink' => 'Jouer la carte',
    'mapAuthor' => 'Auteur',
    'mapCreatedBy' => 'Créé par',
    'backToMaps' => 'retourner aux cartes',
    'playThisMap' => 'Jouer cette carte',
    'search' => 'Rechercher',
    'myMaps' => 'Mes cartes',
    'mapsByUser' => 'cartes de :name',
    'displayUnpublished' => 'Montrer :cnt cartes non publiées',
    'displayPublished' => 'Montrer :cnt cartes publiées',
    'usersMapMedals' => 'Médailles de :name',
    'usersCompletedMaps' => 'Cartes complétées de :name',
    'showRecords' => 'Voir les records',
    'details' => 'Détails',
    'playedBy' => 'Joué par',
    'latestMapGames' => 'La dernière carte jouée',
    'viewMapsBy' => 'Voir toutes les cartes créés par',

    /* Stats */
    'improvementStats' => 'Statistiques de progression',
    //keep ':name'
    'improvementInfo' => 'Le graphe ci-dessous montre les temps de sprint (axe des ordonnées) en fonction de leur date (axe des abscisses). La ligne surlignée montre l\'évolution du record personnel de :name. Passez votre souris sur un point pour afficher les détails du sprint correspondant.',
    'date' => 'Date',
    'result' => 'Résultat',
    'submit' => 'Afficher',
    'qSettings' => 'Afficher un autre graphe',
    'dispAll' => 'Afficher toutes les parties',

    /* About */
    'aboutInfo' => 'Jstris est un jeu multijoueur en ligne d\'empilement de blocs codé en Javascript, HTML5, et Python (côté serveur).',
    'version' => 'Version',
    'changelog' => 'Notes de mises à jour',
    'discussion' => 'Discussion',
    'learnMore' => 'En savoir plus',
    'contact' => 'Contact',
    'serverCoverage' => 'Frais d\'hébergement du site',
    'supporters' => 'Donateurs',
    'moderators' => 'Modérateurs',
    'translators' => 'Traducteurs',

    /* Other */
    'notFound' => 'Introuvable.',
    'invalidLink' => 'Le lien entré n\'est pas valide.',
    'brb' => 'Je reviens tout de suite.',
    'tryAgain' => 'Le site est en cours de mise à jour, merci de réessayer ultérieurement.',
    'wasteDesc' => 'Rapport de pièces T qui n\'ont pas été utilisées dans un T-Spin (par rapport au nombre total de T)',

    /* Settings - Other options */
    'setOther' => 'Autres options',
    'hideAcc' => 'Comptes cachés',
    'accVisibility' => 'Visibilité',
    'hideAccInfo' => 'Si activé, le compte sera exclu des classements publiques',

    /* Chat reports */
    'reportU' => 'Signaler l\'utilisateur',
    'reportDesc' => 'Ici vous pouvez signaler un utilisateur dans le chat.',
    'user' => 'Utilisateur',
    'reason' => 'Raison',
    'rr0' => 'Spam ou publicité',
    'rr1' => 'Images pornographiques explicites',
    'rr2' => 'Discours haineux',
    'rr3' => 'Harcèlement ou intimidation',
    'rr4' => 'Autre (spécifier)',
    'sendReport' => 'Envoyer le rapport',

    /* Friends */
    'accept' => 'Accepter',
    'ignore' => 'Ignorer',
    'pending' => 'Requêtes en suspens',
    'frFilter' => 'Filtrer les noms',
    'noPending' => 'Vous n\'avez actuellement aucune demande d\'ami en attente.',
    'onlineNow' => 'En ligne actuellement',
    'recentlyAc' => 'Actif(s) récemment',
    'lastActive' => 'Dernière activité :when',
    'noFriends' => 'Votre liste d\'amis est vide.',
    'ruSure' => 'Êtes-vous sûr?',
    'rmFriend' => 'Êtes-vous sûr de vouloir retirer cette personne de votre liste d\'amis?',
    'rmConfirm' => 'Oui, retirer',
];
