<?php

return [
    'leaderboard' => 'Topplista',
    'tournament' => 'Turnering',
    'maps' => 'banor',
    'mapsBrowse' => 'Bläddra',
    'myMaps' => 'Mina banor',
    'mapsDesigner' => 'Kart Redigerare',
    'randomMap' => 'Slumpmässig bana',
    'mapsLatestGames' => 'Senaste spel',
    'guide' => 'Guide',
    'login' => 'Logga in',
    'register' => 'Registrera',
    'myProfile' => 'Min profil',
    'myImprovement' => 'Mina förbättringar',
    'favReplays' => 'Favorit inspelningar',
    'settings' => 'Inställningar',
    'logout' => 'Logga ut',
    
    /* Leaderboard */
    'name' => 'Namn',
    'time' => 'Tid',
    'blocks' => 'Block',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Datum',
    'replay' => 'Inspelning',
    'place' => 'Placerat',
    'nli' => 'Inte inloggad!',
    'today' => 'Idag',
    'lastWeek' => 'Senaste Veckan',
    'lastMonth' => 'Senaste Månaden',
    'lastYear' => 'Senaste Året',
    'allTime' => 'Föralltid',
    'bestPlayers' => 'Bästa spelarna',
    'bestGames' => 'Bästa spelen',
    'bestSubs' => 'Bästa subs',
    'latestGames' => 'Senaste spelen',
    'leastBlocks' => 'Det minsta antalet block',
    'myTimes' => 'Mina Tider',
    'perfectFinesse' => '0 finesse',
    
    /* Replay */
    'load' => 'Ladda',
    'play' => 'Spela',
    'pause' => 'Pausa',
    'showSeg' => 'Visa segment',
    'fastestSeg' => 'Snabbaste segment',
    'slowestSeg' => 'Långsammaste segment',
    'speedChart' => 'Hastighetsdiagram',
    'moreStats' => 'Mer Statistik',
    'lines' => 'Linjer',
    'scoringPlaylist' => 'Scoring playlist',
    'filterSP' => 'Filtrera scoring playlist',
    'applyFilter' => 'Tillämpa filter',
    'timestamp' => 'Tidstämpel',
    'action' => 'Handling', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Poäng motsvarighet',
    'position' => 'Position', //position in a replay
    'lAVG' => 'Lokalt genomsnitt',
    'gAVG' => 'Globalt genomsnitt',
    'repHelp' => 'Hjälp', //link that shows information how to use the tool
    'repExport' => 'GIF eller video',
    
    /* PW change */
    'pwChange' => 'Ändra Lösenord',
    'newPw' => 'Nytt Lösenord',
    'againPw' => 'Igen',
    'applyChange' => 'Tillämpa ändring',
    
    /* Localization settings */
    'localSettings' => 'Lokaliserings inställningar',
    'lang' => 'Språk',
    'langNone' => 'Inget (väljbart i topp menyn)',
    'langDesc' => 'Välj önskat språk.',
    'timezone' => 'Tidszon',
    'timezoneDesc' => 'Används för att konvertera tid till din lokala tid.',
    'country' => 'Land',
    'continent' => 'Kontinent',
    'countryDesc' => 'Används för att visa nationella topplistor.',
    
    /* Profile */
    'ownProfile' => 'Det här är din offentliga profil tillgänglig på',
    'bestTimes' => 'Bästa tider',
    'allTimes' => 'Visa alla spurt tider',
    'userImpr' => 'Visa förrbättrings statistik',
    'gameStats' => 'Spel statistik',
    'latestGames' => 'Senaste spel',
    'noGames' => 'Den här spelaren har inte spelat några spel ännu.',
    'gamesPlayed' => 'Spel',
    'totalTime' => 'Total tid',
    'linesSent' => 'Linjer skickade',
    'linesRec' => 'Linjer mottagna',
    'placedBlocks' => 'Placerade block',
    'blockCnt' => ':cnt blocks',
    'APM10Games' => '10-spel APM',
    'PPS10Games' => '10-spel PPS',
    'maxAPM' => 'Max. APM',
    'maxREN' => 'Max. Kombo',
    'longestGame' => 'Längsta spel',
    'totalB2B' => 'Totala B2Bs',
    'mostSent' => 'Mest skickade',
    'hours' => 'timmar',
    'minutes' => 'minuter',
    'createdMaps' => 'Skapade banor',
    'viewMapsBy' => 'Se alla banor skapade av',
    'playersCount' => 'Spelare',
    'gameResultPosition' => 'Position',
    'gameResultRoundTime' => 'Speltid',
    'viewAllGamesOf' => 'Se alla spel av :mode',
    'noGamesOf' => ':name har inte spelat ett spel av :mode ännu.',
    
    /* Maps */
    'map' => 'Bana',
    'mapCreate' => 'Skapa ny',
    'mapName' => 'Namn',
    'mapNameLong' => 'Ban-namn',
    'mapDesc' => 'Beskrivning',
    'mapRules' => 'Regler',
    'mapOptions' => 'Inställningar',
    'mapPlay' => 'Spela',
    'mapPlayLink' => 'Spela Bana',
    'mapAuthor' => 'Skapare',
    'mapCreatedBy' => 'Skapad av',
    'backToMaps' => 'Tillbaka till banor',
    'playThisMap' => 'Spela denna bana',
    'search' => 'Sök',
    'myMaps' => 'Mina banor',
    'mapsByUser' => ':name\'s banor',
    'displayUnpublished' => 'Visa :cnt ej publicerade banor',
    'displayPublished' => 'Visa :cnt publicerade banor',
    'usersMapMedals' => ':name\'s ban medaljer',
    'usersCompletedMaps' => ':name\'s avklarade banor',
    'showRecords' => 'visa rekord',
    'details' => 'Detaljer',
    'playedBy' => 'Spelad av',
    'latestMapGames' => 'De senaste ban spelen',

    /* Stats */
    'improvementStats' => 'Förbättringsstatistik',
    //keep ':name'
    'improvementInfo' => 'Följande diagram visar linje-tävlings tid (Y-axel) vs spel tid (X axel). Markerad linje visar förrbättringar i :name\'s personliga rekord. Du kan placera din muspekare var du vill för att visa spel detaljerna.',
    'date' => 'Datum',
    'result' => 'Resultat',
    'submit' => 'Skicka in',
    'qSettings' => 'Query inställningar',
    'dispAll' => 'Visa alla spel',
    
    /* About */
    'aboutInfo' => 'Jstris är ett simpelt online flerspelarspelar block spel byggt i Javascript, HTML5 och Python (server).',
    'version' => 'Version',
    'changelog' => 'Ändringslogg',
    'discussion' => 'Diskussion',
    'learnMore' => 'Läs mer',
    'contact' => 'Kontakt',
    'serverCoverage' => 'Server cost coverage',
    'supporters' => 'Projekt stödjare',
    'translators' => 'Översättare',
    'moderators' => 'Moderatorer',
    
    /* Other */
    'notFound' => 'Ej hittad.',
    'invalidLink' => 'Begärd länk är ogiltig.',
    'brb' => 'Be right back.',
    'tryAgain' => 'Sidan uppdateras just nu, vänligen försök igen om en liten stund.',

    /* Settings - Other options */
    'setOther' => 'Andra inställningar',
    'hideAcc' => 'Gömt konto',
    'accVisibility' => 'Synlighet',
    'hideAccInfo' => 'Om aktiverad, kommer kontot exkluderas från officiella topplistor.',

    /* Chat reports */
    'reportU' => 'Rapportera spelare',
    'reportDesc' => 'Här kan du skapa en rapport om du tror att någon har missbrukat spelchatten.',
    'user' => 'Användare',
    'reason' => 'Anledning',
    'rr0' => 'Spam eller oönskad reklam',
    'rr1' => 'Sexuellt kontent',
    'rr2' => 'Hat språk',
    'rr3' => 'Trakassering eller mobbning',
    'rr4' => 'Annan (specifiera)',
    'sendReport' => 'Skicka Rapport',
    
];
