<?php

return [
    'leaderboard' => 'ランキング',
    'tournament' => 'トーナメント',
    'maps' => 'マップ',
    'mapsBrowse' => '一覧',
    'myMaps' => 'あなたのマップ',
    'mapsDesigner' => 'マップを作成',
    'mapsLatestGames' => '新着リプレイ',
    'guide' => 'ヘルプ',
    'login' => 'ログイン',
    'register' => '登録',
    'myProfile' => 'プロフィール',
    'myImprovement' => 'ステータスの推移',
    'favReplays' => 'お気に入りのリプレイ',
    'settings' => 'アカウント設定',
    'logout' => 'ログアウト',
    
    /* Leaderboard */
    'name' => '名前',
    'time' => '時間',
    'blocks' => 'ブロック',
    'PPS' => 'PPS',
    'finesse' => '最適化ミス',
    'date' => '日付',
    'replay' => 'リプレイ',
    'place' => '順位',
    'nli' => 'ログインしていません！',
    'today' => '今日',
    'lastWeek' => '一週間以内',
    'lastMonth' => '一ヶ月以内',
    'lastYear' => '一年以内',
    'allTime' => 'すべて',
    'bestPlayers' => 'プレイヤー重複なし',
    'bestGames' => 'プレイヤー重複あり',
    'bestSubs' => '〜秒以下のみ',
    'latestGames' => '新着リプレイ',
    'leastBlocks' => '設置ブロック数順',
    'myTimes' => '自分の記録のみ',
    'perfectFinesse' => '最適化ミス0',
    
    /* Replay */
    'load' => '読み込み',
    'play' => '再生',
    'pause' => '一時停止',
    'showSeg' => '区間を表示',
    'fastestSeg' => '最も早い区間',
    'slowestSeg' => '最も遅い区間',
    'speedChart' => 'スピードのグラフ',
    'moreStats' => '他の統計量',
    'lines' => 'ライン',
    'scoringPlaylist' => 'スコアイベント一覧',
    'filterSP' => '一覧表にフィルターを掛ける',
    'applyFilter' => 'フィルターを適用',
    'timestamp' => '時刻',
    'action' => 'アクション', // e.g. combo, tspin, perfect clear
    'scoreEq' => '獲得スコア',
    'position' => '再生位置', //position in a replay
    'lAVG' => '局所平均',
    'gAVG' => '全体平均',
    'repHelp' => '使い方', //link that shows information how to use the tool
    
    /* PW change */
    'pwChange' => 'パスワード変更',
    'newPw' => '新しいパスワード',
    'againPw' => '確認のためもう一度入れてください',
    'applyChange' => '変更を適用',

    /* Localization settings */
    'localSettings' => '言語設定',
    'lang' => '言語',
    'langNone' => '未指定 (トップメニューで変更したい場合)',
    'langDesc' => '使いたい言語を選択',
    'timezone' => 'タイムゾーン',
    'timezoneDesc' => '時刻表示に使用',
    'country' => '国',
    'countryDesc' => '国ごとのランキングを表示する際に使用',
    
    /* Profile */
    'ownProfile' => 'このページは誰でも以下のアドレスからアクセスできます:',
    'bestTimes' => '自己ベスト',
    'allTimes' => 'すべてのスプリントの記録を見る',
    'userImpr' => 'ステータスの推移を見る',
    'gameStats' => '対戦データの統計',
    'latestGames' => '新着の対戦リプレイ',
    'noGames' => 'まだ対戦をプレイしていません',
    'gamesPlayed' => '試合数',
    'totalTime' => 'プレイ時間',
    'linesSent' => '送ったライン合計',
    'linesRec' => '受けたライン合計',
    'placedBlocks' => '置いたブロック合計',
    'maxAPM' => '最大APM',
    'maxREN' => '最大REN数',
    'longestGame' => '最も長かったゲーム',
    'totalB2B' => '合計B2B回数',
    'mostSent' => '送ったライン最大値',
    'hours' => '時間',
    'minutes' => '分',
    'createdMaps' => 'Created maps',
    'viewMapsBy' => '作成されたすべてのマップを表示',
    'playersCount' => '人',
    'gameResultPosition' => '順位',
    'gameResultRoundTime' => 'ゲームの時間',
    'viewAllGamesOf' => ':mode のすべてのゲームを表示',
    'noGamesOf' => ':name はまだ:mode のゲームをプレイしていません。',
    
    /* Maps */
    'map' => 'マップ',
    'mapCreate' => '新しく作る',
    'mapName' => '名前',
    'mapNameLong' => 'マップの名前',
    'mapDesc' => '説明',
    'mapRules' => 'ルール',
    'mapOptions' => '設定',
    'mapPlay' => 'スタート！',
    'mapPlayLink' => 'マップスタート！',
    'mapAuthor' => '著者',
    'mapCreatedBy' => '作成者：',
    'backToMaps' => 'マップリストに戻る',
    'playThisMap' => 'マップをプレイ',
    'search' => '探す',
    'myMaps' => 'あなたのマップ',
    'mapsByUser' => ':name のマップ',
    'displayUnpublished' => ':cnt つの非公開マップを表示',
    'displayPublished' => ':cnt つの公開マップを表示',
    'usersMapMedals' => ':name のマップメダル',
    'usersCompletedMaps' => ':name が完成したマップ',
    'showRecords' => '自己ベスト',
    'details' => '細部',
    'playedBy' => '再生：',
    'latestMapGames' => '最新のマップゲーム',

    /* Stats */
    'improvementStats' => 'ステータスの推移',
    //keep ':name'
    'improvementInfo' => '縦軸にスプリント等のタイム、横軸に日付(日/月/年)をとったグラフです。折れ線は:nameさんのベストタイムの推移を表します。グラフ中の点にマウスカーソルを合わせることで各ゲームの詳細を見ることができます。',
    'date' => '日付',
    'result' => '結果',
    'submit' => 'グラフを表示',
    'qSettings' => 'クエリーの設定',
    'dispAll' => 'ベストでないゲームも全て表示',
    
    /* About */
    'aboutInfo' => 'JstrisはJavascriptとHTML5とPython(サーバー)で作られたシンプルなオンライン対戦パズルゲームです。',
    'version' => 'バージョン',
    'changelog' => 'チェンジログ',
    'discussion' => '話し合',
    'learnMore' => 'もっと知りたい人向け',
    'contact' => 'コンタクト',
    'serverCoverage' => 'サーバーコストの現況',
    'supporters' => 'プロジェクトのサポーター',
    'translators' => '翻訳者',
    'moderators' => 'モデレーター',
    
    /* Other */
    'notFound' => '見つかりませんでした',
    'invalidLink' => '指定されたリンクは無効です',
    'brb' => 'すぐに戻ります',
    'tryAgain' => 'サイトのアップデート中です。しばらくしてからもう一度お試し下さい。',
];

    /* Settings - Other options */
    'setOther' => 'その他のオプション',
    'hideAcc' => '隠しアカウント',
    'accVisibility' => '可視性',
    'hideAccInfo' => '有効にすると、このアカウントは公開ランキングから除外されます',

    /* Chat reports */
    'reportU' => 'ユーザーを報告する',
    'reportDesc' => 'ここでは、誰かがゲームチャットを悪用したと思われる場合にレポートを作成できます。',
    'user' => 'ユーザー',
    'reason' => '理由',
    'rr0' => 'スパムまたは不要な広告',
    'rr1' => '露骨な性的コンテンツ',
    'rr2' => 'ヘイトスピーチ',
    'rr3' => '嫌がらせ',
    'rr4' => 'その他（ご指定ください）',
    'sendReport' => 'レポートを送信',
    
];
