<?php

return [
    'leaderboard' => 'Lider Tablosu',
    'tournament' => 'Turnuva',
    'maps' => 'Haritalar',
    'mapsBrowse' => 'Haritalara Gözat',
    'myMaps' => 'Haritalarım',
    'mapsDesigner' => 'Harita Tasarımcısı',
    'randomMap' => 'Rastgele harita',
    'mapsLatestGames' => 'Son oyunlar',
    'guide' => 'Rehber',
    'login' => 'Giriş yap',
    'register' => 'Kayıt ol',
    'myProfile' => 'Profilim',
    'myImprovement' => 'Gelişim',
    'favReplays' => 'Favori tekrarlar',
    'settings' => 'Ayarlar',
    'logout' => 'Çıkış yap',
    
    /* Leaderboard */
    'name' => 'İsim',
    'time' => 'Süre',
    'blocks' => 'Bloklar',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Tarih',
    'replay' => 'Tekrar oynat',
    'place' => 'Sıra',
    'nli' => 'Giriş yapmadınız!',
    'today' => 'Bugün',
    'lastWeek' => 'Geçen hafta',
    'lastMonth' => 'Geçen ay',
    'lastYear' => 'Geçen yıl',
    'allTime' => 'Tüm zamanlar',
    'bestPlayers' => 'En iyi oyuncular',
    'bestGames' => 'En iyi oyunlar',
    'bestSubs' => 'En iyiler',
    'latestGames' => 'Son oyunlar',
    'leastBlocks' => 'En az blok',
    'myTimes' => 'Sürelerim',
    'perfectFinesse' => '0 finesse',
    
    /* Replay */
    'load' => 'Yükle',
    'play' => 'Oynat',
    'pause' => 'Durdur',
    'showSeg' => 'Segmentleri göster',
    'fastestSeg' => 'En hızlı segment',
    'slowestSeg' => 'En yavaş segment',
    'speedChart' => 'Hız tablosu',
    'moreStats' => 'Daha fazla istatistik',
    'lines' => 'Satırlar',
    'scoringPlaylist' => 'Skor tablosu',
    'filterSP' => 'Skor tablosunu filtrele',
    'applyFilter' => 'Filtreyi uygula',
    'timestamp' => 'Zaman damgası',
    'action' => 'Hamle', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Eşit olduğu skor',
    'position' => 'Pozisyon', //position in a replay
    'lAVG' => 'Yerel ortalama',
    'gAVG' => 'Genel ortalama',
    'repHelp' => 'Yardım', //link that shows information how to use the tool
    'repExport' => 'GIF veya video',
    
    /* PW change */
    'pwChange' => 'Şifreni değiştir',
    'newPw' => 'Yeni şifre',
    'againPw' => 'Tekrardan',
    'applyChange' => 'Değişiklikleri uygula',
    
    /* Localization settings */
    'localSettings' => 'Yerelleştirme seçenekleri',
    'lang' => 'Dil',
    'langNone' => 'Yok (üstteki menüden seçilebilir)',
    'langDesc' => 'Tercih edilen dili seçin',
    'timezone' => 'Zaman dilimi',
    'timezoneDesc' => 'Zamanı sizin zaman diliminize göre ayarlamak için kullanılır.',
    'country' => 'Ülke',
    'countryDesc' => 'Ülke bazında lider tablolarını göstermek için kullanılır.',
    
    /* Profile */
    'ownProfile' => 'Bu sizin ulaşılabilir profiliniz', //There isn't really a translation for that imo.
    'bestTimes' => 'En iyi süreler',
    'allTimes' => 'Tüm sprint sürelerini göster',
    'userImpr' => 'Gelişme istatistiklerini göster',
    'gameStats' => 'Oyun istatistikleri',
    'latestGames' => 'Son oyunlar',
    'noGames' => 'Bu oyuncu daha önce hiç oynamadı.',
    'gamesPlayed' => 'Oynanan oyunlar',
    'totalTime' => 'Toplam vakit',
    'linesSent' => 'Gönderilen satırlar',
    'linesRec' => 'Alınan satırlar',
    'placedBlocks' => 'Yerleştirilen bloklar',
    'maxAPM' => 'Dakikada en fazla yapılan aksiyon sayısı',
    'maxREN' => 'Maksimum combo',
    'longestGame' => 'En uzun oyun',
    'totalB2B' => 'Toplam B2B\'ler',
    'mostSent' => 'En çok gönderilen',
    'hours' => 'saat',
    'minutes' => 'dakika',
    'createdMaps' => 'Oluşturulan haritalar',
    'viewMapsBy' => 'Şu kişi tarafından oluşturulan tüm haritalar',
    'playersCount' => 'Oyuncular',
    'gameResultPosition' => 'Pozisyon',
    'gameResultRoundTime' => 'Oyun süresi',
    'viewAllGamesOf' => 'Tüm oyunlarını görüntüle :mode',
    'noGamesOf' => ':name daha hiç bir oyun :mode oynamadı.',
    
        /* Maps */
    'map' => 'Harita',
    'mapCreate' => 'Yeni oluştur',
    'mapName' => 'İsim',
    'mapNameLong' => 'Harita Adı',
    'mapDesc' => 'Açıklama',
    'mapRules' => 'Kurallar',
    'mapOptions' => 'Ayarlar',
    'mapPlay' => 'Oyna',
    'mapPlayLink' => 'Play Map',
    'mapAuthor' => 'Yaratıcı',
    'mapCreatedBy' => 'Oluşturan',
    'backToMaps' => 'Haritalara geri dön',
    'playThisMap' => 'Bu haritayı oyna',
    'search' => 'Ara',
    'myMaps' => 'Haritalarım',
    'mapsByUser' => ':name\' ait haritalar',
    'displayUnpublished' => ':cnt Adet yayımlanmamış haritaları göster',
    'displayPublished' => ':cnt Adet yayımlanmış haritaları göster',
    'usersMapMedals' => ':name\' ait harita madalyaları',
    'usersCompletedMaps' => ':name\' ait tamamlanmış haritalar',
    'showRecords' => 'Kayıtları göster',
    'details' => 'Detaylar',
    'playedBy' => 'Tarafından oynandı',
    'latestMapGames' => 'En son harita oyunları',

    /* Stats */
    'improvementStats' => 'Gelişme istatistikleri',
    //keep ':name'
    'improvementInfo' => 'Aşağıdaki grafik yarış süresine (Y axis) karşılık oyun tarihini (X axis) gösterir. Highlightlı çizgi :name\'nin kişisel rekorlarındaki gelişmeyi gösterir. İmleçi çizgi üzerindeki herhangi bir noktaya getirerek daha fazla bilgi öğrenebilirsiniz.',
    'date' => 'Tarih',
    'result' => 'Sonuç',
    'submit' => 'Gönder',
    'qSettings' => 'Sorgu ayarları',
    'dispAll' => 'Tüm oyunları göster',
    
    /* About */
    'aboutInfo' => 'Jstris çok oyunculu basit bir blok oyunudur. Javascript, HTML5 ve Python (sunucu tarafı için) dilleriyle geliştirilmiştir.',
    'version' => 'Versiyon',
    'changelog' => 'Değişiklikler',
    'discussion' => 'Tartışma',
    'learnMore' => 'Daha fazlası',
    'contact' => 'İletişim',
    'serverCoverage' => 'Sunucu maliyeti',
    'supporters' => 'Projeyi destekleyenler',
    'translators' => 'Çevirmenler',
    'moderators' => 'Yöneticiler',
    
    
    /* Other */
    'notFound' => 'Bulunamadı.',
    'invalidLink' => 'Talep edilen link hatalı.',
    'brb' => 'Hemen geri döneceğim.',
    'tryAgain' => 'Site güncelleniyor, lütfen biraz sonra deneyiniz.',
];
