<?php

return [
    'leaderboard' => 'Lider Tablosu',
    'tournament' => 'Turnuva',
    'maps' => 'Haritalar',
    'mapsBrowse' => 'Haritalara Gözat',
    'myMaps' => 'Haritalarım',
    'mapsDesigner' => 'Harita Tasarımcısı',
    'randomMap' => 'Rastgele harita',
    'mapsLatestGames' => 'Son oyunlar',
    'guide' => 'Rehber',
    'login' => 'Giriş yap',
    'register' => 'Kayıt ol',
    'myProfile' => 'Profilim',
    'myImprovement' => 'Gelişim',
    'favReplays' => 'Favori tekrarlar',
    'settings' => 'Ayarlar',
    'logout' => 'Çıkış yap',
    
    /* Leaderboard */
    'name' => 'İsim',
    'time' => 'Süre',
    'blocks' => 'Bloklar',
    'PPS' => 'PPS',
    'finesse' => 'Finesse',
    'date' => 'Tarih',
    'replay' => 'Tekrar oynat',
    'place' => 'Sıra',
    'nli' => 'Giriş yapmadınız!',
    'today' => 'Bugün',
    'lastWeek' => 'Geçen hafta',
    'lastMonth' => 'Geçen ay',
    'lastYear' => 'Geçen yıl',
    'allTime' => 'Tüm zamanlar',
    'bestPlayers' => 'En iyi oyuncular',
    'bestGames' => 'En iyi oyunlar',
    'bestSubs' => 'En iyiler',
    'latestGames' => 'Son oyunlar',
    'leastBlocks' => 'En az blok',
    'myTimes' => 'Sürelerim',
    'perfectFinesse' => '0 finesse',
    
    /* Replay */
    'load' => 'Yükle',
    'play' => 'Oynat',
    'pause' => 'Durdur',
    'showSeg' => 'Segmentleri göster',
    'fastestSeg' => 'En hızlı segment',
    'slowestSeg' => 'En yavaş segment',
    'speedChart' => 'Hız tablosu',
    'moreStats' => 'Daha fazla istatistik',
    'lines' => 'Satırlar',
    'scoringPlaylist' => 'Skor tablosu',
    'filterSP' => 'Skor tablosunu filtrele',
    'applyFilter' => 'Filtreyi uygula',
    'timestamp' => 'Zaman damgası',
    'action' => 'Hamle', // e.g. combo, tspin, perfect clear
    'scoreEq' => 'Eşit olduğu skor',
    'position' => 'Pozisyon', //position in a replay
    'lAVG' => 'Yerel ortalama',
    'gAVG' => 'Genel ortalama',
    'repHelp' => 'Yardım', //link that shows information how to use the tool
    'repExport' => 'GIF veya video',
    
    /* PW change */
    'pwChange' => 'Şifreni değiştir',
    'newPw' => 'Yeni şifre',
    'againPw' => 'Tekrardan',
    'applyChange' => 'Değişiklikleri uygula',
    'emailChange' => 'E-postayı değiştir',
    'currentEmail' => 'Geçerli',
    'newEmail' => 'Yeni e-posta',
    
    /* Localization settings */
    'localSettings' => 'Yerelleştirme seçenekleri',
    'lang' => 'Dil',
    'langNone' => 'Yok (üstteki menüden seçilebilir)',
    'langDesc' => 'Tercih edilen dili seçin',
    'timezone' => 'Zaman dilimi',
    'timezoneDesc' => 'Zamanı sizin zaman diliminize göre ayarlamak için kullanılır.',
    'country' => 'Ülke',
    'countryDesc' => 'Ülke bazında lider tablolarını göstermek için kullanılır.',
    
    /* Profile */
    'ownProfile' => 'Bu sizin ulaşılabilir profiliniz', //There isn't really a translation for that imo.
    'bestTimes' => 'En iyi süreler',
    'allTimes' => 'Tüm sprint sürelerini göster',
    'userImpr' => 'Gelişme istatistiklerini göster',
    'gameStats' => 'Oyun istatistikleri',
    'latestGames' => 'Son oyunlar',
    'noGames' => 'Bu oyuncu daha önce hiç oynamadı.',
    'gamesPlayed' => 'Oynanan oyunlar',
    'totalTime' => 'Toplam vakit',
    'linesSent' => 'Gönderilen satırlar',
    'linesRec' => 'Alınan satırlar',
    'placedBlocks' => 'Yerleştirilen bloklar',
    'maxAPM' => 'Dakikada en fazla yapılan aksiyon sayısı',
    'maxREN' => 'Maksimum combo',
    'longestGame' => 'En uzun oyun',
    'totalB2B' => 'Toplam B2B\'ler',
    'mostSent' => 'En çok gönderilen',
    'hours' => 'saat',
    'minutes' => 'dakika',
    'createdMaps' => 'Oluşturulan haritalar',
    'viewMapsBy' => 'Şu kişi tarafından oluşturulan tüm haritalar',
    'playersCount' => 'Oyuncular',
    'gameResultPosition' => 'Pozisyon',
    'gameResultRoundTime' => 'Oyun süresi',
    'viewAllGamesOf' => 'Tüm oyunlarını görüntüle :mode',
    'noGamesOf' => ':name daha hiç bir oyun :mode oynamadı.',
    
        /* Maps */
    'map' => 'Harita',
    'mapCreate' => 'Yeni oluştur',
    'mapName' => 'İsim',
    'mapNameLong' => 'Harita Adı',
    'mapDesc' => 'Açıklama',
    'mapRules' => 'Kurallar',
    'mapOptions' => 'Ayarlar',
    'mapPlay' => 'Oyna',
    'mapPlayLink' => 'Play Map',
    'mapAuthor' => 'Yaratıcı',
    'mapCreatedBy' => 'Oluşturan',
    'backToMaps' => 'Haritalara geri dön',
    'playThisMap' => 'Bu haritayı oyna',
    'search' => 'Ara',
    'myMaps' => 'Haritalarım',
    'mapsByUser' => ':name\' ait haritalar',
    'displayUnpublished' => ':cnt Adet yayımlanmamış haritaları göster',
    'displayPublished' => ':cnt Adet yayımlanmış haritaları göster',
    'usersMapMedals' => ':name\' ait harita madalyaları',
    'usersCompletedMaps' => ':name\' ait tamamlanmış haritalar',
    'showRecords' => 'Kayıtları göster',
    'details' => 'Detaylar',
    'playedBy' => 'Tarafından oynandı',
    'latestMapGames' => 'En son harita oyunları',

    /* Stats */
    'improvementStats' => 'Gelişme istatistikleri',
    //keep ':name'
    'improvementInfo' => 'Aşağıdaki grafik yarış süresine (Y axis) karşılık oyun tarihini (X axis) gösterir. Highlightlı çizgi :name\'nin kişisel rekorlarındaki gelişmeyi gösterir. İmleçi çizgi üzerindeki herhangi bir noktaya getirerek daha fazla bilgi öğrenebilirsiniz.',
    'date' => 'Tarih',
    'result' => 'Sonuç',
    'submit' => 'Gönder',
    'qSettings' => 'Sorgu ayarları',
    'dispAll' => 'Tüm oyunları göster',
    
    /* About */
    'aboutInfo' => 'Jstris çok oyunculu basit bir blok oyunudur. Javascript, HTML5 ve Python (sunucu tarafı için) dilleriyle geliştirilmiştir.',
    'version' => 'Versiyon',
    'changelog' => 'Değişiklikler',
    'discussion' => 'Tartışma',
    'learnMore' => 'Daha fazlası',
    'contact' => 'İletişim',
    'serverCoverage' => 'Sunucu maliyeti',
    'supporters' => 'Projeyi destekleyenler',
    'translators' => 'Çevirmenler',
    'moderators' => 'Yöneticiler',
    
    
    /* Other */
    'notFound' => 'Bulunamadı.',
    'invalidLink' => 'Talep edilen link hatalı.',
    'brb' => 'Hemen geri döneceğim.',
    'tryAgain' => 'Site güncelleniyor, lütfen biraz sonra deneyiniz.',

    'continent' => 'Kıta',
    'blockCnt' => ':cnt blokları',
    'APM10Games' => '10-oyun DBS',
    'PPS10Games' => '10-games SBP',
    'setOther' => 'Diğer seçenekler',
    'hideAcc' => 'Gizlenmiş hesap',
    'accVisibility' => 'Görünürlük',
    'hideAccInfo' => 'Etkinleştirilirse, hesap herkese açık skor tablolarından hariç tutulur.',
    'reportU' => 'Kullanıcıyı bildir',
    'reportDesc' => 'Burada birinin oyun sohbetini kötüye kullandığını düşünüyorsanız bir rapor oluşturabilirsiniz.',
    'user' => 'Kulanıcı',
    'reason' => 'Gerekçe',
    'rr0' => 'Spam veya istenmeyen reklamlar',
    'rr1' => 'Müstehcen içerik',
    'rr2' => 'Nefret söylemi',
    'rr3' => 'Taciz veya zorbalık',
    'rr4' => 'Diğer (belirtin)',
    'sendReport' => 'Rapor gönder',
    
    /* Settings - Navigation */
    'setProfileNav' => 'Profil',
    'setLocalizationNav' => 'Yerelleştirme',
    'setPasswordNav' => 'Şifre',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => 'Diğer',

    /* Settings - Discord */
    'setDiscordTitle' => 'Discord\'u bağla',
    'disconnect' => 'Bağlantıyı kes',
    'connectDiscord' => 'Discord\'u bağla',

    /* Settings - Other */
    'setExperiments' => 'Deneyler',
    'setExperimentsDesc' => 'Deneysel/tamamlanmamış özelliklere test erişimini etkinleştir',
    'setExperimentsNote' => 'Test edilen özelliklerle ilgili fikirlerini Jstris Discord\'unda paylaş',
    'deleteAccount' => 'Hesabı sil',

    /* Settings - Supporter History */
    'returnBack' => 'Geri dön',
    'giftBalanceHistory' => 'Hediye bakiyesi geçmişi',
    'message' => 'Mesaj',
    'change' => 'Değişim',
    'before' => 'Önce',
    'after' => 'Sonra',
    'relative' => 'Bağıl',
    'none' => 'Yok',

    /* Settings - Supporter Status */
    'subscription' => 'Abonelik',
    'active' => 'aktif',
    'manage' => 'Yönet',
    'renewsOn' => 'Yenilenme tarihi:',
    'oneTime' => 'Tek seferlik',
    'expires' => 'Sona eriyor',
    'extend' => 'Uzat',
    'giftingBalance' => 'Hediye bakiyesi',
    'days' => 'gün',
    'add' => 'Ekle',
    'useCode' => 'Kod kullan',
    'balanceHistory' => 'Bakiye geçmişi',
    'noExpiration' => 'Süresiz',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => 'Özel görsel yükle',
    'uploadCustomImageDesc' => 'Jstris\'te herkese açık profil resmi olarak kullanılacak görseli seç. Uygunsuz olarak bildirildiğinde kaldırılabilir.',
    'supporterOption' => 'Supporter seçeneği',
    'seeDetails' => 'Detayları gör',
    'uploadPreviewCrop' => 'Önizleme ve kırpma için yükle',

    /* Settings - Profile */
    'remove' => 'Kaldır',
    'noImageSelected' => 'Henüz görsel seçilmedi',
    'bioPlaceholder' => 'Profilinde görünecek mesajı gir',
    'bioFormatInfo' => 'Hiperlinkleri şu şekilde biçimlendirebilirsin: [YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Supporter hesaplar biçimlendirme, bağlantı ve emoji kullanabilir',
    'selectProfileImage' => 'Profil görseli seç',
    'jstrisBlocks' => 'Jstris blokları',
    'animalArt' => 'Hayvan sanatı',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris reklamsızdır ve herkes için ücretsizdir. Destekleyerek şu avantajları açabilirsin:',
    'benefitProfileCustomizations' => 'Profil özelleştirmeleri',
    'benefitProfileCustomizationsDesc' => 'Özel profil görseli yükleyebilir ve profildeki "Hakkında" mesajında gelişmiş biçimlendirme kullanabilirsin (2000 karaktere kadar, link ve emojiler).',
    'benefitSaveMatchesBots' => 'Botlara karşı maçları kaydet',
    'benefitSaveMatchesBotsDesc' => 'Botlara karşı 1v1 maçların tekrarlar ve gelişmiş istatistiklerle birlikte sonuçlara kaydedilir.',
    'benefitUnlimitedReplays' => 'Sınırsız tekrar',
    'benefitUnlimitedReplaysDesc' => 'Supporter aktifyken tek oyunculu mod tekrarların silinmez.',
    'getSupporterCta' => 'Jstris Supporter edin!',
    'configureBenefits' => 'Avantajları yapılandır',
    'nameChange' => 'İsim değişikliği',
    'nameChangeInfo' => 'Supporter olarak ayda bir isim değişikliği yapabilirsin. Buradan değiştir:',
    'newNameLabel' => 'Yeni isim',
    'newNamePlaceholder' => 'Yeni kullanıcı adı gir',
    'manageSubscriptionTitle' => 'Jstris aboneliğini yönet',
    'manageSubscriptionInfo1' => 'Durdurmak/iptal için PayPal\'a giriş yap ve Abonelik panelinde ilgili seçeneği seç.',
    'manageSubscriptionInfo2' => 'Sorunlarda: jstris@jezevec10.com.',
    'close' => 'Kapat',

    ];
