<?php

return [
    'leaderboard' => '排行榜',
    'tournament' => '锦标赛',
    'maps' => '地图',
    'mapsBrowse' => '浏览',
    'myMaps' => '我的地图',
    'mapsDesigner' => '地图设计器',
    'randomMap' => '随机地图',
    'mapsLatestGames' => '最新游戏',
    'guide' => '游戏指南',
    'login' => '登录',
    'register' => '注册',
    'myProfile' => '我的个人资料',
    'myImprovement' => '我的进步数据',
    'favReplays' => '已收藏录像',
    'friends' => '好友',
    'settings' => '设置',
    'logout' => '退出登录',
    
    /* Leaderboard */
    'name' => '玩家名',
    'time' => '时间',
    'blocks' => '块数',
    'PPS' => 'PPS',
    'finesse' => '多余操作',
    'date' => '日期',
    'replay' => '回放',
    'place' => '排名',
    'nli' => '未登录！',
    'today' => '今日',
    'lastWeek' => '截至上周',
    'lastMonth' => '截至上月',
    'lastYear' => '截至去年',
    'allTime' => '所有时间',
    'bestPlayers' => '最佳玩家',
    'bestGames' => '最佳游戏',
    'bestSubs' => '时间段内最佳(Sub)',
    'latestGames' => '最近游戏',
    'leastBlocks' => '最少方块数',
    'myTimes' => '我的时间',
    'perfectFinesse' => '无多余操作',
    'mostGames' => '最多游戏次数',
    
    /* Replay */
    'load' => '读取',
    'play' => '播放',
    'pause' => '暂停',
    'showSeg' => '展示分段',
    'fastestSeg' => '最快部分',
    'slowestSeg' => '最慢部分',
    'speedChart' => '速度曲线',
    'moreStats' => '更多数据',
    'lines' => '行数',
    'scoringPlaylist' => '分数表',
    'filterSP' => '过滤分数表',
    'applyFilter' => '应用过滤',
    'timestamp' => '时间',
    'action' => '动作', // e.g. combo, tspin, perfect clear
    'scoreEq' => '得分',
    'position' => '位置', //position in a replay
    'lAVG' => '邻域平均值',
    'gAVG' => '全局平均值',
    'repHelp' => '帮助', //link that shows information how to use the tool
    'repExport' => 'GIF或视频',
    
    /* PW change */
    'pwChange' => '更改密码',
    'newPw' => '新密码',
    'againPw' => '重复',
    'applyChange' => '应用更改',
    'emailChange' => '更改邮箱',
    'currentEmail' => '当前',
    'newEmail' => '新邮箱',
    
    /* Localization settings */
    'localSettings' => '本地化设定',
    'lang' => '语言 (Language) ',
    'langNone' => '无（在顶端菜单修改）',
    'langDesc' => '选择语言偏好',
    'timezone' => '时区',
    'timezoneDesc' => '用于将时间转换为你所在当地时间.',
    'country' => '国家',
    'continent' => '洲属',
    'countryDesc' => '设置后可应用于国家内排行榜.',

    /* Profile */
    'ownProfile' => '您的公共个人资料可访问在',
    'bestTimes' => '最佳时间',
    'allTimes' => '查看所有竞速模式时间',
    'userImpr' => '查看进步数据',
    'gameStats' => '游戏数据',
    'latestGames' => '最近游戏',
    'userRanking' => '排名数据',
    'noGames' => '该用户未曾进行任何游戏.',
    'gamesPlayed' => '游戏数',
    'totalTime' => '总时间',
    'linesSent' => '发送行数',
    'linesRec' => '接收行数',
    'placedBlocks' => '放置方块数',
    'blockCnt' => ':cnt 块',
    'APM10Games' => '近10场APM',
    'PPS10Games' => '近10场PPS',
    'maxAPM' => '最大APM（攻击/分）',
    'maxREN' => '最大连击(Combo)',
    'longestGame' => '最长游戏',
    'totalB2B' => 'B2B总计',
    'mostSent' => '最多送行',
    'hours' => '小时',
    'minutes' => '分钟',
    'createdMaps' => '创建的地图',
    'viewMapsBy' => '查看此玩家创建的所有地图:',
    'playersCount' => '玩家数',
    'gameResultPosition' => '排名',
    'gameResultRoundTime' => '游戏时间',
    'viewAllGamesOf' => '查看:mode模式的所有游戏',
    'noGamesOf' => ':name尚未游玩过:mode模式.',
    
    /* Maps */
    'map' => '地图',
    'mapCreate' => '创建新地图',
    'mapName' => '地图名',
    'mapNameLong' => '地图名称',
    'mapDesc' => '说明',
    'mapRules' => '规则',
    'mapOptions' => '选项',
    'mapPlay' => '游玩预览',
    'mapPlayLink' => '游玩地图',
    'mapAuthor' => '作者',
    'mapCreatedBy' => '作者',
    'backToMaps' => '返回地图列表',
    'playThisMap' => '游玩此地图',
    'search' => '搜索',
    'myMaps' => '我的地图',
    'mapsByUser' => ':name的地图',
    'displayUnpublished' => '显示:cnt个未发表地图',
    'displayPublished' => '显示:cnt个已发布地图',
    'usersMapMedals' => ':name的地图徽章',
    'usersCompletedMaps' => ':name的已完成地图',
    'showRecords' => '显示记录',
    'details' => '详细',
    'playedBy' => '玩家:',
    'latestMapGames' => '地图模式最新游戏',

    /* Stats */
    'improvementStats' => '进步数据',
    //keep ':name'
    'improvementInfo' => '以下图表展示了消行竞速时间（Y轴）和游戏日期（X轴）的对应关系. 高亮线展示了:name的个人记录. 你可以将鼠标悬停到任意点查看该局游戏详情.',//The following graph shows line race time (Y axis) vs game date (X axis). Highlighted line shows improvements in :name\'s personal records. You can place your cursor over any point to show the game details.
    'date' => '日期',
    'result' => '结果',
    'submit' => '提交',
    'qSettings' => '查询设置',
    'dispAll' => '显示所有游戏',
    
    /* About */
    'aboutInfo' => 'Jstris 是一款简单的在线多人方块游戏. 本游戏使用Javascript、HTML5 和 Python（服务器）搭建.',//is a simple online multiplayer block game built in Javascript, HTML5 and Python (server).
    'version' => '版本',
    'changelog' => '更新历史',
    'discussion' => '讨论区',
    'learnMore' => '获取更多..',
    'contact' => '联系我们',
    'serverCoverage' => '服务器成本覆盖率',
    'supporters' => '项目赞助',
    'translators' => '翻译者',
    'moderators' => '管理员',
    
    /* Other */
    'notFound' => '未找到页面.',
    'invalidLink' => '访问链接无效.',
    'brb' => '马上回来. ',
    'tryAgain' => '网站正在升级，请稍后再试.',
    'wasteDesc' => '未用于 T-Spin 的 T 块占比',

    /* Settings - Other options */
    'setOther' => '其他设置',
    'hideAcc' => '隐藏账号',
    'accVisibility' => '可见性',
    'hideAccInfo' => '开启后，此账号将不计入公共排行榜.',

    /* Chat reports */
    'reportU' => '举报用户',
    'reportDesc' => '在此你可以举报你认为不正当使用游戏聊天的人。',
    'user' => '用户',
    'reason' => '举报理由',
    'rr0' => '刷屏、垃圾广告',
    'rr1' => '色情内容',
    'rr2' => '谩骂、仇恨言论',
    'rr3' => '骚扰、霸凌、人身攻击',
    'rr4' => '其他（特别说明）',
    'sendReport' => '提交举报',

    /* Friends */
    'friends' => '好友',
    'accept' => '同意',
    'ignore' => '忽略',
    'pending' => '待处理请求',
    'frFilter' => 'Filter Names',
    'noPending' => '暂无待处理好友请求。',
    'onlineNow' => '在线',
    'recentlyAc' => '近期活动过',
    'lastActive' => ':when 前在线',
    'noFriends' => '目前没有好友。',
    'ruSure' => '确定吗?',
    'rmFriend' => '确定要将该用户移出好友列表?',
    'rmConfirm' => '是，移出',
    
    /* Settings - Navigation */
    'setProfileNav' => '个人资料',
    'setLocalizationNav' => '本地化',
    'setPasswordNav' => '密码',
    'setSupporterNav' => 'Supporter',
    'setOtherNav' => '其他',

    /* Settings - Discord */
    'setDiscordTitle' => '连接 Discord',
    'disconnect' => '断开连接',
    'connectDiscord' => '连接 Discord',

    /* Settings - Other */
    'setExperiments' => '实验功能',
    'setExperimentsDesc' => '启用对实验性/未完成功能的测试访问',
    'setExperimentsNote' => '在 Jstris 的 Discord 频道分享你的想法',
    'deleteAccount' => '删除账号',

    /* Settings - Supporter History */
    'returnBack' => '返回',
    'giftBalanceHistory' => '赠送余额历史',
    'message' => '消息',
    'change' => '更改',
    'before' => '之前',
    'after' => '之后',
    'relative' => '相对',
    'none' => '无',

    /* Settings - Supporter Status */
    'subscription' => '订阅',
    'active' => '有效',
    'manage' => '管理',
    'renewsOn' => '续订日期：',
    'oneTime' => '一次性',
    'expires' => '到期',
    'extend' => '延长',
    'giftingBalance' => '赠送余额',
    'days' => '天',
    'add' => '添加',
    'useCode' => '使用代码',
    'balanceHistory' => '余额历史',
    'noExpiration' => '不过期',

    /* Settings - Upload Custom Image */
    'uploadCustomImage' => '上传自定义图片',
    'uploadCustomImageDesc' => '选择一张图片作为 Jstris 的公共头像。如被举报不当可能会被移除。',
    'supporterOption' => 'Supporter 选项',
    'seeDetails' => '查看详情',
    'uploadPreviewCrop' => '上传以预览和裁剪',

    /* Settings - Profile */
    'remove' => '移除',
    'noImageSelected' => '尚未选择图片',
    'bioPlaceholder' => '输入将在你的个人资料中显示的消息',
    'bioFormatInfo' => '你可以这样格式化链接：[YouTube](https://youtu.be/dQw4w9WgXcQ)',
    'bioFormatInfoNonPrem' => 'Supporter 账户可使用格式化、插入链接和表情',
    'selectProfileImage' => '选择头像图片',
    'jstrisBlocks' => 'Jstris 方块',
    'animalArt' => '动物艺术',

    /* Settings - Supporter page */
    'jstrisSupporterTitle' => 'Jstris Supporter',
    'supporterLead' => 'Jstris 无广告且对所有人免费。支持我们可解锁以下福利：',
    'benefitProfileCustomizations' => '资料自定义',
    'benefitProfileCustomizationsDesc' => '可上传自定义头像，并在“关于”信息中使用扩展格式（最多2000字符，可用超链接与表情）。',
    'benefitSaveMatchesBots' => '保存与机器人对局',
    'benefitSaveMatchesBotsDesc' => '你与机器人的 1v1 对局会保存到结果中，包括回放和高级统计。',
    'benefitUnlimitedReplays' => '回放无限保留',
    'benefitUnlimitedReplaysDesc' => 'Supporter 有效期间，你的单人模式回放不会被删除。',
    'getSupporterCta' => '获取 Jstris Supporter！',
    'configureBenefits' => '配置福利',
    'nameChange' => '修改名称',
    'nameChangeInfo' => '作为 Supporter，你每月可修改一次名称。可在此修改：',
    'newNameLabel' => '新名称',
    'newNamePlaceholder' => '输入新的用户名',
    'manageSubscriptionTitle' => '管理 Jstris 订阅',
    'manageSubscriptionInfo1' => '暂停或取消订阅：登录 PayPal 并在订阅面板选择相应选项。',
    'manageSubscriptionInfo2' => '遇到问题请联系 jstris@jezevec10.com。',
    'close' => '关闭',
];
