<?php

return [
    'leaderboard' => '排行榜',
    'tournament' => '锦标赛',
    'maps' => '地图',
    'mapsBrowse' => '浏览',
    'myMaps' => '我的地图',
    'mapsDesigner' => '地图设计器',
    'randomMap' => '随机地图',
    'mapsLatestGames' => '最新游戏',
    'guide' => '游戏指南',
    'login' => '登录',
    'register' => '注册',
    'myProfile' => '我的个人资料',
    'myImprovement' => '我的进步数据',
    'favReplays' => '已收藏录像',
    'settings' => '设置',
    'logout' => '退出登录',
    
    /* Leaderboard */
    'name' => '玩家名',
    'time' => '时间',
    'blocks' => '块数',
    'PPS' => 'PPS',
    'finesse' => '多余操作',
    'date' => '日期',
    'replay' => '回放',
    'place' => '排名',
    'nli' => '未登录！',
    'today' => '今日',
    'lastWeek' => '截至上周',
    'lastMonth' => '截至上月',
    'lastYear' => '截至去年',
    'allTime' => '所有时间',
    'bestPlayers' => '最佳玩家',
    'bestGames' => '最佳游戏',
    'bestSubs' => '时间段内最佳(Sub)',
    'latestGames' => '最近游戏',
    'leastBlocks' => '最少方块数',
    'myTimes' => '我的时间',
    'perfectFinesse' => '无多余操作',
    
    /* Replay */
    'load' => '读取',
    'play' => '播放',
    'pause' => '暂停',
    'showSeg' => '展示分段',
    'fastestSeg' => '最快部分',
    'slowestSeg' => '最慢部分',
    'speedChart' => '速度曲线',
    'moreStats' => '更多数据',
    'lines' => '行数',
    'scoringPlaylist' => '分数表',
    'filterSP' => '过滤分数表',
    'applyFilter' => '应用过滤',
    'timestamp' => '时间',
    'action' => '动作', // e.g. combo, tspin, perfect clear
    'scoreEq' => '得分',
    'position' => '位置', //position in a replay
    'lAVG' => '邻域平均值',
    'gAVG' => '全局平均值',
    'repHelp' => '帮助', //link that shows information how to use the tool
    'repExport' => 'GIF或视频',
    
    /* PW change */
    'pwChange' => '更改密码',
    'newPw' => '新密码',
    'againPw' => '重复',
    'applyChange' => '应用更改',
    
    /* Localization settings */
    'localSettings' => '本地化设定',
    'lang' => '语言 (Language) ',
    'langNone' => '无（在顶端菜单修改）',
    'langDesc' => '选择语言偏好',
    'timezone' => '时区',
    'timezoneDesc' => '用于将时间转换为你所在当地时间.',
    'country' => '国家',
    'continent' => '洲属',
    'countryDesc' => '设置后可应用于国家内排行榜.',
    /* Profile */
    'ownProfile' => '您的公共个人资料可访问在',
    'bestTimes' => '最佳时间',
    'allTimes' => '查看所有竞速模式时间',
    'userImpr' => '查看进步数据',
    'gameStats' => '游戏数据',
    'latestGames' => '最近游戏',
    'noGames' => '该用户未曾进行任何游戏.',
    'gamesPlayed' => '游戏数',
    'totalTime' => '总时间',
    'linesSent' => '发送行数',
    'linesRec' => '接收行数',
    'placedBlocks' => '放置方块数',
    'blockCnt' => ':cnt 块',
    'APM10Games' => '近10场APM',
    'PPS10Games' => '近10场PPS',
    'maxAPM' => '最大APM（攻击/分）',
    'maxREN' => '最大连击(Combo)',
    'longestGame' => '最长游戏',
    'totalB2B' => 'B2B总计',
    'mostSent' => '最多送行',
    'hours' => '小时',
    'minutes' => '分钟',
    'createdMaps' => '创建的地图',
    'viewMapsBy' => '查看此玩家创建的所有地图:',
    'playersCount' => '玩家数',
    'gameResultPosition' => '排名',
    'gameResultRoundTime' => '游戏时间',
    'viewAllGamesOf' => '查看:mode模式的所有游戏',
    'noGamesOf' => ':name尚未游玩过:mode模式.',
    
    /* Maps */
    'map' => '地图',
    'mapCreate' => '创建新地图',
    'mapName' => '地图名',
    'mapNameLong' => '地图名称',
    'mapDesc' => '说明',
    'mapRules' => '规则',
    'mapOptions' => '选项',
    'mapPlay' => '游玩',
    'mapPlayLink' => '游玩地图',
    'mapAuthor' => '作者',
    'mapCreatedBy' => '作者',
    'backToMaps' => '返回地图列表',
    'playThisMap' => '游玩此地图',
    'search' => '搜索',
    'myMaps' => '我的地图',
    'mapsByUser' => ':name的地图',
    'displayUnpublished' => '显示:cnt个未发表地图',
    'displayPublished' => '显示:cnt个已发布地图',
    'usersMapMedals' => ':name的地图徽章',
    'usersCompletedMaps' => ':name的已完成地图',
    'showRecords' => '显示记录',
    'details' => '详细',
    'playedBy' => '玩家:',
    'latestMapGames' => '地图模式最新游戏',
    /* Stats */
    'improvementStats' => '进步数据',
    //keep ':name'
    'improvementInfo' => '以下图表展示了消行竞速时间（Y轴）和游戏日期（X轴）的对应关系. 高亮线展示了:name的个人记录. 你可以将鼠标悬停到任意点查看该局游戏详情.',//The following graph shows line race time (Y axis) vs game date (X axis). Highlighted line shows improvements in :name\'s personal records. You can place your cursor over any point to show the game details.
    'date' => '日期',
    'result' => '结果',
    'submit' => '提交',
    'qSettings' => '查询设置',
    'dispAll' => '显示所有游戏',
    
    /* About */
    'aboutInfo' => 'Jstris 是一款简单的在线多人方块游戏. 本游戏使用Javascript、HTML5 和 Python（服务器）搭建.',//is a simple online multiplayer block game built in Javascript, HTML5 and Python (server).
    'version' => '版本',
    'changelog' => '更新历史',
    'discussion' => '讨论区',
    'learnMore' => '获取更多..',
    'contact' => '联系我们',
    'serverCoverage' => '服务器成本覆盖率',
    'supporters' => '项目赞助',
    'translators' => '翻译者',
    'moderators' => '管理员',
    
    /* Other */
    'notFound' => '未找到页面.',
    'invalidLink' => '访问链接无效.',
    'brb' => '马上回来. ',
    'tryAgain' => '网站正在升级，请稍后再试.',
];
