<?php

return [
    'play' => 'Играть',
    'live' => 'Против игроков', //"Versus players". -mLurker
    'controls' => 'Управление',
    'gameSettings' => 'Настройки игры',
    'appearance' => 'Вид и Звук', //This string should be "Appearance and Sound" in English. -mLurker
    'more' => '+',
    'gameControls' => 'Управление игры',
    'gameControlsInfo' => 'Нажмите на текстовое окно и выберите желаемую клавишу.',
    'moveLeft' => 'Налево',
    'moveRight' => 'Направо',
    'softDrop' => 'Медленное падение',
    'hardDrop' => 'Быстрое падение',
    'rotateLeft' => 'Поворот налево',
    'rotateRight' => 'Поворот направо',
    'rotate180' => 'Переворот',
    'hold' => 'Замена',
    'touch' => 'Включить управление смахиванием по экрану', //"Turn on swiping (on the screen) controls". -mLurker
    'DAS' => 'DAS', //Unlocalised by community request. -mLurker
    'ARR' => 'ARR', //Unlocalised. -mLurker
    'softDropSpeed' => 'Скорость падения',
    'sdSlow' => 'Медленная',
    'sdMedium' => 'Средняя',
    'sdFast' => 'Быстрая',
    'sdUltra' => 'Ультра',
    'sdInstant' => 'Мгновенная',
    'gridNone' => 'Пустая',
    'gridStandard' => 'Стандартная',
    'gridPartial' => 'Частичная',
    'gridVertical' => 'Вертикальная',
    'gridFull' => 'Полная',
    'grid' => 'Решётка',
    'ghost' => 'Фантомная фигура',
    'enabled' => 'Вкл.',
    'disabled' => 'Выкл.',
    'appearSound' => 'Вид', //This string now describes appearance settings only, changed accordingly. -mLurker
    'blockStyle' => 'Фигуры',
    'solidBlocks' => 'Цвета (без текстур)',
    'invisibleBlocks' => 'Невидимые',
    'monochrome' => 'Один цвет',
    'enableSE' => 'Звуковые эффекты',
    'startSE' => 'Звуковой эффект в начале раунда',
    'faultSE'=> 'Звуковой эффект в случае несоблюдения техники', //No official translation of "Tetris Finesse", wrote "Special sound effect on technique fault". -mLurker
    'esound'=> 'Оповещение о подключении игрока',
    'SEvol'=> 'Громкость зв. эффектов',
    'otherSettings'=> 'Другие настройки',
    'nickname'=> 'Никнейм', //"nickname". "Псевдоним" can be used instead. -mLurker
    'saveReload'=> 'Сохраните и перезапустите игру, чтобы изменения вступили в силу.',
    'sprintReset'=> 'Перезапуск спринта',
    'or'=> 'или',
    'finFault'=> 'Несоблюдение техники', //See "faultSE" for explanation", wrote "Technique fault" -mLurker
    'altResetKeyInfo'=> 'Выберите альтернативную клавишу для перезапуска спринта.',
    'gameReset'=> 'Перезапуск игры',
    'altLiveResetKeyInfo'=> 'Выберите альтернативную клавишу для перезапуска игры.',
    'saveClose'=> 'Сохранить настройки и закрыть',
    'resetAll'=> 'Сброс',
    'close'=> 'Закрыть',
    'gameResults'=> 'Результаты игры',
    'practiceModes'=> 'Режимы для практики',
    'practice'=> 'Практика',
    'sprint'=> 'Спринт',
    'cheese'=> 'Очистка', //No official translation of "Cheese race", wrote "Cleanup" instead. -mLurker
    'freePlay'=> 'Практика', 
    'close'=> 'Закрыть',
    'showMoreDetails' => 'Показать больше',
    'showMore'=> 'Показать больше',
    'showLess'=> 'Показать меньше',
    'lrem'=> 'Осталось рядов',
    'trem'=> 'Осталось времени',
    'toRestart'=> 'чтобы перезапустить',     //used in: press F4 to restart
    'lobby'=> 'Лобби',
    'settings'=> 'Настройки',
    'newGame'=> 'Новая игра',
    'roundTime'=> 'Время раунда',
    'score'=> 'Очки',
    'sent'=> 'Отправлено',
    'received'=> 'Получено',
    'PPS'=> 'Ф./с',
    'APM'=> 'Ат./мин',
    'finesse'=> 'Техника', //See "faultSE" for explanation, wrote "Technique". -mLurker
    'save'=> 'Сохранить',
    'createRoom'=> 'Cоздать комнату',
    'refreshList'=> 'Перезагрузить',
    'roomName'=> 'Название комнаты',
    'playersCount'=> 'Игроки',
    'usePreset' => 'Использовать правила',    //preset = predefined room settings
    'default' => 'По умолчанию', // "Правила" - literally means "rules", but can be used to mean "preset". -mLurker
    'defaultDesc' => 'Правила по умолчанию',
    'otherOptions' => 'Другие правила',
    'customPreset' => 'Использовать пользовательские правила',
    'browsePresets' => 'Просмотреть пользовательские правила',
    'submitPreset' => 'Отправить пользовательские правила',
    'customRooms'=> 'Пользовательские комнаты',
    'gmode'=> 'Режим',
    'gmodeStandard'=> 'Стандартн.',
    'gmodeCheese'=> 'Очистка', //See "cheese" for explanation, wrote "Cleanup" instead. -mLurker
    'isPrivate'=> 'Приватная',
    'simple'=> 'Простые',
    'advanced'=> 'Продвинутые',
    'moreSett'=> 'Больше правил',
    'attack'=> 'Атака',
    'gDist'=> 'Метод атаки',
    'create'=> 'Создать',
    'cancel'=> 'Отменить',
    'about' => 'О сайте',
    'donate' => 'Пожертвовать',
    'hdThread' => 'Ветка в форуме HardDrop', //Obsolete? -mLurker
    'chatSend' => 'Отправить',
    'rememberName' => 'Запомнить никнейм', //See "nickname" for explanation. "Запомнить псевдоним" can be used, too. -mLurker
    'mapDownstack' => 'Карты',
    'survival' => 'Выживание',
    'ultra' => 'Ультра',
    'all' => 'Все',
    'preset' => 'Правила',
    'save' => 'Сохранить',
    'translationBy' => 'metallicLurker, EDETNAOZERO', //Contact me on any uncertainties or details in Discord - metallicLurker
	
	//New strings:
	//from July 29th, 2019. -mLurker
	'rescaleNow' => 'Обновлять поле других игроков сразу',
	'rescaleNowInfo' => 'Если не отметить, то поля новых игроков появятся на след. раунде.',
	'DAScancel' => 'Освежать DAS', //"Refresh DAS". -mLurker
	'DAScancelInfo' => 'Если отметить, то DAS будет отменяться со сменой сторон передвижения.',
	'FPSDAS' => 'Считать DAS по кадрам',
	'FPSDASInfo' => 'Использует мониторные кадры (60 FPS) для считывания DAS. Точность cчёта времени будет снижена.',
	'webGL' => 'Использовать WebGL',
	'KPP' => 'Наж./Ф.',
	'editRoom' => 'Изменить',
	'savePreset' => 'Сохранить настройки',
	'overflowRooms' => 'Запасные комнаты', //"Extra Rooms". -mLurker
	'spectateRooms' => 'Только для наблюдения', //Fixed for context. -mLurker
	'gmodeTeam' => 'Командн.',
	'applyCh' => 'Применить изменения',
	'audioCredits' => 'Авторы аудиофайлов:', //"Authors of the audiofiles". -mLurker
	'fullScreen' => 'В полный экран',
	'showHoldQueue' => 'Показать З.+Оч.',
	'showStats' => 'Показать статистику',
	'roomLimits' => 'Ограничения на вход в комнату',
	'setLimitsInfo' => 'Вы можете поставить ограничения на вход в вашу комнату. Оставьте поля пустыми для снятия ограничении.',
	'addLimit' => 'Добавить ограничения',
	's40L' => 'Время Спринта 40L',
	'accGametime' => 'Общ. время игры',
	'applyClose' => 'Применить и закрыть',
	'teamSel' => 'Выбор команды',
	'myTeam' => 'Вы играете за',
	'seconds' => 'секунды',
	'minutes' => 'минуты',
	'hours' => 'часы',
	'ms' => 'мс',
	's' => 'с',
	'hrs' => 'ч',
	'attackTable' => 'Табл. атаки', //Shortened the prompts* in Advanced settings, as much as possible. Some prompts may have become too short to understand. -mLurker
	'comboTable' => 'Табл. комбо', //*
	'gBlocking' => 'Блок. мусора', //*
	'blocksType' => 'Тип фигур',
	'randomizer' => 'ГСФ', //* "Генератор Случайных Фигур", as in "Random Piece Generator". No short Russian term for "Randomizer" found. -mLurker
	'previews' => 'Дл. очереди', //* As in, "Next queue length". -mLurker
	'solidGarbage' => 'Заполнять', //* As in, "Fill". -mLurker
	'solidAfterSecs' => 'После',
	'lockDelay' => 'Задерж. фикс.', //*
	'clearDelay' => 'Задерж. очист.', //*
	'speedLimit' => 'Лим. скорости', //*
	'gravityLvl' => 'Гравитация',
	'garbageDelay' => 'Задерж. мусора', //*
	'garbageMess' => 'Замеш. мусора', //*
	'solidAtk' => 'Атака полн.', //* As in, "Attack with full". -mLurker
	'noFW' => 'Бан на 4-wide', //* As in, "Ban 4-wide". -mLurker
	'hostStart' => 'Старт от хоз.', //As in, "Start from host". -mLurker
	
	//from August 21st, 2019. -mLurker
	'webGLInfo' => 'Отмените эту настройку если у вас не работает OpenGL рендеринг в :year году.',
	'tsdsCounter' => 'TSD выполнено', //See frontend.php for explanation. -mLurker
	'20TSD' => '20TSD', //Unlocalised. -mLurker
	
	//from January 4th, 2020. -mLurker
	'touchBtn' => 'Включить экранные кнопки',
	'touchBtnMove' => 'Разрешить передвижение экранных кнопок',
	'mLay' => 'Использовать мобильную раскладку',
	'mLayInfo' => 'Отключите эту настройку, чтобы не загружать мобильную раскладку. Потребуется обновление.',
	'allSpin' => 'Все Повороты',
	'asImmobile' => 'По неподвиж.', //Shortened "By immobility". -mLurker
	'as4Point' => 'По 4 точкам', //"By 4 points". -mLurker
	'allSpinNA' => 'Исключить Повороты', //"Exclude Spins". -mLurker
	
	//from January 22nd, 2020. -mLurker
	'pcCounter' => 'Perfect Clears', //Unlocalised. -mLurker
	'PCmode' => 'Режим PC',

	//from May 21st, 2020. -mLurker
	'sound' => 'Звук',
	'enableVSE' => 'Комментатор', //"Announcer". -mLurker
	'rotateSE' => 'Звуковой эффект поворота фигуры', //Obsolete? -mLurker
	
	//from December 7th, 2020. -mLurker
	'DMsound' => 'Напоминиание личн. сообщении',
	'gapWidth' => 'Ширина дыр в мусоре',
	'gInv' => 'Инверт. мусор',
	'lines' => 'Линии',
	'statistics' => 'Статистика',
	'vs' => 'VS', //No term for VS Score. -mLurker
	'downstack' => 'Очистка мусора',
	'wasted' => 'Т Потрачено', //"T Wasted". -mLurker
	'expand' => 'Раскрыть', //Not sure where this is used. -mLurker

	//from October 25th, 2022. -mLurker
	'skin' => 'Фигуры', //"Blocks", may be changed if "blockskin" becomes more common. -mLurker
	'skin2' => 'Вид фигур', //"Block appearance", see above. - mLurker
	'guestRooms' => 'Гостевые комнаты',
	'bots' => 'Боты',
	'rulesets' => 'Наборы правил',
	'solidGarbageSpeed' => 'Скорость заполнения',
];
