<?php

return [
    'play' => 'Играть',
    'live' => 'Против игроков', //"Live" has no close analogy in Russian, wrote "versus players" instead
    'controls' => 'Управление',
    'gameSettings' => 'Настройки игры',
    'appearance' => 'Вид',
    'more' => '+',
    'gameControls' => 'Управление игры',
    'gameControlsInfo' => 'Нажмите на текстовое окно и выберите желаемую клавишу.',
    'moveLeft' => 'Налево',
    'moveRight' => 'Направо',
    'softDrop' => 'Медленное падение',
    'hardDrop' => 'Быстрое падение',
    'rotateLeft' => 'Повернуть налево',
    'rotateRight' => 'Повернуть направо',
    'rotate180' => 'Перевернуть',
    'hold' => 'Замена',
    'touch' => 'Включить сенсорное управление (экспериментально)',
    'DAS' => 'ЗАП', //Custom abbreviation from "Задержка Авто-Передвижения" (Delay of Auto-Movement). -mLukrer
    'ARR' => 'ЧАП', //Custom abbreviation from "Частота Авто-Передвижения" (Rate of Auto-Movement). -mLurker
    'softDropSpeed' => 'Скорость падения',
    'sdSlow' => 'Медленная',
    'sdMedium' => 'Средняя',
    'sdFast' => 'Быстрая',
    'sdUltra' => 'Ультра',
    'sdInstant' => 'Мгновенная',
    'gridNone' => 'Пустая',
    'gridStandard' => 'Стандартная',
    'gridPartial' => 'Частичная',
    'gridVertical' => 'Вертикальная',
    'gridFull' => 'Полная',
    'grid' => 'Решётка',
    'ghost' => 'Фантомная фигура',
    'enabled' => 'Вкл.',
    'disabled' => 'Выкл.',
    'appearSound' => 'Вид и Звук',
    'blockStyle' => 'Фигуры',
    'solidBlocks' => 'Цвета (без текстур)',
    'invisibleBlocks' => 'Невидимые',
    'monochrome' => 'Один цвет',
    'enableSE' => 'Звуковые эффекты',
    'startSE' => 'Звуковой эффект в начале раунда',
    'faultSE'=> 'Звуковой эффект в случае несоблюдения техники', //No appropriate term for "Tetris Finesse" in Russian, wrote "Special sound effect on technique fault". -mLurker
    'esound'=> 'Оповещение о подключении игрока',
    'SEvol'=> 'Громкость зв. эффектов',
    'otherSettings'=> 'Другие настройки',
    'nickname'=> 'Никнейм', //Literally "nickname". "Псевдоним" can be used, too. -mLurker
    'saveReload'=> 'Сохраните и перезапустите игру, чтобы изменения вступили в силу.',
    'sprintReset'=> 'Перезапуск спринта',
    'or'=> 'или',
    'finFault'=> 'Несоблюдение техники', //See "faultSE" for explanation", wrote "Technique fault" -mLurker
    'altResetKeyInfo'=> 'Выберите альтернативную клавишу для перезапуска спринта.',
    'gameReset'=> 'Перезапуск игры',
    'altLiveResetKeyInfo'=> 'Выберите альтернативную клавишу для перезапуска игры.',
    'saveClose'=> 'Сохранить настройки и закрыть',
    'resetAll'=> 'Сброс',
    'close'=> 'Закрыть',
    'gameResults'=> 'Результаты игры',
    'practiceModes'=> 'Режимы для практики',
    'practice'=> 'Практика',
    'sprint'=> 'Спринт',
    'cheese'=> 'Очистка', //No official translation of "Cheese race", wrote "Cleanup" instead. Use "Сырная гонка" for a literal translation. -mLurker
    'freePlay'=> 'Практика', 
    'close'=> 'Закрыть',
    'showMoreDetails' => 'Показать больше',
    'showMore'=> 'Показать больше',
    'showLess'=> 'Показать меньше',
    'lrem'=> 'Осталось рядов',
    'trem'=> 'Осталось времени',
    'toRestart'=> 'чтобы перезапустить',     //used in: press F4 to restart
    'lobby'=> 'Лобби',
    'settings'=> 'Настройки',
    'newGame'=> 'Новая игра',
    'roundTime'=> 'Время раунда',
    'score'=> 'Очки',
    'sent'=> 'Отправлено',
    'received'=> 'Получено',
    'PPS'=> 'Ф./с',
    'APM'=> 'Ат./мин',
    'finesse'=> 'Техника', //See "faultSE" for explanation", wrote "Technique". -mLurker
    'save'=> 'Сохранить',
    'createRoom'=> 'Cоздать комнату',
    'refreshList'=> 'Перезагрузить',
    'roomName'=> 'Название комнаты',
    'playersCount'=> 'Игроки',
    'usePreset' => 'Использовать правила',    //preset = predefined room settings
    'default' => 'По умолчанию', // "Правила" - literally means "rules", but can be used to mean "preset". -mLurker
    'defaultDesc' => 'Правила по умолчанию',
    'otherOptions' => 'Другие правила',
    'customPreset' => 'Использовать пользовательские правила',
    'browsePresets' => 'Просмотреть пользовательские правила',
    'submitPreset' => 'Отправить пользовательские правила',
    'customRooms'=> 'Пользовательские комнаты',
    'gmode'=> 'Режим',
    'gmodeStandard'=> 'Стандартный',
    'gmodeCheese'=> 'Очистка', //See "cheese" for explanation, wrote "Cleanup" instead. Use "Сырная гонка" for a literal translation. -mLurker
    'isPrivate'=> 'Приватная',
    'simple'=> 'Простые',
    'advanced'=> 'Продвинутые',
    'moreSett'=> 'Больше правил',
    'attack'=> 'Атака',
    'gDist'=> 'Метод атаки', //Fixed. -mLurker
    'create'=> 'Создать',
    'cancel'=> 'Отменить',
    'about' => 'О сайте',
    'donate' => 'Подарить',
    'hdThread' => 'Ветка в форуме HardDrop',
    'chatSend' => 'Отправить',
    'rememberName' => 'Запомнить никнейм', //See "nickname" for explanation. "Запомнить псевдоним" can be used, too. -mLurker
    'mapDownstack' => 'Карты', //Updated. -mLurker
    'survival' => 'Выживание',
    'ultra' => 'Ультра',
    'all' => 'Все',
    'preset' => 'Правила',
    'save' => 'Сохранить',
    'translationBy' => 'metallicLurker', //Contact me on any uncertainties or details. -mLurker
	
	//New strings:
	//from July 29th, 2019. -mLurker
	'rescaleNow' => 'Обновлять поле других игроков сразу',
	'rescaleNowInfo' => 'Если не отметить, то поля новых игроков появятся на след. раунде.',
	'DAScancel' => 'Освежать ЗАП', //As in, "Refresh DAS". -mLurker
	'DAScancelInfo' => 'Если отметить, то Авто-Передвижение будет отменяться со сменой сторон передвижения.',
	'FPSDAS' => 'Считать ЗАП по кадрам',
	'FPSDASInfo' => 'Использует мониторные кадры (60 FPS) для считывания ЗАП. Точность cчёта времени будет снижена.',
	'webGL' => 'Использовать WebGL',
	'KPP' => 'Наж./Ф.',
	'editRoom' => 'Изменить',
	'savePreset' => 'Сохранить настройки',
	'overflowRooms' => 'Запасные комнаты', //As in, "Extra Rooms". -mLurker
	'spectateRooms' => 'Комнаты наблюдения',
	'gmodeTeam' => 'Командн.',
	'applyCh' => 'Применить изменения',
	'audioCredits' => 'Авторы аудиофайлов:', //As in, "Authors of the audiofiles". -mLurker
	'fullScreen' => 'В полный экран',
	'showHoldQueue' => 'Показать З.+Оч.',
	'showStats' => 'Показать статистику',
	'roomLimits' => 'Ограничения на вход в комнату',
	'setLimitsInfo' => 'Вы можете поставить ограничения на вход в вашу комнату. Оставьте поля пустыми для снятия ограничении.',
	'addLimit' => 'Добавить ограничения',
	's40L' => 'Время Спринта 40L',
	'accGametime' => 'Общ. время игры',
	'applyClose' => 'Применить и закрыть',
	'teamSel' => 'Выбор команды',
	'myTeam' => 'Вы играете за',
	'seconds' => 'секунды',
	'minutes' => 'минуты',
	'hours' => 'часы',
	'ms' => 'мс',
	's' => 'с',
	'hrs' => 'ч',
	'attackTable' => 'Табл. атаки', //Shortened the prompts* in Advanced settings, as much as possible. Some prompts may have become too short to understand. -mLurker
	'comboTable' => 'Табл. комбо', //*
	'gBlocking' => 'Блок. мусора', //*
	'blocksType' => 'Тип фигур',
	'randomizer' => 'ГСФ', //* "Генератор Случайных Фигур", as in "Random Piece Generator". No short Russian term for "Randomizer" found.
	'previews' => 'Дл. очереди', //* As in, "Next queue length".
	'solidGarbage' => 'Заполнять', //* As in, "Fill".
	'solidAfterSecs' => 'После',
	'lockDelay' => 'Задерж. фикс.', //*
	'clearDelay' => 'Задерж. очист.', //*
	'speedLimit' => 'Лим. скорости', //*
	'gravityLvl' => 'Гравитация',
	'garbageDelay' => 'Задерж. мусора', //*
	'garbageMess' => 'Замеш. мусора', //*
	'solidAtk' => 'Атака полн.', //* As in, "Attack with full".
	'noFW' => 'Бан на 4-ряд', //* As in, "Ban 4-wide". Revert back to "Бан на 4-wide" to avoid localizing.
	'hostStart' => 'Старт от хоз.', //As in, "Start from host".
	//from August 21st, 2019. -mLurker
	'webGLInfo' => 'Отмените эту настройку если у вас не работает OpenGL рендеринг в :year году',
	'tsdsCounter' => 'ТП2 выполнено', //Replace with "TSD выполнено" to avoid localizing. See frontend.php for explanation. -mLurker
	'20TSD' => '20ТП2', //Revert back to "20TSD" to avoid localizing.
];
